import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureInventory() {
  return <FeatureDetail data={{
    category: { sq: "Operacione", en: "Operations", es: "Operaciones", de: "Betrieb", mk: "Операции", fr: "Opérations", pt: "Operações", it: "Operazioni" },
    categoryColor: "bg-teal-500",
    title: { sq: "Menaxhim Inventari", en: "Inventory Management", es: "Gestión de Inventario", de: "Bestandsverwaltung", mk: "Управување со Инвентар" , fr: "Gestion des stocks", pt: "Gestão de inventário", it: "Gestione del magazzino" },
    tagline: { sq: "Kontrolloni stokun, eliminoni humbjet", en: "Control stock, eliminate losses", es: "Controle el stock, elimine pérdidas", de: "Bestand kontrollieren, Verluste eliminieren", mk: "Контролирајте залиха, елиминирајте загуби" , fr: "Contrôlez le stock, éliminez les pertes", pt: "Controle o stock, elimine as perdas", it: "Controlla le scorte, elimina le perdite" },
    stat: { sq: "35% ulje humbje stoku", en: "35% stock loss reduction", es: "35% reducción de pérdida de stock", de: "35% weniger Bestandsverlust", mk: "35% намалување на загуба на залиха" , fr: "35% de réduction des pertes de stock", pt: "35% de redução de perdas de stock", it: "35% di riduzione delle perdite di scorte" },
    description: {
      sq: "Gjurmoni stokun në kohë reale, merrni alarme kur produktet po mbarojnë dhe analizoni lëvizjet e inventarit me raporte të detajuara.",
      en: "Track stock in real time, receive alerts when products are running out and analyze inventory movements with detailed reports.",
      es: "Rastree el stock en tiempo real, reciba alertas cuando los productos se estén agotando y analice los movimientos de inventario con informes detallados.",
      de: "Verfolgen Sie den Bestand in Echtzeit, erhalten Sie Warnungen, wenn Produkte zur Neige gehen, und analysieren Sie Bestandsbewegungen mit detaillierten Berichten.",
      mk: "Следете ги залихите во реално време, добивајте аларми кога производите се при крај и анализирајте ги движењата на инвентарот со детални извештаи.",
    , fr: "Suivez le stock en temps réel, recevez des alertes quand les produits s'épuisent et analysez les mouvements d'inventaire avec des rapports détaillés.", pt: "Acompanhe o stock em tempo real, receba alertas quando os produtos estão a esgotar e analise os movimentos de inventário com relatórios detalhados.", it: "Monitora le scorte in tempo reale, ricevi avvisi quando i prodotti si esauriscono e analizza i movimenti di magazzino con report dettagliati." },
    benefits: [
      { sq: "Gjurmim stoku në kohë reale", en: "Real-time stock tracking", es: "Seguimiento de stock en tiempo real", de: "Echtzeit-Bestandsverfolgung", mk: "Следење на залихи во реално време" , fr: "Suivi du stock en temps réel", pt: "Rastreamento de stock em tempo real", it: "Monitoraggio scorte in tempo reale" },
      { sq: "Alarme stoku minimal", en: "Minimum stock alerts", es: "Alertas de stock mínimo", de: "Mindestbestandswarnungen", mk: "Аларми за минимални залихи" , fr: "Alertes de stock minimum", pt: "Alertas de stock mínimo", it: "Avvisi di scorte minime" },
      { sq: "Skaner barcodi për hyrje/dalje", en: "Barcode scanner for entries/exits", es: "Escáner de código de barras para entradas/salidas", de: "Barcode-Scanner für Ein-/Ausgänge", mk: "Скенер за баркод за влез/излез" , fr: "Scanner de codes-barres pour entrées/sorties", pt: "Leitor de códigos de barras para entradas/saídas", it: "Scanner codici a barre per entrate/uscite" },
      { sq: "Raporte lëvizjesh inventari", en: "Inventory movement reports", es: "Informes de movimientos de inventario", de: "Bestandsbewegungsberichte", mk: "Извештаи за движење на инвентар" , fr: "Rapports de mouvements d'inventaire", pt: "Relatórios de movimentos de inventário", it: "Report dei movimenti di magazzino" },
      { sq: "Integrim me faturimin automatik", en: "Integration with automatic invoicing", es: "Integración con facturación automática", de: "Integration mit automatischer Rechnungsstellung", mk: "Интеграција со автоматско фактурирање" , fr: "Intégration avec la facturation automatique", pt: "Integração com faturação automática", it: "Integrazione con la fatturazione automatica" },
    ],
    workflow: [
      { step: "1", sq: "Regjistroni produktet me emër, kodin e barcodit, kategorinë dhe stokun fillestar", en: "Register products with name, barcode, category and initial stock", es: "Registre productos con nombre, código de barras, categoría y stock inicial", de: "Registrieren Sie Produkte mit Name, Barcode, Kategorie und Anfangsbestand", mk: "Регистрирајте производи со име, баркод, категорија и почетни залихи" , fr: "Enregistrez les produits avec nom, code-barres, catégorie et stock initial", pt: "Registe produtos com nome, código de barras, categoria e stock inicial", it: "Registra i prodotti con nome, codice a barre, categoria e stock iniziale" },
      { step: "2", sq: "Skanoni barcodin me telefon për hyrje (pranime) ose dalje (shitje)", en: "Scan barcode with phone for entries (receipts) or exits (sales)", es: "Escanee el código de barras con el teléfono para entradas (recepciones) o salidas (ventas)", de: "Scannen Sie den Barcode mit dem Telefon für Eingänge (Empfang) oder Ausgänge (Verkauf)", mk: "Скенирајте баркод со телефон за влез (прием) или излез (продажба)" , fr: "Scannez le code-barres avec le téléphone pour les entrées (réceptions) ou sorties (ventes)", pt: "Digitalize o código de barras com o telemóvel para entradas (receções) ou saídas (vendas)", it: "Scansiona il codice a barre con il telefono per entrate (ricezioni) o uscite (vendite)" },
      { step: "3", sq: "Sistemi dërgon alarme kur stoku bie nën minimumin e caktuar", en: "System sends alerts when stock falls below the set minimum", es: "El sistema envía alertas cuando el stock cae por debajo del mínimo establecido", de: "System sendet Warnungen, wenn der Bestand unter das festgelegte Minimum fällt", mk: "Системот испраќа аларми кога залихите паѓаат под поставениот минимум" , fr: "Le système envoie des alertes quand le stock descend sous le minimum défini", pt: "O sistema envia alertas quando o stock cai abaixo do mínimo definido", it: "Il sistema invia avvisi quando le scorte scendono sotto il minimo impostato" },
      { step: "4", sq: "Shikoni raportet e lëvizjeve: hyrje, dalje, bilanci dhe trendet", en: "View movement reports: entries, exits, balance and trends", es: "Vea informes de movimientos: entradas, salidas, saldo y tendencias", de: "Sehen Sie Bewegungsberichte: Eingänge, Ausgänge, Saldo und Trends", mk: "Прегледајте извештаи за движење: влезови, излези, салдо и трендови" , fr: "Consultez les rapports de mouvements: entrées, sorties, solde et tendances", pt: "Visualize relatórios de movimentos: entradas, saídas, saldo e tendências", it: "Visualizza i report dei movimenti: entrate, uscite, saldo e tendenze" },
    ],
    capabilities: [
      { icon: "📦", title: { sq: "Katalog Produktesh", en: "Product Catalog", es: "Catálogo de Productos", de: "Produktkatalog", mk: "Каталог на Производи" , fr: "Catalogue de produits", pt: "Catálogo de produtos", it: "Catalogo prodotti" }, desc: { sq: "Listë e organizuar me emra, barcoda, kategori dhe foto", en: "Organized list with names, barcodes, categories and photos", es: "Lista organizada con nombres, códigos de barras, categorías y fotos", de: "Organisierte Liste mit Namen, Barcodes, Kategorien und Fotos", mk: "Организирана листа со имиња, баркодови, категории и фотографии" , fr: "Liste organisée avec noms, codes-barres, catégories et photos", pt: "Lista organizada com nomes, códigos de barras, categorias e fotos", it: "Elenco organizzato con nomi, codici a barre, categorie e foto" } },
      { icon: "📱", title: { sq: "Skaner Barcodi", en: "Barcode Scanner", es: "Escáner de Código de Barras", de: "Barcode-Scanner", mk: "Скенер за Баркод" , fr: "Scanner de codes-barres", pt: "Leitor de códigos de barras", it: "Scanner codici a barre" }, desc: { sq: "Skanoni barcodin me kamerën e telefonit për hyrje/dalje të shpejtë", en: "Scan barcode with phone camera for quick entry/exit", es: "Escanee el código de barras con la cámara del teléfono para entrada/salida rápida", de: "Scannen Sie den Barcode mit der Telefonkamera für schnellen Ein-/Ausgang", mk: "Скенирајте баркод со камерата на телефонот за брз влез/излез" , fr: "Scannez le code-barres avec la caméra du téléphone pour une entrée/sortie rapide", pt: "Digitalize o código de barras com a câmara do telemóvel para entrada/saída rápida", it: "Scansiona il codice a barre con la fotocamera del telefono per entrate/uscite rapide" } },
      { icon: "🔔", title: { sq: "Alarme Stoku", en: "Stock Alerts", es: "Alertas de Stock", de: "Bestandswarnungen", mk: "Аларми за Залихи" , fr: "Alertes de stock", pt: "Alertas de stock", it: "Avvisi di scorte" }, desc: { sq: "Njoftimet vijnë kur produkti po mbaron — porositni përpara", en: "Notifications come when product is running out — order ahead", es: "Las notificaciones llegan cuando el producto se está agotando — ordene con anticipación", de: "Benachrichtigungen kommen, wenn das Produkt zur Neige geht — bestellen Sie im Voraus", mk: "Известувањата доаѓаат кога производот е при крај — нарачајте однапред" , fr: "Les notifications arrivent quand un produit s'épuise — commandez à l'avance", pt: "As notificações chegam quando um produto está a esgotar — encomende com antecedência", it: "Le notifiche arrivano quando un prodotto si sta esaurendo — ordina in anticipo" } },
      { icon: "📊", title: { sq: "Raporte Lëvizjesh", en: "Movement Reports", es: "Informes de Movimientos", de: "Bewegungsberichte", mk: "Извештаи за Движење" , fr: "Rapports de mouvements", pt: "Relatórios de movimentos", it: "Report dei movimenti" }, desc: { sq: "Shikoni hyrjet, daljet dhe bilancin e çdo produkti", en: "View entries, exits and balance of every product", es: "Vea entradas, salidas y saldo de cada producto", de: "Sehen Sie Eingänge, Ausgänge und Saldo jedes Produkts", mk: "Прегледајте влезови, излези и салдо на секој производ" , fr: "Consultez les entrées, sorties et solde de chaque produit", pt: "Visualize entradas, saídas e saldo de cada produto", it: "Visualizza entrate, uscite e saldo di ogni prodotto" } },
      { icon: "🔗", title: { sq: "Integrim Faturash", en: "Invoice Integration", es: "Integración de Facturas", de: "Rechnungsintegration", mk: "Интеграција со Фактури" , fr: "Intégration facturation", pt: "Integração de faturação", it: "Integrazione fatturazione" }, desc: { sq: "Fatura lidhet direkt me stokun — kur shisni, stoku ulet vetë", en: "Invoice links directly with stock — when you sell, stock decreases automatically", es: "La factura se vincula directamente con el stock — cuando vende, el stock disminuye automáticamente", de: "Rechnung verknüpft sich direkt mit dem Bestand — wenn Sie verkaufen, sinkt der Bestand automatisch", mk: "Фактурата се поврзува директно со залихите — кога продавате, залихите се намалуваат автоматски" , fr: "La facture est directement liée au stock — quand vous vendez, le stock diminue automatiquement", pt: "A fatura está diretamente ligada ao stock — quando vende, o stock diminui automaticamente", it: "La fattura è direttamente collegata alle scorte — quando vendi, le scorte diminuiscono automaticamente" } },
      { icon: "📈", title: { sq: "Trende Stoku", en: "Stock Trends", es: "Tendencias de Stock", de: "Bestandstrends", mk: "Трендови на Залихи" , fr: "Tendances de stock", pt: "Tendências de stock", it: "Tendenze delle scorte" }, desc: { sq: "Analizoni cilat produkte lëvizin më shumë dhe planifikoni blerjet", en: "Analyze which products move most and plan purchases", es: "Analice qué productos se mueven más y planifique las compras", de: "Analysieren Sie, welche Produkte sich am meisten bewegen, und planen Sie Einkäufe", mk: "Анализирајте кои производи се движат најмногу и планирајте набавки" , fr: "Analysez quels produits bougent le plus et planifiez les achats", pt: "Analise quais os produtos que mais se movem e planeie as compras", it: "Analizza quali prodotti si muovono di più e pianifica gli acquisti" } },
    ],
  }} />;
}
