import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureAttendance() {
  return <FeatureDetail data={{
    category: { sq: "HR & Ekipi", en: "HR & Team", es: "RRHH & Equipo", de: "HR & Team", mk: "HR & Тим" },
    categoryColor: "bg-emerald-500",
    title: { sq: "Prezencë & Check‑In Mobile", en: "Attendance & Mobile Check‑In", es: "Asistencia & Check-In Móvil", de: "Anwesenheit & Mobiler Check-In", mk: "Присуство & Мобилен Check-In" },
    tagline: { sq: "Pa pajisje në zyrë — vetëm telefon dhe GPS", en: "No office equipment — just phone and GPS", es: "Sin equipos de oficina — solo teléfono y GPS", de: "Keine Bürogeräte — nur Telefon und GPS", mk: "Без канцелариска опрема — само телефон и GPS" },
    stat: { sq: "100% saktësi lokacioni", en: "100% location accuracy", es: "100% precisión de ubicación", de: "100% Standortgenauigkeit", mk: "100% точност на локација" },
    description: {
      sq: "Punonjësit bëjnë check-in dhe check-out direkt nga telefoni me lokacion GPS të saktë — pa karta, pa pajisje të instaluara. Orari i punës, turnet dhe overtime llogariten automatikisht.",
      en: "Employees check in and out directly from their phone with accurate GPS location — no cards, no installed devices. Work hours, shifts and overtime are calculated automatically.",
      es: "Los empleados registran entrada y salida directamente desde su teléfono con ubicación GPS precisa — sin tarjetas, sin dispositivos instalados. Las horas de trabajo, turnos y horas extra se calculan automáticamente.",
      de: "Mitarbeiter checken direkt vom Telefon mit genauem GPS-Standort ein und aus — keine Karten, keine installierten Geräte. Arbeitszeiten, Schichten und Überstunden werden automatisch berechnet.",
      mk: "Вработените се пријавуваат и одјавуваат директно од телефонот со точна GPS локација — без картички, без инсталирани уреди. Работните часови, смените и прекувремената работа се пресметуваат автоматски.",
    },
    benefits: [
      { sq: "Check-in/out nga telefoni me GPS + foto", en: "Check-in/out from phone with GPS + photo", es: "Check-in/out desde el teléfono con GPS + foto", de: "Check-in/out vom Telefon mit GPS + Foto", mk: "Check-in/out од телефон со GPS + фотографија" },
      { sq: "Pa pajisje në zyrë — zero instalim harduer", en: "No office devices — zero hardware installation", es: "Sin dispositivos de oficina — cero instalación de hardware", de: "Keine Bürogeräte — null Hardwareinstallation", mk: "Без канцелариски уреди — нула хардверска инсталација" },
      { sq: "Llogaritje automatike orësh dhe overtime", en: "Automatic calculation of hours and overtime", es: "Cálculo automático de horas y horas extra", de: "Automatische Berechnung von Stunden und Überstunden", mk: "Автоматско пресметување на часови и прекувремена работа" },
      { sq: "Caktim orarit dhe turneve të punës", en: "Work schedule and shift assignment", es: "Asignación de horarios y turnos de trabajo", de: "Arbeitsplan- und Schichtzuweisung", mk: "Распоред на работно време и смени" },
      { sq: "Raporte të avancuara prezence (ditore/mujore)", en: "Advanced attendance reports (daily/monthly)", es: "Informes avanzados de asistencia (diarios/mensuales)", de: "Erweiterte Anwesenheitsberichte (täglich/monatlich)", mk: "Напредни извештаи за присуство (дневни/месечни)" },
      { sq: "Eksport automatik për llogaritje page", en: "Automatic export for payroll calculation", es: "Exportación automática para cálculo de nómina", de: "Automatischer Export für Gehaltsabrechnung", mk: "Автоматски извоз за пресметка на плата" },
    ],
    workflow: [
      { step: "1", sq: "Punonjësi hap aplikacionin dhe shtyp 'Check-In' — GPS dhe foto ruhen", en: "Employee opens the app and taps 'Check-In' — GPS and photo are saved", es: "El empleado abre la app y pulsa 'Check-In' — GPS y foto se guardan", de: "Mitarbeiter öffnet die App und tippt 'Check-In' — GPS und Foto werden gespeichert", mk: "Вработениот ја отвора апликацијата и притиска 'Check-In' — GPS и фотографија се зачувуваат" },
      { step: "2", sq: "Sistemi regjistron orën e fillimit dhe lokacionin automatikisht", en: "System records start time and location automatically", es: "El sistema registra la hora de inicio y la ubicación automáticamente", de: "System erfasst Startzeit und Standort automatisch", mk: "Системот го евидентира времето на почеток и локацијата автоматски" },
      { step: "3", sq: "Në fund të ditës, punonjësi bën 'Check-Out' — orët llogariten", en: "At end of day, employee does 'Check-Out' — hours are calculated", es: "Al final del día, el empleado hace 'Check-Out' — las horas se calculan", de: "Am Ende des Tages macht der Mitarbeiter 'Check-Out' — Stunden werden berechnet", mk: "На крајот на денот, вработениот прави 'Check-Out' — часовите се пресметуваат" },
      { step: "4", sq: "Menaxheri shikon raportin ditor: kush erdhi, kush vonoi, orë totale", en: "Manager views daily report: who came, who was late, total hours", es: "El gerente ve el informe diario: quién vino, quién llegó tarde, horas totales", de: "Manager sieht Tagesbericht: wer kam, wer zu spät war, Gesamtstunden", mk: "Менаџерот го гледа дневниот извештај: кој дошол, кој доцнел, вкупни часови" },
      { step: "5", sq: "Në fund të muajit, eksportoni orët direkt për llogaritjen e pagës", en: "At month end, export hours directly for payroll calculation", es: "Al final del mes, exporte las horas directamente para el cálculo de nómina", de: "Am Monatsende exportieren Sie die Stunden direkt für die Gehaltsabrechnung", mk: "На крајот на месецот, извезете ги часовите директно за пресметка на плата" },
    ],
    capabilities: [
      { icon: "📍", title: { sq: "GPS Check-In", en: "GPS Check-In", es: "Check-In GPS", de: "GPS Check-In", mk: "GPS Check-In" }, desc: { sq: "Lokacion i saktë GPS kur punonjësi bën check-in — pa mundësi mashtrimi", en: "Accurate GPS location when employee checks in — no fraud possible", es: "Ubicación GPS precisa cuando el empleado registra entrada — sin posibilidad de fraude", de: "Genauer GPS-Standort beim Check-in des Mitarbeiters — kein Betrug möglich", mk: "Точна GPS локација кога вработениот се пријавува — без можност за измама" } },
      { icon: "📸", title: { sq: "Foto Verifikimi", en: "Photo Verification", es: "Verificación con Foto", de: "Fotoverifizierung", mk: "Фото Верификација" }, desc: { sq: "Foto selfie automatike gjatë check-in për verifikim identiteti", en: "Automatic selfie photo during check-in for identity verification", es: "Foto selfie automática durante el check-in para verificación de identidad", de: "Automatisches Selfie-Foto beim Check-in zur Identitätsüberprüfung", mk: "Автоматска селфи фотографија при пријавување за верификација на идентитет" } },
      { icon: "⏰", title: { sq: "Llogaritje Orësh", en: "Hours Calculation", es: "Cálculo de Horas", de: "Stundenberechnung", mk: "Пресметка на Часови" }, desc: { sq: "Orë normale, overtime, vonesa — gjithçka llogaritet automatikisht", en: "Normal hours, overtime, lateness — everything calculated automatically", es: "Horas normales, horas extra, retrasos — todo calculado automáticamente", de: "Normalstunden, Überstunden, Verspätungen — alles automatisch berechnet", mk: "Нормални часови, прекувремена работа, доцнење — сè се пресметува автоматски" } },
      { icon: "📋", title: { sq: "Turne Pune", en: "Work Shifts", es: "Turnos de Trabajo", de: "Arbeitsschichten", mk: "Работни Смени" }, desc: { sq: "Caktoni turne: mëngjes, mbasdite, natë — me rotacion automatik", en: "Assign shifts: morning, afternoon, night — with automatic rotation", es: "Asigne turnos: mañana, tarde, noche — con rotación automática", de: "Schichten zuweisen: Morgen, Nachmittag, Nacht — mit automatischer Rotation", mk: "Доделете смени: утро, попладне, ноќ — со автоматска ротација" } },
      { icon: "📊", title: { sq: "Raporte Prezence", en: "Attendance Reports", es: "Informes de Asistencia", de: "Anwesenheitsberichte", mk: "Извештаи за Присуство" }, desc: { sq: "Raporte ditore dhe mujore me grafiqe, vonesa dhe mungesa", en: "Daily and monthly reports with charts, lateness and absences", es: "Informes diarios y mensuales con gráficos, retrasos y ausencias", de: "Tägliche und monatliche Berichte mit Diagrammen, Verspätungen und Abwesenheiten", mk: "Дневни и месечни извештаи со графикони, доцнења и отсуства" } },
      { icon: "💰", title: { sq: "Eksport Payroll", en: "Payroll Export", es: "Exportación de Nómina", de: "Gehaltsexport", mk: "Извоз на Плата" }, desc: { sq: "Eksportoni orët direkt për modulin e pagave — zero hyrje manuale", en: "Export hours directly to payroll module — zero manual entry", es: "Exporte horas directamente al módulo de nómina — cero entrada manual", de: "Stunden direkt in das Gehaltsmodul exportieren — null manuelle Eingabe", mk: "Извезете часови директно во модулот за плати — нула рачно внесување" } },
    ],
  }} />;
}
