import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureClients() {
  return <FeatureDetail data={{
    category: { sq: "Klientë", en: "Clients", es: "Clientes", de: "Kunden", mk: "Клиенти", fr: "Clients", pt: "Clientes", it: "Clienti" },
    categoryColor: "bg-indigo-500",
    title: { sq: "Menaxhim Klientësh (CRM)", en: "Client Management (CRM)", es: "Gestión de Clientes (CRM)", de: "Kundenverwaltung (CRM)", mk: "Управување со Клиенти (CRM)" , fr: "Gestion clients (CRM)", pt: "Gestão de clientes (CRM)", it: "Gestione clienti (CRM)" },
    tagline: { sq: "Ndërtoni marrëdhënie të forta me çdo klient", en: "Build strong relationships with every client", es: "Construya relaciones sólidas con cada cliente", de: "Bauen Sie starke Beziehungen zu jedem Kunden auf", mk: "Изградете силни односи со секој клиент" , fr: "Construisez de solides relations avec chaque client", pt: "Construa relações sólidas com cada cliente", it: "Costruisci relazioni solide con ogni cliente" },
    stat: { sq: "+30% mbajtje klientësh", en: "+30% client retention", es: "+30% retención de clientes", de: "+30% Kundenbindung", mk: "+30% задржување на клиенти" , fr: "+30% de fidélisation des clients", pt: "+30% de retenção de clientes", it: "+30% di fidelizzazione dei clienti" },
    description: {
      sq: "Mbani historikun e plotë të çdo klienti — porositë, pagesat, ofertat, korespondencën dhe shënimet. Asnjë detaj nuk humb. CRM i plotë që ju ndihmon të ndërtoni marrëdhënie afatgjata.",
      en: "Keep the complete history of every client — orders, payments, offers, correspondence and notes. No detail is lost. A full CRM that helps you build long-term relationships.",
      es: "Mantenga el historial completo de cada cliente — pedidos, pagos, ofertas, correspondencia y notas. Ningún detalle se pierde. Un CRM completo que le ayuda a construir relaciones a largo plazo.",
      de: "Behalten Sie die vollständige Historie jedes Kunden — Bestellungen, Zahlungen, Angebote, Korrespondenz und Notizen. Kein Detail geht verloren. Ein vollständiges CRM, das Ihnen hilft, langfristige Beziehungen aufzubauen.",
      mk: "Чувајте ја целосната историја на секој клиент — нарачки, плаќања, понуди, кореспонденција и белешки. Ниеден детал не се губи. Целосен CRM што ви помага да градите долгорочни односи.",
    fr: "Conservez l'historique complet de chaque client — commandes, paiements, offres, correspondance et notes. Aucun détail n'est perdu. Un CRM complet pour construire des relations durables.", pt: "Mantenha o histórico completo de cada cliente — encomendas, pagamentos, ofertas, correspondência e notas. Nenhum detalhe se perde. Um CRM completo para construir relações duradouras.", it: "Conserva la cronologia completa di ogni cliente — ordini, pagamenti, offerte, corrispondenza e note. Nessun dettaglio viene perso. Un CRM completo per costruire relazioni durature." },
    benefits: [
      { sq: "Profil i plotë 360° i çdo klienti", en: "Complete 360° profile of every client", es: "Perfil completo 360° de cada cliente", de: "Vollständiges 360°-Profil jedes Kunden", mk: "Целосен 360° профил на секој клиент" , fr: "Profil complet à 360° de chaque client", pt: "Perfil completo 360° de cada cliente", it: "Profilo completo 360° di ogni cliente" },
      { sq: "Historiku i porosive, ofertave dhe pagesave", en: "History of orders, offers and payments", es: "Historial de pedidos, ofertas y pagos", de: "Historie von Bestellungen, Angeboten und Zahlungen", mk: "Историја на нарачки, понуди и плаќања" , fr: "Historique des commandes, offres et paiements", pt: "Histórico de encomendas, ofertas e pagamentos", it: "Cronologia ordini, offerte e pagamenti" },
      { sq: "Rikujtime automatike follow-up", en: "Automatic follow-up reminders", es: "Recordatorios automáticos de seguimiento", de: "Automatische Follow-up-Erinnerungen", mk: "Автоматски потсетници за следење" , fr: "Rappels de suivi automatiques", pt: "Lembretes de acompanhamento automáticos", it: "Promemoria follow-up automatici" },
      { sq: "Segmentim klientësh sipas vlerës", en: "Client segmentation by value", es: "Segmentación de clientes por valor", de: "Kundensegmentierung nach Wert", mk: "Сегментација на клиенти по вредност" , fr: "Segmentation des clients par valeur", pt: "Segmentação de clientes por valor", it: "Segmentazione dei clienti per valore" },
      { sq: "Lidhje direkte me kalendarin e takimeve", en: "Direct link with meeting calendar", es: "Enlace directo con el calendario de reuniones", de: "Direkte Verbindung mit dem Terminkalender", mk: "Директна врска со календарот за состаноци" , fr: "Lien direct avec le calendrier de réunions", pt: "Ligação direta com o calendário de reuniões", it: "Collegamento diretto con il calendario riunioni" },
    ],
    workflow: [
      { step: "1", sq: "Shtoni klientin e ri me të dhënat e kontaktit dhe llojin e biznesit", en: "Add the new client with contact details and business type", es: "Agregue el nuevo cliente con datos de contacto y tipo de negocio", de: "Fügen Sie den neuen Kunden mit Kontaktdaten und Geschäftstyp hinzu", mk: "Додајте нов клиент со контакт информации и тип на бизнис" , fr: "Ajoutez le nouveau client avec coordonnées et type d'entreprise", pt: "Adicione o novo cliente com detalhes de contacto e tipo de negócio", it: "Aggiungi il nuovo cliente con i dettagli di contatto e il tipo di attività" },
      { step: "2", sq: "Çdo ofertë, faturë dhe pagesë regjistrohet automatikisht te profili i klientit", en: "Every quote, invoice and payment is auto-recorded on the client profile", es: "Cada cotización, factura y pago se registra automáticamente en el perfil del cliente", de: "Jedes Angebot, jede Rechnung und Zahlung wird automatisch im Kundenprofil erfasst", mk: "Секоја понуда, фактура и плаќање автоматски се евидентира на профилот на клиентот" , fr: "Chaque devis, facture et paiement est automatiquement enregistré sur le profil client", pt: "Cada orçamento, fatura e pagamento é automaticamente registado no perfil do cliente", it: "Ogni preventivo, fattura e pagamento viene automaticamente registrato nel profilo del cliente" },
      { step: "3", sq: "Caktoni rikujtime follow-up dhe takime drejtpërdrejt nga profili", en: "Set follow-up reminders and meetings directly from the profile", es: "Establezca recordatorios de seguimiento y reuniones directamente desde el perfil", de: "Setzen Sie Follow-up-Erinnerungen und Meetings direkt vom Profil aus", mk: "Поставете потсетници за следење и состаноци директно од профилот" , fr: "Définissez des rappels de suivi et réunions directement depuis le profil", pt: "Defina lembretes de acompanhamento e reuniões diretamente do perfil", it: "Imposta promemoria di follow-up e riunioni direttamente dal profilo" },
      { step: "4", sq: "Segmentoni klientët sipas vlerës, aktivitetit dhe potencialit të rritjes", en: "Segment clients by value, activity and growth potential", es: "Segmente clientes por valor, actividad y potencial de crecimiento", de: "Segmentieren Sie Kunden nach Wert, Aktivität und Wachstumspotenzial", mk: "Сегментирајте клиенти по вредност, активност и потенцијал за раст" , fr: "Segmentez les clients par valeur, activité et potentiel de croissance", pt: "Segmente os clientes por valor, atividade e potencial de crescimento", it: "Segmenta i clienti per valore, attività e potenziale di crescita" },
    ],
    capabilities: [
      { icon: "👤", title: { sq: "Profil 360°", en: "360° Profile", es: "Perfil 360°", de: "360°-Profil", mk: "360° Профил" , fr: "Profil à 360°", pt: "Perfil a 360°", it: "Profilo 360°" }, desc: { sq: "Të gjitha të dhënat e klientit në një faqe: kontakte, porosi, pagesa, shënime", en: "All client data on one page: contacts, orders, payments, notes", es: "Todos los datos del cliente en una página: contactos, pedidos, pagos, notas", de: "Alle Kundendaten auf einer Seite: Kontakte, Bestellungen, Zahlungen, Notizen", mk: "Сите податоци за клиентот на една страница: контакти, нарачки, плаќања, белешки" , fr: "Toutes les données client sur une page: contacts, commandes, paiements, notes", pt: "Todos os dados do cliente numa página: contactos, encomendas, pagamentos, notas", it: "Tutti i dati del cliente in una pagina: contatti, ordini, pagamenti, note" } },
      { icon: "📜", title: { sq: "Historik i Plotë", en: "Full History", es: "Historial Completo", de: "Vollständige Historie", mk: "Целосна Историја" , fr: "Historique complet", pt: "Histórico completo", it: "Cronologia completa" }, desc: { sq: "Çdo ndërveprim, ofertë dhe faturë ruhet dhe aksesohet lehtësisht", en: "Every interaction, quote and invoice stored and easily accessed", es: "Cada interacción, cotización y factura almacenada y fácilmente accesible", de: "Jede Interaktion, jedes Angebot und jede Rechnung gespeichert und leicht zugänglich", mk: "Секоја интеракција, понуда и фактура зачувана и лесно достапна" , fr: "Chaque interaction, devis et facture stockés et facilement accessibles", pt: "Cada interação, orçamento e fatura armazenados e facilmente acessíveis", it: "Ogni interazione, preventivo e fattura archiviati e facilmente accessibili" } },
      { icon: "🔔", title: { sq: "Follow-up Automatik", en: "Auto Follow-up", es: "Seguimiento Automático", de: "Automatisches Follow-up", mk: "Автоматско Следење" , fr: "Suivi automatique", pt: "Acompanhamento automático", it: "Follow-up automatico" }, desc: { sq: "Rikujtime inteligjente për të ndjekur klientët në kohën e duhur", en: "Smart reminders to follow up with clients at the right time", es: "Recordatorios inteligentes para dar seguimiento a clientes en el momento adecuado", de: "Intelligente Erinnerungen, um Kunden zum richtigen Zeitpunkt nachzuverfolgen", mk: "Паметни потсетници за следење на клиенти во вистинско време" , fr: "Rappels intelligents pour suivre les clients au bon moment", pt: "Lembretes inteligentes para acompanhar os clientes no momento certo", it: "Promemoria intelligenti per seguire i clienti al momento giusto" } },
      { icon: "📊", title: { sq: "Segmentim", en: "Segmentation", es: "Segmentación", de: "Segmentierung", mk: "Сегментација" , fr: "Segmentation", pt: "Segmentação", it: "Segmentazione" }, desc: { sq: "Gruponi klientët sipas vlerës, frekuencës ose potencialit", en: "Group clients by value, frequency or potential", es: "Agrupe clientes por valor, frecuencia o potencial", de: "Gruppieren Sie Kunden nach Wert, Häufigkeit oder Potenzial", mk: "Групирајте клиенти по вредност, фреквенција или потенцијал" , fr: "Regroupez les clients par valeur, fréquence ou potentiel", pt: "Agrupe os clientes por valor, frequência ou potencial", it: "Raggruppa i clienti per valore, frequenza o potenziale" } },
      { icon: "📅", title: { sq: "Kalendar i Integruar", en: "Integrated Calendar", es: "Calendario Integrado", de: "Integrierter Kalender", mk: "Интегриран Календар" , fr: "Calendrier intégré", pt: "Calendário integrado", it: "Calendario integrato" }, desc: { sq: "Caktoni takime direkt nga profili i klientit", en: "Schedule meetings directly from the client profile", es: "Programe reuniones directamente desde el perfil del cliente", de: "Planen Sie Meetings direkt vom Kundenprofil aus", mk: "Закажете состаноци директно од профилот на клиентот" , fr: "Planifiez des réunions directement depuis le profil client", pt: "Agende reuniões diretamente a partir do perfil do cliente", it: "Pianifica riunioni direttamente dal profilo del cliente" } },
      { icon: "📈", title: { sq: "Analitikë Klienti", en: "Client Analytics", es: "Analítica de Clientes", de: "Kundenanalytik", mk: "Аналитика на Клиенти" , fr: "Analyse client", pt: "Análise de clientes", it: "Analisi dei clienti" }, desc: { sq: "Raporte për klientët më profitabilë, trendet dhe mundësitë", en: "Reports on most profitable clients, trends and opportunities", es: "Informes sobre clientes más rentables, tendencias y oportunidades", de: "Berichte über die profitabelsten Kunden, Trends und Chancen", mk: "Извештаи за најпрофитабилни клиенти, трендови и можности" , fr: "Rapports sur les clients les plus rentables, tendances et opportunités", pt: "Relatórios sobre os clientes mais rentáveis, tendências e oportunidades", it: "Report sui clienti più redditizi, tendenze e opportunità" } },
    ],
  }} />;
}
