import FeatureDetail from "@/components/FeatureDetail";

export default function FeaturePayroll() {
  return <FeatureDetail data={{
    category: { sq: "HR & Ekipi", en: "HR & Team", es: "RRHH & Equipo", de: "HR & Team", mk: "HR & Тим" },
    categoryColor: "bg-blue-500",
    title: { sq: "Paga & Kompensimi", en: "Payroll & Compensation", es: "Nómina & Compensación", de: "Gehaltsabrechnung & Vergütung", mk: "Плата & Компензација" },
    tagline: { sq: "Çdo mënyrë pagese — e automatizuar plotësisht", en: "Every payment method — fully automated", es: "Cada método de pago — totalmente automatizado", de: "Jede Zahlungsmethode — vollständig automatisiert", mk: "Секој метод на плаќање — целосно автоматизиран" },
    stat: { sq: "100% saktësi llogaritje page", en: "100% payroll accuracy", es: "100% precisión de nómina", de: "100% Gehaltsabrechnungsgenauigkeit", mk: "100% точност на плата" },
    description: {
      sq: "Konfiguroni pagën për çdo punonjës sipas mënyrës që i përshtatet rolit të tij — pagë fikse, komision, kombinim, ose bonus performancë. Llogaritja bëhet automatikisht bazuar në orët e prezencës.",
      en: "Configure pay for each employee according to their role — fixed salary, commission, combination, or performance bonus. The calculation is done automatically based on attendance hours.",
      es: "Configure el pago para cada empleado según su rol — salario fijo, comisión, combinación o bonificación por rendimiento. El cálculo se realiza automáticamente basado en las horas de asistencia.",
      de: "Konfigurieren Sie die Vergütung für jeden Mitarbeiter entsprechend seiner Rolle — Festgehalt, Provision, Kombination oder Leistungsbonus. Die Berechnung erfolgt automatisch basierend auf den Anwesenheitsstunden.",
      mk: "Конфигурирајте ја платата за секој вработен според неговата улога — фиксна плата, провизија, комбинација или бонус за перформанси. Пресметката се врши автоматски врз основа на часовите на присуство.",
    },
    benefits: [
      { sq: "Pagë fikse mujore ose javore", en: "Fixed monthly or weekly salary", es: "Salario fijo mensual o semanal", de: "Festes Monats- oder Wochengehalt", mk: "Фиксна месечна или неделна плата" },
      { sq: "Komision me përqindje të shitjeve", en: "Commission with sales percentage", es: "Comisión con porcentaje de ventas", de: "Provision mit Verkaufsprozentsatz", mk: "Провизија со процент од продажба" },
      { sq: "Pagë fikse + përqindje (hibride)", en: "Fixed salary + percentage (hybrid)", es: "Salario fijo + porcentaje (híbrido)", de: "Festgehalt + Prozentsatz (hybrid)", mk: "Фиксна плата + процент (хибридна)" },
      { sq: "Bonus performancë dhe stimuj të personalizuar", en: "Performance bonuses and personalised incentives", es: "Bonificaciones por rendimiento e incentivos personalizados", de: "Leistungsboni und personalisierte Anreize", mk: "Бонуси за перформанси и персонализирани стимулации" },
      { sq: "Llogaritje automatike bazuar në orë prezence", en: "Automatic calculation based on attendance hours", es: "Cálculo automático basado en horas de asistencia", de: "Automatische Berechnung basierend auf Anwesenheitsstunden", mk: "Автоматска пресметка базирана на часови на присуство" },
      { sq: "Raporte pagash dhe eksport payroll", en: "Payroll reports and payroll export", es: "Informes de nómina y exportación de nómina", de: "Gehaltsberichte und Gehaltsexport", mk: "Извештаи за плати и извоз на платен список" },
    ],
    workflow: [
      { step: "1", sq: "Konfiguroni llojin e pagës: fikse, komision, hibride ose bonus", en: "Configure the pay type: fixed, commission, hybrid or bonus", es: "Configure el tipo de pago: fijo, comisión, híbrido o bonificación", de: "Vergütungstyp konfigurieren: fest, Provision, hybrid oder Bonus", mk: "Конфигурирајте го типот на плата: фиксна, провизија, хибридна или бонус" },
      { step: "2", sq: "Sistemi lexon orët e prezencës automatikisht nga moduli i prezencës", en: "System reads attendance hours automatically from the attendance module", es: "El sistema lee las horas de asistencia automáticamente del módulo de asistencia", de: "System liest Anwesenheitsstunden automatisch aus dem Anwesenheitsmodul", mk: "Системот ги чита часовите на присуство автоматски од модулот за присуство" },
      { step: "3", sq: "Llogaritja e pagës bëhet automatikisht: bazë + orë shtesë + bonus", en: "Payroll calculation done automatically: base + overtime + bonus", es: "Cálculo de nómina realizado automáticamente: base + horas extra + bonificación", de: "Gehaltsberechnung automatisch: Basis + Überstunden + Bonus", mk: "Пресметката на платата се врши автоматски: основа + прекувремена работа + бонус" },
      { step: "4", sq: "Aprovoni pagat dhe eksportoni raportin për bankën ose kontabilistin", en: "Approve payroll and export the report for bank or accountant", es: "Apruebe la nómina y exporte el informe para el banco o contador", de: "Gehaltsabrechnung genehmigen und Bericht für Bank oder Buchhalter exportieren", mk: "Одобрете ги платите и извезете го извештајот за банката или сметководителот" },
    ],
    capabilities: [
      { icon: "💵", title: { sq: "Pagë Fikse", en: "Fixed Salary", es: "Salario Fijo", de: "Festgehalt", mk: "Фиксна Плата" }, desc: { sq: "Pagë standarde mujore ose javore e konfiguruar për çdo punonjës", en: "Standard monthly or weekly salary configured for each employee", es: "Salario estándar mensual o semanal configurado para cada empleado", de: "Standard-Monats- oder Wochengehalt für jeden Mitarbeiter konfiguriert", mk: "Стандардна месечна или неделна плата конфигурирана за секој вработен" } },
      { icon: "📈", title: { sq: "Komision Shitjesh", en: "Sales Commission", es: "Comisión de Ventas", de: "Verkaufsprovision", mk: "Провизија од Продажба" }, desc: { sq: "Përqindje automatike bazuar në shitjet e çdo punonjësi", en: "Automatic percentage based on each employee's sales", es: "Porcentaje automático basado en las ventas de cada empleado", de: "Automatischer Prozentsatz basierend auf den Verkäufen jedes Mitarbeiters", mk: "Автоматски процент базиран на продажбите на секој вработен" } },
      { icon: "🔀", title: { sq: "Pagë Hibride", en: "Hybrid Pay", es: "Pago Híbrido", de: "Hybridgehalt", mk: "Хибридна Плата" }, desc: { sq: "Kombinoni pagë fikse me përqindje shitjesh për fleksibilitet", en: "Combine fixed salary with sales percentage for flexibility", es: "Combine salario fijo con porcentaje de ventas para flexibilidad", de: "Festgehalt mit Verkaufsprozentsatz für Flexibilität kombinieren", mk: "Комбинирајте фиксна плата со процент од продажба за флексибилност" } },
      { icon: "🏆", title: { sq: "Bonus Performancë", en: "Performance Bonus", es: "Bonificación por Rendimiento", de: "Leistungsbonus", mk: "Бонус за Перформанси" }, desc: { sq: "Stimuj bazuar në objektivat dhe performancën e ekipit", en: "Incentives based on objectives and team performance", es: "Incentivos basados en objetivos y rendimiento del equipo", de: "Anreize basierend auf Zielen und Teamleistung", mk: "Стимулации базирани на цели и перформанси на тимот" } },
      { icon: "⏱️", title: { sq: "Orë Shtesë", en: "Overtime", es: "Horas Extra", de: "Überstunden", mk: "Прекувремена Работа" }, desc: { sq: "Llogaritje automatike e orëve shtesë me tarifa të konfiguruara", en: "Automatic overtime calculation with configured rates", es: "Cálculo automático de horas extra con tarifas configuradas", de: "Automatische Überstundenberechnung mit konfigurierten Sätzen", mk: "Автоматска пресметка на прекувремена работа со конфигурирани тарифи" } },
      { icon: "📊", title: { sq: "Raporte Pagash", en: "Payroll Reports", es: "Informes de Nómina", de: "Gehaltsberichte", mk: "Извештаи за Плати" }, desc: { sq: "Eksportoni raporte detale për bankë, kontabilist ose menaxher", en: "Export detailed reports for bank, accountant or manager", es: "Exporte informes detallados para banco, contador o gerente", de: "Detaillierte Berichte für Bank, Buchhalter oder Manager exportieren", mk: "Извезете детални извештаи за банка, сметководител или менаџер" } },
    ],
  }} />;
}
