import FeatureDetail from "@/components/FeatureDetail";

const data = {
  category: { sq: "Financë", en: "Finance", es: "Finanzas", de: "Finanzen", mk: "Финансии", fr: "Finance", pt: "Finanças", it: "Finanza" },
  categoryColor: "bg-amber-500",
  title: { sq: "Kartelat e Blerësit", en: "Buyer Cards", es: "Tarjetas de Comprador", de: "Käuferkarten", mk: "Картички на Купувач" , fr: "Cartes d'acheteurs", pt: "Cartões de compradores", it: "Carte acquirenti" },
  tagline: { sq: "Menaxhoni kartelat dhe historikun e blerësve", en: "Manage buyer cards and purchase history", es: "Gestione tarjetas de compradores e historial de compras", de: "Käuferkarten und Kaufhistorie verwalten", mk: "Управувајте со картичките и историјата на купувачите" , fr: "Gérez les cartes d'acheteurs et l'historique des achats", pt: "Gira cartões de compradores e histórico de compras", it: "Gestisci le carte degli acquirenti e la cronologia degli acquisti" },
  stat: { sq: "100% transparencë blerësi", en: "100% buyer transparency", es: "100% transparencia del comprador", de: "100% Käufertransparenz", mk: "100% транспарентност на купувач" , fr: "100% de transparence des acheteurs", pt: "100% de transparência dos compradores", it: "100% di trasparenza degli acquirenti" },
  description: {
    sq: "Krijoni kartela dixhitale për çdo blerës me historikun e plotë të blerjeve, pagesave dhe borxheve. Çdo blerës ka profilin e vet me saldo aktuale, limitet e kreditit dhe statistikat e blerjeve. Ju gjithmonë e dini saktësisht ku qëndroni me çdo klient.",
    en: "Create digital cards for each buyer with complete purchase, payment and debt history. Each buyer has their own profile with current balance, credit limits and purchase statistics. You always know exactly where you stand with each client.",
    es: "Cree tarjetas digitales para cada comprador con historial completo de compras, pagos y deudas. Cada comprador tiene su propio perfil con saldo actual, límites de crédito y estadísticas de compras. Usted siempre sabe exactamente dónde se encuentra con cada cliente.",
    de: "Erstellen Sie digitale Karten für jeden Käufer mit vollständiger Kauf-, Zahlungs- und Schuldenhistorie. Jeder Käufer hat sein eigenes Profil mit aktuellem Saldo, Kreditlimits und Kaufstatistiken. Sie wissen immer genau, wo Sie mit jedem Kunden stehen.",
    mk: "Креирајте дигитални картички за секој купувач со целосна историја на купувања, плаќања и долгови. Секој купувач има свој профил со тековно салдо, кредитни лимити и статистики на купувања. Секогаш точно знаете каде стоите со секој клиент.",
  , fr: "Créez des cartes numériques pour chaque acheteur avec l'historique complet des achats, paiements et dettes. Chaque acheteur a son propre profil avec solde actuel, limites de crédit et statistiques d'achats. Vous savez toujours exactement où vous en êtes avec chaque client.", pt: "Crie cartões digitais para cada comprador com histórico completo de compras, pagamentos e dívidas. Cada comprador tem o seu próprio perfil com saldo atual, limites de crédito e estatísticas de compras. Sabe sempre exatamente onde está com cada cliente.", it: "Crea carte digitali per ogni acquirente con cronologia completa di acquisti, pagamenti e debiti. Ogni acquirente ha il proprio profilo con saldo attuale, limiti di credito e statistiche di acquisto. Sai sempre esattamente a che punto sei con ogni cliente." },
  benefits: [
    { sq: "Kartela dixhitale me saldo dhe historik blerje", en: "Digital cards with balance and purchase history", es: "Tarjetas digitales con saldo e historial de compras", de: "Digitale Karten mit Saldo und Kaufhistorie", mk: "Дигитални картички со салдо и историја на купувања" , fr: "Cartes numériques avec solde et historique d'achats", pt: "Cartões digitais com saldo e histórico de compras", it: "Carte digitali con saldo e cronologia degli acquisti" },
    { sq: "Limit krediti dhe njoftim automatik", en: "Credit limit and automatic notification", es: "Límite de crédito y notificación automática", de: "Kreditlimit und automatische Benachrichtigung", mk: "Кредитен лимит и автоматско известување" , fr: "Limite de crédit et notification automatique", pt: "Limite de crédito e notificação automática", it: "Limite di credito e notifica automatica" },
    { sq: "Gjurmim i pagesave dhe borxheve të blerësit", en: "Tracking buyer payments and debts", es: "Seguimiento de pagos y deudas del comprador", de: "Verfolgung von Käuferzahlungen und Schulden", mk: "Следење на плаќања и долгови на купувачот" , fr: "Suivi des paiements et dettes des acheteurs", pt: "Rastreamento de pagamentos e dívidas de compradores", it: "Monitoraggio dei pagamenti e debiti degli acquirenti" },
    { sq: "Raport detajuar i çdo blerësi", en: "Detailed report for each buyer", es: "Informe detallado de cada comprador", de: "Detaillierter Bericht für jeden Käufer", mk: "Детален извештај за секој купувач" , fr: "Rapport détaillé pour chaque acheteur", pt: "Relatório detalhado para cada comprador", it: "Report dettagliato per ogni acquirente" },
    { sq: "Kategorizim sipas llojit të blerësit", en: "Categorization by buyer type", es: "Categorización por tipo de comprador", de: "Kategorisierung nach Käufertyp", mk: "Категоризација според тип на купувач" , fr: "Catégorisation par type d'acheteur", pt: "Categorização por tipo de comprador", it: "Categorizzazione per tipo di acquirente" },
    { sq: "Eksport i listës së blerësve (PDF/Excel)", en: "Export buyer list (PDF/Excel)", es: "Exportar lista de compradores (PDF/Excel)", de: "Käuferliste exportieren (PDF/Excel)", mk: "Извоз на листа на купувачи (PDF/Excel)" , fr: "Exportez la liste des acheteurs (PDF/Excel)", pt: "Exporte lista de compradores (PDF/Excel)", it: "Esporta elenco acquirenti (PDF/Excel)" },
  ],
  workflow: [
    { step: "1", sq: "Shtoni blerësin e ri me të dhënat bazë: emër, kontakt, lloj biznesi", en: "Add the new buyer with basic data: name, contact, business type", es: "Agregue al nuevo comprador con datos básicos: nombre, contacto, tipo de negocio", de: "Neuen Käufer mit Basisdaten hinzufügen: Name, Kontakt, Geschäftstyp", mk: "Додајте го новиот купувач со основни податоци: име, контакт, тип на бизнис" , fr: "Ajoutez le nouvel acheteur avec les données de base: nom, contact, type d'entreprise", pt: "Adicione o novo comprador com dados básicos: nome, contacto, tipo de negócio", it: "Aggiungi il nuovo acquirente con dati di base: nome, contatto, tipo di attività" },
    { step: "2", sq: "Caktoni limitin e kreditit dhe kushtet e pagesës për blerësin", en: "Set the credit limit and payment terms for the buyer", es: "Establezca el límite de crédito y los términos de pago para el comprador", de: "Kreditlimit und Zahlungsbedingungen für den Käufer festlegen", mk: "Поставете го кредитниот лимит и условите за плаќање за купувачот" , fr: "Définissez la limite de crédit et les conditions de paiement pour l'acheteur", pt: "Defina o limite de crédito e os termos de pagamento para o comprador", it: "Imposta il limite di credito e le condizioni di pagamento per l'acquirente" },
    { step: "3", sq: "Çdo blerje dhe pagesë regjistrohet automatikisht në kartelën e blerësit", en: "Every purchase and payment is automatically recorded on the buyer's card", es: "Cada compra y pago se registra automáticamente en la tarjeta del comprador", de: "Jeder Kauf und jede Zahlung wird automatisch auf der Käuferkarte erfasst", mk: "Секое купување и плаќање автоматски се евидентира на картичката на купувачот" , fr: "Chaque achat et paiement est automatiquement enregistré sur la carte de l'acheteur", pt: "Cada compra e pagamento é automaticamente registado no cartão do comprador", it: "Ogni acquisto e pagamento viene automaticamente registrato sulla carta dell'acquirente" },
    { step: "4", sq: "Merrni alarme kur blerësi i afrohet limitit ose ka borxh të vonuar", en: "Get alerts when the buyer approaches the limit or has overdue debt", es: "Reciba alertas cuando el comprador se acerque al límite o tenga deuda vencida", de: "Erhalten Sie Alarme, wenn der Käufer sich dem Limit nähert oder überfällige Schulden hat", mk: "Добијте аларми кога купувачот се приближува до лимитот или има достасан долг" , fr: "Recevez des alertes quand l'acheteur approche de la limite ou a des dettes en retard", pt: "Receba alertas quando o comprador se aproxima do limite ou tem dívidas em atraso", it: "Ricevi avvisi quando l'acquirente si avvicina al limite o ha debiti scaduti" },
    { step: "5", sq: "Gjeneroni raporte për blerësit — saldo, historik blerje, profitabilitet", en: "Generate reports for buyers — balance, purchase history, profitability", es: "Genere informes para compradores — saldo, historial de compras, rentabilidad", de: "Berichte für Käufer generieren — Saldo, Kaufhistorie, Rentabilität", mk: "Генерирајте извештаи за купувачите — салдо, историја на купувања, профитабилност" , fr: "Générez des rapports pour les acheteurs — solde, historique des achats, rentabilité", pt: "Gere relatórios para compradores — saldo, histórico de compras, rentabilidade", it: "Genera report per gli acquirenti — saldo, cronologia acquisti, redditività" },
  ],
  capabilities: [
    { icon: "💳", title: { sq: "Kartela Dixhitale", en: "Digital Cards", es: "Tarjetas Digitales", de: "Digitale Karten", mk: "Дигитални Картички" , fr: "Cartes numériques", pt: "Cartões digitais", it: "Carte digitali" }, desc: { sq: "Profil i plotë për çdo blerës me të gjitha të dhënat financiare në një vend", en: "Complete profile for each buyer with all financial data in one place", es: "Perfil completo para cada comprador con todos los datos financieros en un solo lugar", de: "Vollständiges Profil für jeden Käufer mit allen Finanzdaten an einem Ort", mk: "Целосен профил за секој купувач со сите финансиски податоци на едно место" , fr: "Profil complet pour chaque acheteur avec toutes les données financières en un seul endroit", pt: "Perfil completo para cada comprador com todos os dados financeiros num só lugar", it: "Profilo completo per ogni acquirente con tutti i dati finanziari in un unico posto" } },
    { icon: "📈", title: { sq: "Saldo në Kohë Reale", en: "Real-time Balance", es: "Saldo en Tiempo Real", de: "Echtzeit-Saldo", mk: "Салдо во Реално Време" , fr: "Solde en temps réel", pt: "Saldo em tempo real", it: "Saldo in tempo reale" }, desc: { sq: "Shikoni saldot aktuale, pagesat e pritshme dhe borxhet e çdo blerësi", en: "View current balances, expected payments and debts for each buyer", es: "Vea saldos actuales, pagos esperados y deudas de cada comprador", de: "Aktuelle Salden, erwartete Zahlungen und Schulden für jeden Käufer einsehen", mk: "Погледнете тековни салда, очекувани плаќања и долгови за секој купувач" , fr: "Consultez les soldes actuels, paiements attendus et dettes pour chaque acheteur", pt: "Visualize os saldos atuais, pagamentos esperados e dívidas de cada comprador", it: "Visualizza i saldi attuali, i pagamenti attesi e i debiti per ogni acquirente" } },
    { icon: "⚠️", title: { sq: "Alarme Krediti", en: "Credit Alerts", es: "Alertas de Crédito", de: "Kreditalarme", mk: "Кредитни Аларми" , fr: "Alertes de crédit", pt: "Alertas de crédito", it: "Avvisi di credito" }, desc: { sq: "Njoftim automatik kur blerësi i afrohet ose e kalon limitin e kreditit", en: "Auto notification when buyer approaches or exceeds credit limit", es: "Notificación automática cuando el comprador se acerca o excede el límite de crédito", de: "Automatische Benachrichtigung, wenn der Käufer sich dem Kreditlimit nähert oder es überschreitet", mk: "Автоматско известување кога купувачот се приближува или го надминува кредитниот лимит" , fr: "Notification automatique quand l'acheteur approche ou dépasse la limite de crédit", pt: "Notificação automática quando o comprador se aproxima ou excede o limite de crédito", it: "Notifica automatica quando l'acquirente si avvicina o supera il limite di credito" } },
    { icon: "📋", title: { sq: "Historik i Plotë", en: "Complete History", es: "Historial Completo", de: "Vollständige Historie", mk: "Целосна Историја" , fr: "Historique complet", pt: "Histórico completo", it: "Cronologia completa" }, desc: { sq: "Çdo blerje, pagesë dhe kthim i regjistruar me data dhe detaje", en: "Every purchase, payment and return recorded with dates and details", es: "Cada compra, pago y devolución registrada con fechas y detalles", de: "Jeder Kauf, jede Zahlung und Rückgabe mit Daten und Details erfasst", mk: "Секое купување, плаќање и враќање евидентирано со датуми и детали" , fr: "Chaque achat, paiement et retour enregistré avec dates et détails", pt: "Cada compra, pagamento e devolução registados com datas e detalhes", it: "Ogni acquisto, pagamento e reso registrato con date e dettagli" } },
    { icon: "🏷️", title: { sq: "Kategorizim", en: "Categorization", es: "Categorización", de: "Kategorisierung", mk: "Категоризација" , fr: "Catégorisation", pt: "Categorização", it: "Categorizzazione" }, desc: { sq: "Gruponi blerësit sipas llojit, rajonit ose volumit të blerjeve", en: "Group buyers by type, region or purchase volume", es: "Agrupe compradores por tipo, región o volumen de compras", de: "Käufer nach Typ, Region oder Kaufvolumen gruppieren", mk: "Групирајте купувачи според тип, регион или обем на купувања" , fr: "Regroupez les acheteurs par type, région ou volume d'achats", pt: "Agrupe compradores por tipo, região ou volume de compras", it: "Raggruppa gli acquirenti per tipo, regione o volume di acquisti" } },
    { icon: "📊", title: { sq: "Raporte Blerësi", en: "Buyer Reports", es: "Informes de Comprador", de: "Käuferberichte", mk: "Извештаи за Купувачи" , fr: "Rapports acheteurs", pt: "Relatórios de compradores", it: "Report acquirenti" }, desc: { sq: "Analiza detajuara: blerësi më profitabil, borxhet, trendet e blerjeve", en: "Detailed analysis: most profitable buyer, debts, purchase trends", es: "Análisis detallado: comprador más rentable, deudas, tendencias de compra", de: "Detaillierte Analyse: profitabelster Käufer, Schulden, Kauftrends", mk: "Детална анализа: најпрофитабилен купувач, долгови, трендови на купување" , fr: "Analyse détaillée: acheteur le plus rentable, dettes, tendances d'achats", pt: "Análise detalhada: comprador mais rentável, dívidas, tendências de compras", it: "Analisi dettagliata: acquirente più redditizio, debiti, tendenze di acquisto" } },
  ],
};

export default function FeatureBuyerCards() {
  return <FeatureDetail data={data} />;
}
