import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureMaintenance() {
  return <FeatureDetail data={{
    category: { sq: "Flotë", en: "Fleet", es: "Flota", de: "Flotte", mk: "Флота" },
    categoryColor: "bg-rose-500",
    title: { sq: "Mirëmbajtje & Servisimet", en: "Maintenance & Service", es: "Mantenimiento & Servicio", de: "Wartung & Service", mk: "Одржување & Сервисирање" },
    tagline: { sq: "Asnjë servisim nuk harrohet, asnjë kosto nuk fshihet", en: "No service is forgotten, no cost is hidden", es: "Ningún servicio se olvida, ningún costo se oculta", de: "Kein Service wird vergessen, keine Kosten werden versteckt", mk: "Ниту еден сервис не се заборава, ниту еден трошок не се крие" },
    stat: { sq: "60% ulje dështimesh", en: "60% fewer breakdowns", es: "60% menos averías", de: "60% weniger Ausfälle", mk: "60% помалку дефекти" },
    description: {
      sq: "Planifikoni dhe gjurmoni çdo servisim, ndërrimin e gomave, kontrollin teknik dhe çdo riparim. Merrni alarme automatike bazuar në km ose datë. Të gjitha kostot regjistrohen direkt në shpenzimet e kompanisë.",
      en: "Plan and track every service, tyre change, technical inspection and any repair. Receive automatic alerts based on km or date. All costs are recorded directly in company expenses.",
      es: "Planifique y rastree cada servicio, cambio de neumáticos, inspección técnica y cualquier reparación. Reciba alertas automáticas basadas en km o fecha. Todos los costos se registran directamente en los gastos de la empresa.",
      de: "Planen und verfolgen Sie jeden Service, Reifenwechsel, technische Inspektion und jede Reparatur. Erhalten Sie automatische Alarme basierend auf km oder Datum. Alle Kosten werden direkt in den Firmenausgaben erfasst.",
      mk: "Планирајте и следете секој сервис, промена на гуми, технички преглед и секоја поправка. Добивајте автоматски аларми базирани на km или датум. Сите трошоци се евидентираат директно во трошоците на компанијата.",
    },
    benefits: [
      { sq: "Plani i servisimeve sipas km ose datës", en: "Service plan based on km or date", es: "Plan de servicio basado en km o fecha", de: "Serviceplan basierend auf km oder Datum", mk: "План за сервисирање според km или датум" },
      { sq: "Alarme automatike: ndërrimi gomave, vaj, filtra", en: "Automatic alerts: tyre change, oil, filters", es: "Alertas automáticas: cambio de neumáticos, aceite, filtros", de: "Automatische Alarme: Reifenwechsel, Öl, Filter", mk: "Автоматски аларми: промена на гуми, масло, филтри" },
      { sq: "Regjistrim i çdo riparimi me kosto", en: "Registration of every repair with cost", es: "Registro de cada reparación con costo", de: "Erfassung jeder Reparatur mit Kosten", mk: "Евидентирање на секоја поправка со трошок" },
      { sq: "Kontroll teknik dhe afate inspektimi", en: "Technical inspection and inspection deadlines", es: "Inspección técnica y plazos de inspección", de: "Technische Inspektion und Inspektionsfristen", mk: "Технички преглед и рокови за инспекција" },
      { sq: "Lidhje direkte me shpenzimet e kompanisë", en: "Direct connection with company expenses", es: "Conexión directa con los gastos de la empresa", de: "Direkte Verbindung mit Firmenausgaben", mk: "Директна врска со трошоците на компанијата" },
      { sq: "Raporte kosto mirëmbajtjeje për çdo automjet", en: "Maintenance cost reports for each vehicle", es: "Informes de costos de mantenimiento para cada vehículo", de: "Wartungskostenberichte für jedes Fahrzeug", mk: "Извештаи за трошоци на одржување за секое возило" },
    ],
    workflow: [
      { step: "1", sq: "Krijoni planin e servisimit: ndërrim vaji çdo 10,000 km, goma çdo 40,000 km", en: "Create the service plan: oil change every 10,000 km, tyres every 40,000 km", es: "Cree el plan de servicio: cambio de aceite cada 10,000 km, neumáticos cada 40,000 km", de: "Erstellen Sie den Serviceplan: Ölwechsel alle 10.000 km, Reifen alle 40.000 km", mk: "Креирајте план за сервисирање: промена на масло на секои 10.000 km, гуми на секои 40.000 km" },
      { step: "2", sq: "Sistemi gjurmon km-të dhe dërgon alarme kur afrohet servisi", en: "System tracks km and sends alerts when service approaches", es: "El sistema rastrea km y envía alertas cuando se acerca el servicio", de: "System verfolgt km und sendet Alarme, wenn der Service naht", mk: "Системот ги следи km и испраќа аларми кога се приближува сервисот" },
      { step: "3", sq: "Regjistroni riparimin: lloji, kosto, servisi, data, çfarë u bë", en: "Record the repair: type, cost, service provider, date, what was done", es: "Registre la reparación: tipo, costo, proveedor de servicio, fecha, qué se hizo", de: "Reparatur erfassen: Art, Kosten, Dienstleister, Datum, was gemacht wurde", mk: "Евидентирајте ја поправката: вид, трошок, сервисер, датум, што е направено" },
      { step: "4", sq: "Shpenzimet e mirëmbajtjes lidhen automatikisht me shpenzimet e kompanisë", en: "Maintenance expenses link automatically with company expenses", es: "Los gastos de mantenimiento se vinculan automáticamente con los gastos de la empresa", de: "Wartungskosten werden automatisch mit den Firmenausgaben verknüpft", mk: "Трошоците за одржување автоматски се поврзуваат со трошоците на компанијата" },
    ],
    capabilities: [
      { icon: "🔧", title: { sq: "Plan Servisimi", en: "Service Plan", es: "Plan de Servicio", de: "Serviceplan", mk: "План за Сервисирање" }, desc: { sq: "Caktoni intervale sipas km ose muajve për çdo lloj shërbimi", en: "Set intervals by km or months for every type of service", es: "Establezca intervalos por km o meses para cada tipo de servicio", de: "Intervalle nach km oder Monaten für jede Art von Service festlegen", mk: "Поставете интервали според km или месеци за секој вид сервис" } },
      { icon: "🔔", title: { sq: "Alarme Automatike", en: "Auto Alerts", es: "Alertas Automáticas", de: "Automatische Alarme", mk: "Автоматски Аларми" }, desc: { sq: "Njoftimet vijnë kur afrohet koha e servisimit bazuar në km ose datë", en: "Notifications come when service time approaches based on km or date", es: "Las notificaciones llegan cuando se acerca el tiempo de servicio basado en km o fecha", de: "Benachrichtigungen kommen, wenn die Servicezeit basierend auf km oder Datum naht", mk: "Известувањата доаѓаат кога се приближува времето за сервис базирано на km или датум" } },
      { icon: "🛞", title: { sq: "Ndërrim Gomash", en: "Tyre Changes", es: "Cambio de Neumáticos", de: "Reifenwechsel", mk: "Промена на Гуми" }, desc: { sq: "Gjurmoni sezonen, km e gomave dhe kur duhet ndërruar", en: "Track season, tyre km and when replacement is needed", es: "Rastree la temporada, km de neumáticos y cuándo se necesita reemplazo", de: "Saison, Reifen-km verfolgen und wann ein Wechsel nötig ist", mk: "Следете ја сезоната, km на гумите и кога е потребна замена" } },
      { icon: "📋", title: { sq: "Kontroll Teknik", en: "Technical Inspection", es: "Inspección Técnica", de: "Technische Inspektion", mk: "Технички Преглед" }, desc: { sq: "Regjistroni datat e inspektimit dhe alarme para skadencës", en: "Record inspection dates and alerts before expiry", es: "Registre fechas de inspección y alertas antes del vencimiento", de: "Inspektionsdaten erfassen und Alarme vor Ablauf", mk: "Евидентирајте датуми на инспекција и аларми пред истекување" } },
      { icon: "💶", title: { sq: "Kosto Mirëmbajtje", en: "Maintenance Costs", es: "Costos de Mantenimiento", de: "Wartungskosten", mk: "Трошоци за Одржување" }, desc: { sq: "Çdo kosto regjistrohet dhe lidhet me shpenzimet totale të flotës", en: "Every cost recorded and linked with total fleet expenses", es: "Cada costo registrado y vinculado con los gastos totales de la flota", de: "Jeder Kostenpunkt erfasst und mit den Gesamtflottenkosten verknüpft", mk: "Секој трошок евидентиран и поврзан со вкупните трошоци на флотата" } },
      { icon: "📊", title: { sq: "Historik Servisimi", en: "Service History", es: "Historial de Servicio", de: "Servicehistorie", mk: "Историја на Сервисирање" }, desc: { sq: "Historiku i plotë i çdo riparimi, ndërrimi dhe kontrolli", en: "Complete history of every repair, replacement and inspection", es: "Historial completo de cada reparación, reemplazo e inspección", de: "Vollständige Historie jeder Reparatur, jedes Austauschs und jeder Inspektion", mk: "Целосна историја на секоја поправка, замена и инспекција" } },
    ],
  }} />;
}
