import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureFleet() {
  return <FeatureDetail data={{
    category: { sq: "Flotë", en: "Fleet", es: "Flota", de: "Flotte", mk: "Флота" },
    categoryColor: "bg-amber-500",
    title: { sq: "Motorpool & Flotë Makinash", en: "Motorpool & Fleet Management", es: "Parque Automotor & Gestión de Flota", de: "Fuhrpark & Flottenmanagement", mk: "Возен Парк & Управување со Флота" },
    tagline: { sq: "Menaxhoni çdo makinë, shofer dhe shërbim nga telefoni", en: "Manage every vehicle, driver and service from your phone", es: "Gestione cada vehículo, conductor y servicio desde su teléfono", de: "Verwalten Sie jedes Fahrzeug, jeden Fahrer und jede Wartung vom Telefon", mk: "Управувајте со секое возило, возач и сервис од телефонот" },
    stat: { sq: "100% afate të ndjekura", en: "100% deadlines tracked", es: "100% plazos rastreados", de: "100% Fristen verfolgt", mk: "100% следени рокови" },
    description: {
      sq: "Sistemi i flotës mbulon gjithçka — nga caktimi i shoferëve për udhëtime tek gjurmimi i mirëmbajtjeve, rinovimi i sigurimeve dhe skadencat e regjistrimit. Asnjë afat nuk kalohet pa u vënë re.",
      en: "The fleet system covers everything — from assigning drivers for trips to tracking maintenance, insurance renewals and registration deadlines. No deadline passes unnoticed.",
      es: "El sistema de flota cubre todo — desde la asignación de conductores para viajes hasta el seguimiento de mantenimiento, renovaciones de seguros y plazos de registro. Ningún plazo pasa desapercibido.",
      de: "Das Flottensystem deckt alles ab — von der Zuweisung von Fahrern für Fahrten bis zur Verfolgung von Wartungen, Versicherungserneuerungen und Registrierungsfristen. Keine Frist verstreicht unbemerkt.",
      mk: "Системот за флота покрива сè — од доделување на возачи за патувања до следење на одржување, обновување на осигурувања и рокови за регистрација. Ниту еден рок не поминува незабележано.",
    },
    benefits: [
      { sq: "Regjistrim i flotës: makina, targë, pronësi", en: "Fleet registration: vehicles, plates, ownership", es: "Registro de flota: vehículos, placas, propiedad", de: "Flottenregistrierung: Fahrzeuge, Kennzeichen, Eigentum", mk: "Регистрација на флота: возила, таблички, сопственост" },
      { sq: "Caktim shoferësh për udhëtime (ride dispatch)", en: "Driver assignment for trips (ride dispatch)", es: "Asignación de conductores para viajes (despacho)", de: "Fahrerzuweisung für Fahrten (Disposition)", mk: "Доделување возачи за патувања (диспечирање)" },
      { sq: "Gjurmim mirëmbajtjesh dhe servisimesh", en: "Maintenance and service tracking", es: "Seguimiento de mantenimiento y servicios", de: "Wartungs- und Serviceverfolgung", mk: "Следење на одржување и сервисирање" },
      { sq: "Alarme rinovimi: sigurim, kasko, regjistrimi", en: "Renewal alerts: insurance, casco, registration", es: "Alertas de renovación: seguro, casco, registro", de: "Erneuerungsalarme: Versicherung, Kasko, Registrierung", mk: "Аларми за обновување: осигурување, каско, регистрација" },
      { sq: "Historiku i plotë i shpenzimeve për çdo makinë", en: "Complete expense history for every vehicle", es: "Historial completo de gastos para cada vehículo", de: "Vollständige Ausgabenhistorie für jedes Fahrzeug", mk: "Целосна историја на трошоци за секое возило" },
      { sq: "Raporte km, karburant dhe kosto/makina", en: "km, fuel and cost/vehicle reports", es: "Informes de km, combustible y costo/vehículo", de: "km-, Kraftstoff- und Kosten-/Fahrzeugberichte", mk: "Извештаи за km, гориво и трошок/возило" },
    ],
    workflow: [
      { step: "1", sq: "Regjistroni automjetin: targë, markë, model, viti, pronësia", en: "Register the vehicle: plate, make, model, year, ownership", es: "Registre el vehículo: placa, marca, modelo, año, propiedad", de: "Fahrzeug registrieren: Kennzeichen, Marke, Modell, Jahr, Eigentum", mk: "Регистрирајте го возилото: таблички, марка, модел, година, сопственост" },
      { step: "2", sq: "Caktoni shoferin dhe konfiguroni skadencat (sigurim, kasko, regjistrimi)", en: "Assign the driver and configure deadlines (insurance, casco, registration)", es: "Asigne al conductor y configure los plazos (seguro, casco, registro)", de: "Fahrer zuweisen und Fristen konfigurieren (Versicherung, Kasko, Registrierung)", mk: "Доделете го возачот и конфигурирајте ги роковите (осигурување, каско, регистрација)" },
      { step: "3", sq: "Shoferi raporton km-të dhe karburantin direkt nga telefoni", en: "Driver reports km and fuel directly from phone", es: "El conductor reporta km y combustible directamente desde el teléfono", de: "Fahrer meldet km und Kraftstoff direkt vom Telefon", mk: "Возачот пријавува km и гориво директно од телефонот" },
      { step: "4", sq: "Sistemi dërgon alarme automatike kur afrohet skadenca e sigurimeve", en: "System sends automatic alerts when insurance deadlines approach", es: "El sistema envía alertas automáticas cuando se acercan los plazos del seguro", de: "System sendet automatische Alarme, wenn sich Versicherungsfristen nähern", mk: "Системот испраќа автоматски аларми кога се приближуваат роковите за осигурување" },
      { step: "5", sq: "Shikoni raporte: kosto/makinë, km/muaj, karburant/100km", en: "View reports: cost/vehicle, km/month, fuel/100km", es: "Vea informes: costo/vehículo, km/mes, combustible/100km", de: "Berichte ansehen: Kosten/Fahrzeug, km/Monat, Kraftstoff/100km", mk: "Погледнете извештаи: трошок/возило, km/месец, гориво/100km" },
    ],
    capabilities: [
      { icon: "🚗", title: { sq: "Regjistrim Flotë", en: "Fleet Registration", es: "Registro de Flota", de: "Flottenregistrierung", mk: "Регистрација на Флота" }, desc: { sq: "Regjistroni çdo automjet me targë, model, vit dhe dokumentacion", en: "Register every vehicle with plate, model, year and documentation", es: "Registre cada vehículo con placa, modelo, año y documentación", de: "Registrieren Sie jedes Fahrzeug mit Kennzeichen, Modell, Jahr und Dokumentation", mk: "Регистрирајте секое возило со таблички, модел, година и документација" } },
      { icon: "👨‍✈️", title: { sq: "Dispatch Shoferësh", en: "Driver Dispatch", es: "Despacho de Conductores", de: "Fahrerdisposition", mk: "Диспечирање на Возачи" }, desc: { sq: "Caktoni shoferë për udhëtime me orar, destinacion dhe status", en: "Assign drivers for trips with schedule, destination and status", es: "Asigne conductores para viajes con horario, destino y estado", de: "Weisen Sie Fahrern Fahrten mit Zeitplan, Ziel und Status zu", mk: "Доделете возачи за патувања со распоред, дестинација и статус" } },
      { icon: "⏰", title: { sq: "Alarme Skadence", en: "Deadline Alerts", es: "Alertas de Vencimiento", de: "Fristalarme", mk: "Аларми за Рокови" }, desc: { sq: "Asnjë sigurim, regjistrimi apo kasko nuk skadon pa alarme", en: "No insurance, registration or casco expires without alerts", es: "Ningún seguro, registro o casco vence sin alertas", de: "Keine Versicherung, Registrierung oder Kasko läuft ohne Alarm ab", mk: "Ниту едно осигурување, регистрација или каско не истекува без аларми" } },
      { icon: "⛽", title: { sq: "Gjurmim Karburanti", en: "Fuel Tracking", es: "Seguimiento de Combustible", de: "Kraftstoffverfolgung", mk: "Следење на Гориво" }, desc: { sq: "Monitoroni konsumin e karburantit për çdo automjet", en: "Monitor fuel consumption for every vehicle", es: "Monitoree el consumo de combustible de cada vehículo", de: "Überwachen Sie den Kraftstoffverbrauch für jedes Fahrzeug", mk: "Следете ја потрошувачката на гориво за секое возило" } },
      { icon: "💶", title: { sq: "Kosto per Makinë", en: "Cost per Vehicle", es: "Costo por Vehículo", de: "Kosten pro Fahrzeug", mk: "Трошок по Возило" }, desc: { sq: "Shpenzimet totale: karburant, mirëmbajtje, sigurim, goba", en: "Total expenses: fuel, maintenance, insurance, fines", es: "Gastos totales: combustible, mantenimiento, seguro, multas", de: "Gesamtkosten: Kraftstoff, Wartung, Versicherung, Bußgelder", mk: "Вкупни трошоци: гориво, одржување, осигурување, казни" } },
      { icon: "📊", title: { sq: "Raporte Flotë", en: "Fleet Reports", es: "Informes de Flota", de: "Flottenberichte", mk: "Извештаи за Флота" }, desc: { sq: "Analiza me grafiqe: km, kosto, efikasiteti, shoferi më i mirë", en: "Chart analytics: km, cost, efficiency, best driver", es: "Análisis con gráficos: km, costo, eficiencia, mejor conductor", de: "Diagrammanalysen: km, Kosten, Effizienz, bester Fahrer", mk: "Анализи со графикони: km, трошок, ефикасност, најдобар возач" } },
    ],
  }} />;
}
