import FeatureDetail from "@/components/FeatureDetail";

const data = {
  category: { sq: "HR & Ekipi", en: "HR & Team", es: "RRHH & Equipo", de: "HR & Team", mk: "HR & Тим" },
  categoryColor: "bg-teal-500",
  title: { sq: "Trajnim & Kuize", en: "Training & Quizzes", es: "Capacitación & Cuestionarios", de: "Schulung & Quizze", mk: "Обука & Квизови" },
  tagline: { sq: "Trajnoni ekipin tuaj drejtpërdrejt në platformë", en: "Train your team directly in the platform", es: "Capacite a su equipo directamente en la plataforma", de: "Schulen Sie Ihr Team direkt auf der Plattform", mk: "Обучете го вашиот тим директно на платформата" },
  stat: { sq: "100% ekip i trajnuar", en: "100% trained team", es: "100% equipo capacitado", de: "100% geschultes Team", mk: "100% обучен тим" },
  description: {
    sq: "Krijoni programe trajnimi me kuize, testime dhe certifikata dixhitale për çdo punonjës. Gjurmoni progresin e trajnimit dhe siguroni që ekipi juaj është gjithmonë i përgatitur. Materialet e trajnimit ruhen në platformë dhe janë të aksesueshme nga çdo pajisje.",
    en: "Create training programs with quizzes, tests and digital certificates for each employee. Track training progress and ensure your team is always prepared. Training materials are stored on the platform and accessible from any device.",
    es: "Cree programas de capacitación con cuestionarios, pruebas y certificados digitales para cada empleado. Rastree el progreso de la capacitación y asegúrese de que su equipo esté siempre preparado. Los materiales de capacitación se almacenan en la plataforma y son accesibles desde cualquier dispositivo.",
    de: "Erstellen Sie Schulungsprogramme mit Quizzen, Tests und digitalen Zertifikaten für jeden Mitarbeiter. Verfolgen Sie den Schulungsfortschritt und stellen Sie sicher, dass Ihr Team immer vorbereitet ist. Schulungsmaterialien werden auf der Plattform gespeichert und sind von jedem Gerät aus zugänglich.",
    mk: "Креирајте програми за обука со квизови, тестови и дигитални сертификати за секој вработен. Следете го напредокот на обуката и осигурајте дека вашиот тим е секогаш подготвен. Материјалите за обука се чуваат на платформата и се достапни од секој уред.",
  },
  benefits: [
    { sq: "Kuize dhe testime interaktive", en: "Interactive quizzes and tests", es: "Cuestionarios y pruebas interactivas", de: "Interaktive Quizze und Tests", mk: "Интерактивни квизови и тестови" },
    { sq: "Certifikata dixhitale pas kalimit të provimit", en: "Digital certificates after passing the test", es: "Certificados digitales tras aprobar la prueba", de: "Digitale Zertifikate nach Bestehen des Tests", mk: "Дигитални сертификати по полагање на тестот" },
    { sq: "Programe trajnimi me module të ndryshme", en: "Training programs with different modules", es: "Programas de capacitación con diferentes módulos", de: "Schulungsprogramme mit verschiedenen Modulen", mk: "Програми за обука со различни модули" },
    { sq: "Gjurmim i progresit të çdo punonjësi", en: "Progress tracking for each employee", es: "Seguimiento del progreso de cada empleado", de: "Fortschrittsverfolgung für jeden Mitarbeiter", mk: "Следење на напредокот на секој вработен" },
    { sq: "Material trajnimi: video, PDF, artikuj", en: "Training materials: video, PDF, articles", es: "Materiales de capacitación: video, PDF, artículos", de: "Schulungsmaterialien: Video, PDF, Artikel", mk: "Материјали за обука: видео, PDF, статии" },
    { sq: "Raporte detajuara të trajnimit të ekipit", en: "Detailed team training reports", es: "Informes detallados de capacitación del equipo", de: "Detaillierte Team-Schulungsberichte", mk: "Детални извештаи за обука на тимот" },
  ],
  workflow: [
    { step: "1", sq: "Krijoni programin e trajnimit me titull, përshkrim dhe modulet e nevojshme", en: "Create the training program with title, description and required modules", es: "Cree el programa de capacitación con título, descripción y módulos requeridos", de: "Erstellen Sie das Schulungsprogramm mit Titel, Beschreibung und erforderlichen Modulen", mk: "Креирајте ја програмата за обука со наслов, опис и потребни модули" },
    { step: "2", sq: "Ngarkoni materialet: video, PDF, artikuj — dhe krijoni kuizet me pyetje", en: "Upload materials: video, PDF, articles — and create quizzes with questions", es: "Cargue materiales: video, PDF, artículos — y cree cuestionarios con preguntas", de: "Materialien hochladen: Video, PDF, Artikel — und Quizze mit Fragen erstellen", mk: "Прикачете материјали: видео, PDF, статии — и креирајте квизови со прашања" },
    { step: "3", sq: "Caktoni trajnimin te punonjësit ose ekipet specifike", en: "Assign the training to specific employees or teams", es: "Asigne la capacitación a empleados o equipos específicos", de: "Weisen Sie die Schulung bestimmten Mitarbeitern oder Teams zu", mk: "Доделете ја обуката на одредени вработени или тимови" },
    { step: "4", sq: "Punonjësit studiojnë materialet dhe plotësojnë kuizet nga telefoni ose PC", en: "Employees study materials and complete quizzes from phone or PC", es: "Los empleados estudian materiales y completan cuestionarios desde teléfono o PC", de: "Mitarbeiter studieren Materialien und absolvieren Quizze vom Telefon oder PC", mk: "Вработените ги изучуваат материјалите и ги пополнуваат квизовите од телефон или PC" },
    { step: "5", sq: "Pas kalimit të provimit, certifikata dixhitale gjenerohet automatikisht", en: "After passing the test, the digital certificate is generated automatically", es: "Tras aprobar la prueba, el certificado digital se genera automáticamente", de: "Nach Bestehen des Tests wird das digitale Zertifikat automatisch generiert", mk: "По полагање на тестот, дигиталниот сертификат се генерира автоматски" },
  ],
  capabilities: [
    { icon: "📝", title: { sq: "Kuize Interaktive", en: "Interactive Quizzes", es: "Cuestionarios Interactivos", de: "Interaktive Quizze", mk: "Интерактивни Квизови" }, desc: { sq: "Krijoni pyetje me zgjedhje, tekst ose pikë — me rezultate automatike", en: "Create multiple choice, text or point questions — with auto scoring", es: "Cree preguntas de opción múltiple, texto o puntos — con puntuación automática", de: "Multiple-Choice-, Text- oder Punktfragen erstellen — mit automatischer Bewertung", mk: "Креирајте прашања со избор, текст или поени — со автоматско оценување" } },
    { icon: "🎓", title: { sq: "Certifikata Dixhitale", en: "Digital Certificates", es: "Certificados Digitales", de: "Digitale Zertifikate", mk: "Дигитални Сертификати" }, desc: { sq: "Certifikata e personalizuar me logon tuaj gjenerohet pas kalimit të provimit", en: "Customized certificate with your logo generated after passing the test", es: "Certificado personalizado con su logo generado tras aprobar la prueba", de: "Personalisiertes Zertifikat mit Ihrem Logo wird nach Bestehen des Tests generiert", mk: "Персонализиран сертификат со вашето лого се генерира по полагање на тестот" } },
    { icon: "📹", title: { sq: "Material Multimediale", en: "Multimedia Materials", es: "Materiales Multimedia", de: "Multimedia-Materialien", mk: "Мултимедијални Материјали" }, desc: { sq: "Ngarkoni video, PDF, artikuj dhe prezantime si material trajnimi", en: "Upload video, PDF, articles and presentations as training material", es: "Cargue video, PDF, artículos y presentaciones como material de capacitación", de: "Video, PDF, Artikel und Präsentationen als Schulungsmaterial hochladen", mk: "Прикачете видео, PDF, статии и презентации како материјал за обука" } },
    { icon: "📊", title: { sq: "Gjurmim Progresit", en: "Progress Tracking", es: "Seguimiento del Progreso", de: "Fortschrittsverfolgung", mk: "Следење на Напредок" }, desc: { sq: "Shikoni kush e ka përfunduar trajnimin, rezultatet dhe kohën", en: "See who completed training, results and time spent", es: "Vea quién completó la capacitación, resultados y tiempo invertido", de: "Sehen Sie, wer die Schulung abgeschlossen hat, Ergebnisse und aufgewendete Zeit", mk: "Видете кој ја завршил обуката, резултатите и потрошеното време" } },
    { icon: "👥", title: { sq: "Caktim Ekipor", en: "Team Assignment", es: "Asignación de Equipo", de: "Teamzuweisung", mk: "Тимско Доделување" }, desc: { sq: "Caktoni trajnime specifike për departamente, pozita ose individë", en: "Assign specific training to departments, positions or individuals", es: "Asigne capacitación específica a departamentos, posiciones o individuos", de: "Weisen Sie bestimmte Schulungen Abteilungen, Positionen oder Einzelpersonen zu", mk: "Доделете специфична обука на одделенија, позиции или поединци" } },
    { icon: "🔄", title: { sq: "Ritrajnim Automatik", en: "Auto Retraining", es: "Recapacitación Automática", de: "Automatische Nachschulung", mk: "Автоматска Преобука" }, desc: { sq: "Caktoni afate skadimi dhe ritrajnim automatik kur certifikata skadon", en: "Set expiry dates and auto retraining when certificate expires", es: "Establezca fechas de vencimiento y recapacitación automática cuando el certificado expire", de: "Verfallsdaten und automatische Nachschulung bei Zertifikatsablauf festlegen", mk: "Поставете рокови на истекување и автоматска преобука кога сертификатот истекува" } },
  ],
};

export default function FeatureTraining() {
  return <FeatureDetail data={data} />;
}
