import FeatureDetail from "@/components/FeatureDetail";

export default function FeaturePayroll() {
  return <FeatureDetail data={{
    category: { sq: "HR & Ekipi", en: "HR & Team", es: "RRHH & Equipo", de: "HR & Team", mk: "HR & Тим", fr: "RH & Équipe", pt: "RH & Equipa", it: "HR & Team" },
    categoryColor: "bg-blue-500",
    title: { sq: "Paga & Kompensimi", en: "Payroll & Compensation", es: "Nómina & Compensación", de: "Gehaltsabrechnung & Vergütung", mk: "Плата & Компензација", fr: "Paie & Rémunération", pt: "Salários & Remuneração", it: "Stipendi & Retribuzione" },
    tagline: { sq: "Çdo mënyrë pagese — e automatizuar plotësisht", en: "Every payment method — fully automated", es: "Cada método de pago — totalmente automatizado", de: "Jede Zahlungsmethode — vollständig automatisiert", mk: "Секој метод на плаќање — целосно автоматизиран", fr: "Chaque méthode de paiement — entièrement automatisée", pt: "Cada método de pagamento — totalmente automatizado", it: "Ogni metodo di pagamento — completamente automatizzato" },
    stat: { sq: "100% saktësi llogaritje page", en: "100% payroll accuracy", es: "100% precisión de nómina", de: "100% Gehaltsabrechnungsgenauigkeit", mk: "100% точност на плата" , fr: "100% de précision de la paie", pt: "100% de precisão de salários", it: "100% di precisione degli stipendi" },
    description: {
      sq: "Konfiguroni pagën për çdo punonjës sipas mënyrës që i përshtatet rolit të tij — pagë fikse, komision, kombinim, ose bonus performancë. Llogaritja bëhet automatikisht bazuar në orët e prezencës.",
      en: "Configure pay for each employee according to their role — fixed salary, commission, combination, or performance bonus. The calculation is done automatically based on attendance hours.",
      es: "Configure el pago para cada empleado según su rol — salario fijo, comisión, combinación o bonificación por rendimiento. El cálculo se realiza automáticamente basado en las horas de asistencia.",
      de: "Konfigurieren Sie die Vergütung für jeden Mitarbeiter entsprechend seiner Rolle — Festgehalt, Provision, Kombination oder Leistungsbonus. Die Berechnung erfolgt automatisch basierend auf den Anwesenheitsstunden.",
      mk: "Конфигурирајте ја платата за секој вработен според неговата улога — фиксна плата, провизија, комбинација или бонус за перформанси. Пресметката се врши автоматски врз основа на часовите на присуство.",
    , fr: "Configurez la paie pour chaque employé selon son rôle — salaire fixe, commission, combinaison ou bonus de performance. Le calcul est effectué automatiquement en fonction des heures de présence.", pt: "Configure o salário de cada funcionário de acordo com o seu papel — salário fixo, comissão, combinação ou bónus de desempenho. O cálculo é feito automaticamente com base nas horas de presença.", it: "Configura la retribuzione per ogni dipendente in base al suo ruolo — stipendio fisso, commissione, combinazione o bonus di prestazione. Il calcolo viene eseguito automaticamente in base alle ore di presenze." },
    benefits: [
      { sq: "Pagë fikse mujore ose javore", en: "Fixed monthly or weekly salary", es: "Salario fijo mensual o semanal", de: "Festes Monats- oder Wochengehalt", mk: "Фиксна месечна или неделна плата", fr: "Salaire mensuel ou hebdomadaire fixe", pt: "Salário mensal ou semanal fixo", it: "Stipendio fisso mensile o settimanale" },
      { sq: "Komision me përqindje të shitjeve", en: "Commission with sales percentage", es: "Comisión con porcentaje de ventas", de: "Provision mit Verkaufsprozentsatz", mk: "Провизија со процент од продажба", fr: "Commission avec pourcentage de ventes", pt: "Comissão com percentagem de vendas", it: "Commissione con percentuale di vendita" },
      { sq: "Pagë fikse + përqindje (hibride)", en: "Fixed salary + percentage (hybrid)", es: "Salario fijo + porcentaje (híbrido)", de: "Festgehalt + Prozentsatz (hybrid)", mk: "Фиксна плата + процент (хибридна)", fr: "Salaire fixe + pourcentage (hybride)", pt: "Salário fixo + percentagem (híbrido)", it: "Stipendio fisso + percentuale (ibrido)" },
      { sq: "Bonus performancë dhe stimuj të personalizuar", en: "Performance bonuses and personalised incentives", es: "Bonificaciones por rendimiento e incentivos personalizados", de: "Leistungsboni und personalisierte Anreize", mk: "Бонуси за перформанси и персонализирани стимулации" , fr: "Bonus de performance et incentifs personnalisés", pt: "Bónus de desempenho e incentivos personalizados", it: "Bonus di prestazione e incentivi personalizzati" },
      { sq: "Llogaritje automatike bazuar në orë prezence", en: "Automatic calculation based on attendance hours", es: "Cálculo automático basado en horas de asistencia", de: "Automatische Berechnung basierend auf Anwesenheitsstunden", mk: "Автоматска пресметка базирана на часови на присуство", fr: "Calcul automatique basé sur les heures de présence", pt: "Cálculo automático baseado nas horas de presença", it: "Calcolo automatico basato sulle ore di presenze" },
      { sq: "Raporte pagash dhe eksport payroll", en: "Payroll reports and payroll export", es: "Informes de nómina y exportación de nómina", de: "Gehaltsberichte und Gehaltsexport", mk: "Извештаи за плати и извоз на платен список" , fr: "Rapports de paie et export de la paie", pt: "Relatórios de salários e exportação de salários", it: "Report degli stipendi ed esportazione busta paga" },
    ],
    workflow: [
      { step: "1", sq: "Konfiguroni llojin e pagës: fikse, komision, hibride ose bonus", en: "Configure the pay type: fixed, commission, hybrid or bonus", es: "Configure el tipo de pago: fijo, comisión, híbrido o bonificación", de: "Vergütungstyp konfigurieren: fest, Provision, hybrid oder Bonus", mk: "Конфигурирајте го типот на плата: фиксна, провизија, хибридна или бонус" , fr: "Configurez le type de paie: fixe, commission, hybride ou bonus", pt: "Configure o tipo de remuneração: fixo, comissão, híbrido ou bónus", it: "Configura il tipo di retribuzione: fisso, commissione, ibrido o bonus" },
      { step: "2", sq: "Sistemi lexon orët e prezencës automatikisht nga moduli i prezencës", en: "System reads attendance hours automatically from the attendance module", es: "El sistema lee las horas de asistencia automáticamente del módulo de asistencia", de: "System liest Anwesenheitsstunden automatisch aus dem Anwesenheitsmodul", mk: "Системот ги чита часовите на присуство автоматски од модулот за присуство" , fr: "Le système lit automatiquement les heures de présence du module de présence", pt: "O sistema lê automaticamente as horas de presença do módulo de presença", it: "Il sistema legge automaticamente le ore di presenze dal modulo presenze" },
      { step: "3", sq: "Llogaritja e pagës bëhet automatikisht: bazë + orë shtesë + bonus", en: "Payroll calculation done automatically: base + overtime + bonus", es: "Cálculo de nómina realizado automáticamente: base + horas extra + bonificación", de: "Gehaltsberechnung automatisch: Basis + Überstunden + Bonus", mk: "Пресметката на платата се врши автоматски: основа + прекувремена работа + бонус" , fr: "Calcul de la paie automatiquement: base + heures sup + bonus", pt: "Cálculo de salários feito automaticamente: base + horas extras + bónus", it: "Calcolo degli stipendi fatto automaticamente: base + straordinari + bonus" },
      { step: "4", sq: "Aprovoni pagat dhe eksportoni raportin për bankën ose kontabilistin", en: "Approve payroll and export the report for bank or accountant", es: "Apruebe la nómina y exporte el informe para el banco o contador", de: "Gehaltsabrechnung genehmigen und Bericht für Bank oder Buchhalter exportieren", mk: "Одобрете ги платите и извезете го извештајот за банката или сметководителот" , fr: "Approuvez la paie et exportez le rapport pour la banque ou le comptable", pt: "Aprove os salários e exporte o relatório para o banco ou contabilista", it: "Approva gli stipendi ed esporta il report per la banca o il contabile" },
    ],
    capabilities: [
      { icon: "💵", title: { sq: "Pagë Fikse", en: "Fixed Salary", es: "Salario Fijo", de: "Festgehalt", mk: "Фиксна Плата" , fr: "Salaire fixe", pt: "Salário fixo", it: "Stipendio fisso" }, desc: { sq: "Pagë standarde mujore ose javore e konfiguruar për çdo punonjës", en: "Standard monthly or weekly salary configured for each employee", es: "Salario estándar mensual o semanal configurado para cada empleado", de: "Standard-Monats- oder Wochengehalt für jeden Mitarbeiter konfiguriert", mk: "Стандардна месечна или неделна плата конфигурирана за секој вработен" , fr: "Salaire mensuel ou hebdomadaire standard configuré pour chaque employé", pt: "Salário mensal ou semanal padrão configurado para cada funcionário", it: "Stipendio mensile o settimanale standard configurato per ogni dipendente" } },
      { icon: "📈", title: { sq: "Komision Shitjesh", en: "Sales Commission", es: "Comisión de Ventas", de: "Verkaufsprovision", mk: "Провизија од Продажба" , fr: "Commission de vente", pt: "Comissão de vendas", it: "Commissione di vendita" }, desc: { sq: "Përqindje automatike bazuar në shitjet e çdo punonjësi", en: "Automatic percentage based on each employee's sales", es: "Porcentaje automático basado en las ventas de cada empleado", de: "Automatischer Prozentsatz basierend auf den Verkäufen jedes Mitarbeiters", mk: "Автоматски процент базиран на продажбите на секој вработен" , fr: "Pourcentage automatique basé sur les ventes de chaque employé", pt: "Percentagem automática baseada nas vendas de cada funcionário", it: "Percentuale automatica basata sulle vendite di ogni dipendente" } },
      { icon: "🔀", title: { sq: "Pagë Hibride", en: "Hybrid Pay", es: "Pago Híbrido", de: "Hybridgehalt", mk: "Хибридна Плата" , fr: "Paie hybride", pt: "Remuneração híbrida", it: "Retribuzione ibrida" }, desc: { sq: "Kombinoni pagë fikse me përqindje shitjesh për fleksibilitet", en: "Combine fixed salary with sales percentage for flexibility", es: "Combine salario fijo con porcentaje de ventas para flexibilidad", de: "Festgehalt mit Verkaufsprozentsatz für Flexibilität kombinieren", mk: "Комбинирајте фиксна плата со процент од продажба за флексибилност" , fr: "Combinez salaire fixe et pourcentage de ventes pour la flexibilité", pt: "Combine salário fixo com percentagem de vendas para flexibilidade", it: "Combina stipendio fisso con percentuale di vendite per flessibilità" } },
      { icon: "🏆", title: { sq: "Bonus Performancë", en: "Performance Bonus", es: "Bonificación por Rendimiento", de: "Leistungsbonus", mk: "Бонус за Перформанси" , fr: "Bonus de performance", pt: "Bónus de desempenho", it: "Bonus di prestazione" }, desc: { sq: "Stimuj bazuar në objektivat dhe performancën e ekipit", en: "Incentives based on objectives and team performance", es: "Incentivos basados en objetivos y rendimiento del equipo", de: "Anreize basierend auf Zielen und Teamleistung", mk: "Стимулации базирани на цели и перформанси на тимот" , fr: "Incentifs basés sur les objectifs et la performance de l'équipe", pt: "Incentivos baseados em objetivos e desempenho da equipa", it: "Incentivi basati sugli obiettivi e sulle prestazioni del team" } },
      { icon: "⏱️", title: { sq: "Orë Shtesë", en: "Overtime", es: "Horas Extra", de: "Überstunden", mk: "Прекувремена Работа" , fr: "Heures supplémentaires", pt: "Horas extras", it: "Straordinari" }, desc: { sq: "Llogaritje automatike e orëve shtesë me tarifa të konfiguruara", en: "Automatic overtime calculation with configured rates", es: "Cálculo automático de horas extra con tarifas configuradas", de: "Automatische Überstundenberechnung mit konfigurierten Sätzen", mk: "Автоматска пресметка на прекувремена работа со конфигурирани тарифи" , fr: "Calcul automatique des heures supplémentaires avec les taux configurés", pt: "Cálculo automático de horas extras com as taxas configuradas", it: "Calcolo automatico degli straordinari con le tariffe configurate" } },
      { icon: "📊", title: { sq: "Raporte Pagash", en: "Payroll Reports", es: "Informes de Nómina", de: "Gehaltsberichte", mk: "Извештаи за Плати" , fr: "Rapports de paie", pt: "Relatórios de salários", it: "Report degli stipendi" }, desc: { sq: "Eksportoni raporte detale për bankë, kontabilist ose menaxher", en: "Export detailed reports for bank, accountant or manager", es: "Exporte informes detallados para banco, contador o gerente", de: "Detaillierte Berichte für Bank, Buchhalter oder Manager exportieren", mk: "Извезете детални извештаи за банка, сметководител или менаџер" , fr: "Exportez des rapports détaillés pour la banque, le comptable ou le manager", pt: "Exporte relatórios detalhados para banco, contabilista ou gestor", it: "Esporta report dettagliati per la banca, il contabile o il manager" } },
    ],
  }} />;
}
