import FeatureDetail from "@/components/FeatureDetail";

const data = {
  category: { sq: "Financë", en: "Finance", es: "Finanzas", de: "Finanzen", mk: "Финансии" },
  categoryColor: "bg-cyan-500",
  title: { sq: "Oferta & Kuota Elektronike", en: "Electronic Quotes & Offers", es: "Cotizaciones & Ofertas Electrónicas", de: "Elektronische Angebote & Offerten", mk: "Електронски Понуди & Офери" },
  tagline: { sq: "Dërgoni, gjurmoni dhe nënshkruani — pa letër", en: "Send, track and sign — paperless", es: "Envíe, rastree y firme — sin papel", de: "Senden, verfolgen und unterschreiben — papierlos", mk: "Испратете, следете и потпишете — без хартија" },
  stat: { sq: "3× oferta të aprovuara", en: "3× faster quote approval", es: "3× aprobación de cotizaciones más rápida", de: "3× schnellere Angebotsgenehmigung", mk: "3× побрзо одобрување на понуди" },
  description: {
    sq: "Krijoni oferta profesionale me shabllone të ndryshme dhe dërgojini direkt me email. Klienti e hap, e lexon dhe e nënshkruan direkt nga telefoni ose kompjuteri i tij. Ju shikoni çdo hap në kohë reale — nga momenti i dërgimit deri te nënshkrimi final.",
    en: "Create professional quotes with different templates and send them directly by email. The client opens, reads and signs directly from their phone or computer. You see every step in real time — from the moment of sending to the final signature.",
    es: "Cree cotizaciones profesionales con diferentes plantillas y envíelas directamente por correo electrónico. El cliente abre, lee y firma directamente desde su teléfono o computadora. Usted ve cada paso en tiempo real — desde el momento del envío hasta la firma final.",
    de: "Erstellen Sie professionelle Angebote mit verschiedenen Vorlagen und senden Sie sie direkt per E-Mail. Der Kunde öffnet, liest und unterschreibt direkt von seinem Telefon oder Computer. Sie sehen jeden Schritt in Echtzeit — vom Moment des Versands bis zur endgültigen Unterschrift.",
    mk: "Креирајте професионални понуди со различни шаблони и испратете ги директно по е-пошта. Клиентот отвора, чита и потпишува директно од телефонот или компјутерот. Вие го гледате секој чекор во реално време — од моментот на испраќање до финалниот потпис.",
  },
  benefits: [
    { sq: "Dërgim elektronik me email — pa printer, pa letër", en: "Electronic delivery by email — no printer, no paper", es: "Entrega electrónica por correo — sin impresora, sin papel", de: "Elektronischer Versand per E-Mail — kein Drucker, kein Papier", mk: "Електронска достава по е-пошта — без печатач, без хартија" },
    { sq: "Klienti nënshkruan direkt nga telefoni ose PC", en: "Client signs directly from phone or PC", es: "El cliente firma directamente desde teléfono o PC", de: "Kunde unterschreibt direkt vom Telefon oder PC", mk: "Клиентот потпишува директно од телефон или PC" },
    { sq: "Ju nënshkruani gjithashtu nga aplikacioni", en: "You also sign from the app", es: "Usted también firma desde la aplicación", de: "Sie unterschreiben ebenfalls über die App", mk: "Вие исто така потпишувате од апликацијата" },
    { sq: "Gjurmim: dërguar → hapur → lexuar → nënshkruar", en: "Tracking: sent → opened → read → signed", es: "Seguimiento: enviado → abierto → leído → firmado", de: "Verfolgung: gesendet → geöffnet → gelesen → unterschrieben", mk: "Следење: испратено → отворено → прочитано → потпишано" },
    { sq: "Njoftim i menjëhershëm kur klienti e hap ofertën", en: "Instant alert when client opens the quote", es: "Alerta instantánea cuando el cliente abre la cotización", de: "Sofortige Benachrichtigung, wenn der Kunde das Angebot öffnet", mk: "Моментално известување кога клиентот ја отвора понудата" },
    { sq: "Konvertim automatik Ofertë → Faturë pas aprovimit", en: "Auto conversion Quote → Invoice after approval", es: "Conversión automática Cotización → Factura tras aprobación", de: "Automatische Umwandlung Angebot → Rechnung nach Genehmigung", mk: "Автоматска конверзија Понуда → Фактура по одобрување" },
  ],
  workflow: [
    { step: "1", sq: "Zgjidhni shabllon oferte dhe plotësoni artikujt, çmimet dhe kushtet", en: "Choose a quote template and fill in items, prices and terms", es: "Elija una plantilla de cotización y complete artículos, precios y términos", de: "Wählen Sie eine Angebotsvorlage und füllen Sie Artikel, Preise und Bedingungen aus", mk: "Изберете шаблон за понуда и пополнете ги артиклите, цените и условите" },
    { step: "2", sq: "Dërgoni ofertën me email direkt nga Clientlly — klienti merr linkun", en: "Send the quote by email directly from Clientlly — the client receives the link", es: "Envíe la cotización por correo directamente desde Clientlly — el cliente recibe el enlace", de: "Senden Sie das Angebot per E-Mail direkt von Clientlly — der Kunde erhält den Link", mk: "Испратете ја понудата по е-пошта директно од Clientlly — клиентот го добива линкот" },
    { step: "3", sq: "Gjurmoni në kohë reale: kur hapet, sa herë lexohet, dhe kur nënshkruhet", en: "Track in real time: when it's opened, how many times it's read, and when it's signed", es: "Rastree en tiempo real: cuándo se abre, cuántas veces se lee y cuándo se firma", de: "Verfolgen Sie in Echtzeit: wann es geöffnet wird, wie oft es gelesen wird und wann es unterschrieben wird", mk: "Следете во реално време: кога се отвора, колку пати се чита и кога се потпишува" },
    { step: "4", sq: "Klienti nënshkruan dixhitalisht nga telefoni ose kompjuteri — pa printer", en: "Client signs digitally from phone or computer — no printer needed", es: "El cliente firma digitalmente desde teléfono o computadora — sin necesidad de impresora", de: "Kunde unterschreibt digital vom Telefon oder Computer — kein Drucker nötig", mk: "Клиентот потпишува дигитално од телефон или компјутер — без потреба од печатач" },
    { step: "5", sq: "Oferta e aprovuar konvertohet automatikisht në faturë — pa rishkrim manual", en: "Approved quote automatically converts to invoice — no manual rewriting", es: "La cotización aprobada se convierte automáticamente en factura — sin reescritura manual", de: "Genehmigtes Angebot wird automatisch in Rechnung umgewandelt — kein manuelles Neuschreiben", mk: "Одобрената понуда автоматски се конвертира во фактура — без рачно препишување" },
  ],
  capabilities: [
    { icon: "📄", title: { sq: "Shabllone Profesionale", en: "Professional Templates", es: "Plantillas Profesionales", de: "Professionelle Vorlagen", mk: "Професионални Шаблони" }, desc: { sq: "Shabllone të gatshme me logon dhe markën tuaj. Personalizoni ngjyrat, fontet dhe strukturën", en: "Ready templates with your logo and brand. Customize colors, fonts and structure", es: "Plantillas listas con su logo y marca. Personalice colores, fuentes y estructura", de: "Fertige Vorlagen mit Ihrem Logo und Ihrer Marke. Farben, Schriften und Struktur anpassen", mk: "Готови шаблони со вашето лого и бренд. Прилагодете бои, фонтови и структура" } },
    { icon: "✍️", title: { sq: "Nënshkrim Dixhital", en: "Digital Signature", es: "Firma Digital", de: "Digitale Unterschrift", mk: "Дигитален Потпис" }, desc: { sq: "Klienti dhe ju nënshkruani nga çdo pajisje — ligjërisht e vlefshme dhe e sigurt", en: "Client and you sign from any device — legally valid and secure", es: "El cliente y usted firman desde cualquier dispositivo — legalmente válido y seguro", de: "Kunde und Sie unterschreiben von jedem Gerät — rechtlich gültig und sicher", mk: "Клиентот и вие потпишувате од секој уред — правно валиден и безбеден" } },
    { icon: "👁️", title: { sq: "Gjurmim i Plotë", en: "Full Tracking", es: "Seguimiento Completo", de: "Vollständige Verfolgung", mk: "Целосно Следење" }, desc: { sq: "Shikoni kur oferta hapet, lexohet dhe nënshkruhet — me data dhe orare të sakta", en: "See when the quote is opened, read and signed — with exact dates and times", es: "Vea cuándo la cotización se abre, lee y firma — con fechas y horas exactas", de: "Sehen Sie, wann das Angebot geöffnet, gelesen und unterschrieben wird — mit genauen Daten und Zeiten", mk: "Видете кога понудата се отвора, чита и потпишува — со точни датуми и времиња" } },
    { icon: "🔔", title: { sq: "Njoftime Automatike", en: "Auto Notifications", es: "Notificaciones Automáticas", de: "Automatische Benachrichtigungen", mk: "Автоматски Известувања" }, desc: { sq: "Merrni njoftim menjëherë kur klienti e hap ose e nënshkruan ofertën tuaj", en: "Get notified immediately when the client opens or signs your quote", es: "Reciba notificación inmediata cuando el cliente abra o firme su cotización", de: "Erhalten Sie sofort eine Benachrichtigung, wenn der Kunde Ihr Angebot öffnet oder unterschreibt", mk: "Добијте известување веднаш кога клиентот ја отвора или потпишува вашата понуда" } },
    { icon: "🔄", title: { sq: "Konvertim në Faturë", en: "Invoice Conversion", es: "Conversión a Factura", de: "Rechnungsumwandlung", mk: "Конверзија во Фактура" }, desc: { sq: "Me një klikim, oferta e aprovuar bëhet faturë — pa rishkrim të dhënash", en: "With one click, the approved quote becomes an invoice — no data re-entry", es: "Con un clic, la cotización aprobada se convierte en factura — sin reingresar datos", de: "Mit einem Klick wird das genehmigte Angebot zur Rechnung — keine erneute Dateneingabe", mk: "Со еден клик, одобрената понуда станува фактура — без повторно внесување податоци" } },
    { icon: "📊", title: { sq: "Raporte Ofertash", en: "Quote Reports", es: "Informes de Cotizaciones", de: "Angebotsberichte", mk: "Извештаи за Понуди" }, desc: { sq: "Statistika të ofertave: sa janë dërguar, aprovuar, refuzuar dhe në pritje", en: "Quote statistics: how many sent, approved, rejected and pending", es: "Estadísticas de cotizaciones: cuántas enviadas, aprobadas, rechazadas y pendientes", de: "Angebotsstatistiken: wie viele gesendet, genehmigt, abgelehnt und ausstehend", mk: "Статистики за понуди: колку се испратени, одобрени, одбиени и во чекање" } },
  ],
};

export default function FeatureQuotes() {
  return <FeatureDetail data={data} />;
}
