import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureMaintenance() {
  return <FeatureDetail data={{
    category: { sq: "Flotë", en: "Fleet", es: "Flota", de: "Flotte", mk: "Флота", fr: "Flotte", pt: "Frota", it: "Flotta" },
    categoryColor: "bg-rose-500",
    title: { sq: "Mirëmbajtje & Servisimet", en: "Maintenance & Service", es: "Mantenimiento & Servicio", de: "Wartung & Service", mk: "Одржување & Сервисирање" , fr: "Maintenance & Service", pt: "Manutenção & Serviço", it: "Manutenzione & Servizio" },
    tagline: { sq: "Asnjë servisim nuk harrohet, asnjë kosto nuk fshihet", en: "No service is forgotten, no cost is hidden", es: "Ningún servicio se olvida, ningún costo se oculta", de: "Kein Service wird vergessen, keine Kosten werden versteckt", mk: "Ниту еден сервис не се заборава, ниту еден трошок не се крие" , fr: "Aucun service n'est oublié, aucun coût n'est caché", pt: "Nenhum serviço é esquecido, nenhum custo está oculto", it: "Nessun servizio viene dimenticato, nessun costo è nascosto" },
    stat: { sq: "60% ulje dështimesh", en: "60% fewer breakdowns", es: "60% menos averías", de: "60% weniger Ausfälle", mk: "60% помалку дефекти" , fr: "60% moins de pannes", pt: "60% menos avarias", it: "60% meno guasti" },
    description: {
      sq: "Planifikoni dhe gjurmoni çdo servisim, ndërrimin e gomave, kontrollin teknik dhe çdo riparim. Merrni alarme automatike bazuar në km ose datë. Të gjitha kostot regjistrohen direkt në shpenzimet e kompanisë.",
      en: "Plan and track every service, tyre change, technical inspection and any repair. Receive automatic alerts based on km or date. All costs are recorded directly in company expenses.",
      es: "Planifique y rastree cada servicio, cambio de neumáticos, inspección técnica y cualquier reparación. Reciba alertas automáticas basadas en km o fecha. Todos los costos se registran directamente en los gastos de la empresa.",
      de: "Planen und verfolgen Sie jeden Service, Reifenwechsel, technische Inspektion und jede Reparatur. Erhalten Sie automatische Alarme basierend auf km oder Datum. Alle Kosten werden direkt in den Firmenausgaben erfasst.",
      mk: "Планирајте и следете секој сервис, промена на гуми, технички преглед и секоја поправка. Добивајте автоматски аларми базирани на km или датум. Сите трошоци се евидентираат директно во трошоците на компанијата.",
    fr: "Planifiez et suivez chaque service, changement de pneus, contrôle technique et réparation. Recevez des alertes automatiques basées sur les km ou la date. Tous les coûts sont enregistrés directement dans les dépenses de l'entreprise.", pt: "Planeie e acompanhe cada serviço, mudança de pneus, inspeção técnica e reparação. Receba alertas automáticos baseados em km ou data. Todos os custos são registados diretamente nas despesas da empresa.", it: "Pianifica e monitora ogni servizio, cambio gomme, ispezione tecnica e riparazione. Ricevi avvisi automatici basati su km o data. Tutti i costi vengono registrati direttamente nelle spese aziendali." },
    benefits: [
      { sq: "Plani i servisimeve sipas km ose datës", en: "Service plan based on km or date", es: "Plan de servicio basado en km o fecha", de: "Serviceplan basierend auf km oder Datum", mk: "План за сервисирање според km или датум" , fr: "Plan de service basé sur les km ou la date", pt: "Plano de serviço baseado em km ou data", it: "Piano di servizio basato su km o data" },
      { sq: "Alarme automatike: ndërrimi gomave, vaj, filtra", en: "Automatic alerts: tyre change, oil, filters", es: "Alertas automáticas: cambio de neumáticos, aceite, filtros", de: "Automatische Alarme: Reifenwechsel, Öl, Filter", mk: "Автоматски аларми: промена на гуми, масло, филтри" , fr: "Alertes automatiques: changement de pneus, huile, filtres", pt: "Alertas automáticos: mudança de pneus, óleo, filtros", it: "Avvisi automatici: cambio gomme, olio, filtri" },
      { sq: "Regjistrim i çdo riparimi me kosto", en: "Registration of every repair with cost", es: "Registro de cada reparación con costo", de: "Erfassung jeder Reparatur mit Kosten", mk: "Евидентирање на секоја поправка со трошок" , fr: "Enregistrement de chaque réparation avec coût", pt: "Registo de cada reparação com custo", it: "Registrazione di ogni riparazione con costo" },
      { sq: "Kontroll teknik dhe afate inspektimi", en: "Technical inspection and inspection deadlines", es: "Inspección técnica y plazos de inspección", de: "Technische Inspektion und Inspektionsfristen", mk: "Технички преглед и рокови за инспекција" , fr: "Contrôle technique et délais d'inspection", pt: "Inspeção técnica e prazos de inspeção", it: "Revisione tecnica e scadenze di ispezione" },
      { sq: "Lidhje direkte me shpenzimet e kompanisë", en: "Direct connection with company expenses", es: "Conexión directa con los gastos de la empresa", de: "Direkte Verbindung mit Firmenausgaben", mk: "Директна врска со трошоците на компанијата" , fr: "Connexion directe avec les dépenses de l'entreprise", pt: "Ligação direta com as despesas da empresa", it: "Collegamento diretto con le spese aziendali" },
      { sq: "Raporte kosto mirëmbajtjeje për çdo automjet", en: "Maintenance cost reports for each vehicle", es: "Informes de costos de mantenimiento para cada vehículo", de: "Wartungskostenberichte für jedes Fahrzeug", mk: "Извештаи за трошоци на одржување за секое возило" , fr: "Rapports de coûts de maintenance pour chaque véhicule", pt: "Relatórios de custos de manutenção para cada veículo", it: "Report dei costi di manutenzione per ogni veicolo" },
    ],
    workflow: [
      { step: "1", sq: "Krijoni planin e servisimit: ndërrim vaji çdo 10,000 km, goma çdo 40,000 km", en: "Create the service plan: oil change every 10,000 km, tyres every 40,000 km", es: "Cree el plan de servicio: cambio de aceite cada 10,000 km, neumáticos cada 40,000 km", de: "Erstellen Sie den Serviceplan: Ölwechsel alle 10.000 km, Reifen alle 40.000 km", mk: "Креирајте план за сервисирање: промена на масло на секои 10.000 km, гуми на секои 40.000 km" , fr: "Créez le plan de service: vidange tous les 10 000 km, pneus tous les 40 000 km", pt: "Crie o plano de serviço: mudança de óleo a cada 10 000 km, pneus a cada 40 000 km", it: "Crea il piano di servizio: cambio olio ogni 10 000 km, gomme ogni 40 000 km" },
      { step: "2", sq: "Sistemi gjurmon km-të dhe dërgon alarme kur afrohet servisi", en: "System tracks km and sends alerts when service approaches", es: "El sistema rastrea km y envía alertas cuando se acerca el servicio", de: "System verfolgt km und sendet Alarme, wenn der Service naht", mk: "Системот ги следи km и испраќа аларми кога се приближува сервисот" , fr: "Le système suit les km et envoie des alertes quand le service approche", pt: "O sistema acompanha os km e envia alertas quando o serviço se aproxima", it: "Il sistema monitora i km e invia avvisi quando il servizio si avvicina" },
      { step: "3", sq: "Regjistroni riparimin: lloji, kosto, servisi, data, çfarë u bë", en: "Record the repair: type, cost, service provider, date, what was done", es: "Registre la reparación: tipo, costo, proveedor de servicio, fecha, qué se hizo", de: "Reparatur erfassen: Art, Kosten, Dienstleister, Datum, was gemacht wurde", mk: "Евидентирајте ја поправката: вид, трошок, сервисер, датум, што е направено" , fr: "Enregistrez la réparation: type, coût, prestataire, date, ce qui a été fait", pt: "Registe a reparação: tipo, custo, prestador de serviço, data, o que foi feito", it: "Registra la riparazione: tipo, costo, fornitore di servizi, data, cosa è stato fatto" },
      { step: "4", sq: "Shpenzimet e mirëmbajtjes lidhen automatikisht me shpenzimet e kompanisë", en: "Maintenance expenses link automatically with company expenses", es: "Los gastos de mantenimiento se vinculan automáticamente con los gastos de la empresa", de: "Wartungskosten werden automatisch mit den Firmenausgaben verknüpft", mk: "Трошоците за одржување автоматски се поврзуваат со трошоците на компанијата" , fr: "Les dépenses de maintenance se lient automatiquement aux dépenses de l'entreprise", pt: "As despesas de manutenção ligam-se automaticamente às despesas da empresa", it: "Le spese di manutenzione si collegano automaticamente alle spese aziendali" },
    ],
    capabilities: [
      { icon: "🔧", title: { sq: "Plan Servisimi", en: "Service Plan", es: "Plan de Servicio", de: "Serviceplan", mk: "План за Сервисирање" , fr: "Plan de service", pt: "Plano de serviço", it: "Piano di servizio" }, desc: { sq: "Caktoni intervale sipas km ose muajve për çdo lloj shërbimi", en: "Set intervals by km or months for every type of service", es: "Establezca intervalos por km o meses para cada tipo de servicio", de: "Intervalle nach km oder Monaten für jede Art von Service festlegen", mk: "Поставете интервали според km или месеци за секој вид сервис" , fr: "Définissez les intervalles par km ou mois pour chaque type de service", pt: "Defina intervalos por km ou meses para cada tipo de serviço", it: "Imposta gli intervalli per km o mesi per ogni tipo di servizio" } },
      { icon: "🔔", title: { sq: "Alarme Automatike", en: "Auto Alerts", es: "Alertas Automáticas", de: "Automatische Alarme", mk: "Автоматски Аларми" , fr: "Alertes automatiques", pt: "Alertas automáticos", it: "Avvisi automatici" }, desc: { sq: "Njoftimet vijnë kur afrohet koha e servisimit bazuar në km ose datë", en: "Notifications come when service time approaches based on km or date", es: "Las notificaciones llegan cuando se acerca el tiempo de servicio basado en km o fecha", de: "Benachrichtigungen kommen, wenn die Servicezeit basierend auf km oder Datum naht", mk: "Известувањата доаѓаат кога се приближува времето за сервис базирано на km или датум" , fr: "Les notifications arrivent quand le moment du service approche par km ou date", pt: "As notificações chegam quando a hora do serviço se aproxima por km ou data", it: "Le notifiche arrivano quando si avvicina il momento del servizio in base a km o data" } },
      { icon: "🛞", title: { sq: "Ndërrim Gomash", en: "Tyre Changes", es: "Cambio de Neumáticos", de: "Reifenwechsel", mk: "Промена на Гуми" , fr: "Changements de pneus", pt: "Mudanças de pneus", it: "Cambi gomme" }, desc: { sq: "Gjurmoni sezonen, km e gomave dhe kur duhet ndërruar", en: "Track season, tyre km and when replacement is needed", es: "Rastree la temporada, km de neumáticos y cuándo se necesita reemplazo", de: "Saison, Reifen-km verfolgen und wann ein Wechsel nötig ist", mk: "Следете ја сезоната, km на гумите и кога е потребна замена" , fr: "Suivez la saison, les km des pneus et quand le remplacement est nécessaire", pt: "Acompanhe a temporada, os km dos pneus e quando é necessária a substituição", it: "Monitora la stagione, i km dei pneumatici e quando è necessaria la sostituzione" } },
      { icon: "📋", title: { sq: "Kontroll Teknik", en: "Technical Inspection", es: "Inspección Técnica", de: "Technische Inspektion", mk: "Технички Преглед" , fr: "Contrôle technique", pt: "Inspeção técnica", it: "Revisione tecnica" }, desc: { sq: "Regjistroni datat e inspektimit dhe alarme para skadencës", en: "Record inspection dates and alerts before expiry", es: "Registre fechas de inspección y alertas antes del vencimiento", de: "Inspektionsdaten erfassen und Alarme vor Ablauf", mk: "Евидентирајте датуми на инспекција и аларми пред истекување" , fr: "Enregistrez les dates d'inspection et les alertes avant expiration", pt: "Registe as datas de inspeção e os alertas antes da expiração", it: "Registra le date di ispezione e gli avvisi prima della scadenza" } },
      { icon: "💶", title: { sq: "Kosto Mirëmbajtje", en: "Maintenance Costs", es: "Costos de Mantenimiento", de: "Wartungskosten", mk: "Трошоци за Одржување" , fr: "Coûts de maintenance", pt: "Custos de manutenção", it: "Costi di manutenzione" }, desc: { sq: "Çdo kosto regjistrohet dhe lidhet me shpenzimet totale të flotës", en: "Every cost recorded and linked with total fleet expenses", es: "Cada costo registrado y vinculado con los gastos totales de la flota", de: "Jeder Kostenpunkt erfasst und mit den Gesamtflottenkosten verknüpft", mk: "Секој трошок евидентиран и поврзан со вкупните трошоци на флотата" , fr: "Chaque coût enregistré et lié aux dépenses totales de la flotte", pt: "Cada custo registado e ligado às despesas totais da frota", it: "Ogni costo registrato e collegato alle spese totali della flotta" } },
      { icon: "📊", title: { sq: "Historik Servisimi", en: "Service History", es: "Historial de Servicio", de: "Servicehistorie", mk: "Историја на Сервисирање" , fr: "Historique des services", pt: "Histórico de serviços", it: "Cronologia dei servizi" }, desc: { sq: "Historiku i plotë i çdo riparimi, ndërrimi dhe kontrolli", en: "Complete history of every repair, replacement and inspection", es: "Historial completo de cada reparación, reemplazo e inspección", de: "Vollständige Historie jeder Reparatur, jedes Austauschs und jeder Inspektion", mk: "Целосна историја на секоја поправка, замена и инспекција" , fr: "Historique complet de chaque réparation, remplacement et inspection", pt: "Histórico completo de cada reparação, substituição e inspeção", it: "Cronologia completa di ogni riparazione, sostituzione e ispezione" } },
    ],
  }} />;
}
