import FeatureDetail from "@/components/FeatureDetail";

const data = {
  category: { sq: "HR & Ekipi", en: "HR & Team", es: "RRHH & Equipo", de: "HR & Team", mk: "HR & Тим", fr: "RH & Équipe", pt: "RH & Equipa", it: "HR & Team" },
  categoryColor: "bg-teal-500",
  title: { sq: "Trajnim & Kuize", en: "Training & Quizzes", es: "Capacitación & Cuestionarios", de: "Schulung & Quizze", mk: "Обука & Квизови" , fr: "Formation & Quiz", pt: "Formação & Questionários", it: "Formazione & Quiz" },
  tagline: { sq: "Trajnoni ekipin tuaj drejtpërdrejt në platformë", en: "Train your team directly in the platform", es: "Capacite a su equipo directamente en la plataforma", de: "Schulen Sie Ihr Team direkt auf der Plattform", mk: "Обучете го вашиот тим директно на платформата" , fr: "Formez votre équipe directement dans la plateforme", pt: "Treine a sua equipa diretamente na plataforma", it: "Forma il tuo team direttamente nella piattaforma" },
  stat: { sq: "100% ekip i trajnuar", en: "100% trained team", es: "100% equipo capacitado", de: "100% geschultes Team", mk: "100% обучен тим" , fr: "100% d'équipe formée", pt: "100% da equipa formada", it: "100% del team formato" },
  description: {
    sq: "Krijoni programe trajnimi me kuize, testime dhe certifikata dixhitale për çdo punonjës. Gjurmoni progresin e trajnimit dhe siguroni që ekipi juaj është gjithmonë i përgatitur. Materialet e trajnimit ruhen në platformë dhe janë të aksesueshme nga çdo pajisje.",
    en: "Create training programs with quizzes, tests and digital certificates for each employee. Track training progress and ensure your team is always prepared. Training materials are stored on the platform and accessible from any device.",
    es: "Cree programas de capacitación con cuestionarios, pruebas y certificados digitales para cada empleado. Rastree el progreso de la capacitación y asegúrese de que su equipo esté siempre preparado. Los materiales de capacitación se almacenan en la plataforma y son accesibles desde cualquier dispositivo.",
    de: "Erstellen Sie Schulungsprogramme mit Quizzen, Tests und digitalen Zertifikaten für jeden Mitarbeiter. Verfolgen Sie den Schulungsfortschritt und stellen Sie sicher, dass Ihr Team immer vorbereitet ist. Schulungsmaterialien werden auf der Plattform gespeichert und sind von jedem Gerät aus zugänglich.",
    mk: "Креирајте програми за обука со квизови, тестови и дигитални сертификати за секој вработен. Следете го напредокот на обуката и осигурајте дека вашиот тим е секогаш подготвен. Материјалите за обука се чуваат на платформата и се достапни од секој уред.",
  fr: "Créez des programmes de formation avec quiz, tests et certificats numériques pour chaque employé. Suivez la progression de la formation et assurez-vous que votre équipe est toujours préparée. Les matériaux sont stockés sur la plateforme et accessibles depuis n'importe quel appareil.", pt: "Crie programas de formação com questionários, testes e certificados digitais para cada funcionário. Acompanhe o progresso da formação e garanta que a sua equipa está sempre preparada. Os materiais são armazenados na plataforma e acessíveis de qualquer dispositivo.", it: "Crea programmi di formazione con quiz, test e certificati digitali per ogni dipendente. Monitora i progressi della formazione e assicurati che il tuo team sia sempre preparato. I materiali sono archiviati sulla piattaforma e accessibili da qualsiasi dispositivo." },
  benefits: [
    { sq: "Kuize dhe testime interaktive", en: "Interactive quizzes and tests", es: "Cuestionarios y pruebas interactivas", de: "Interaktive Quizze und Tests", mk: "Интерактивни квизови и тестови" , fr: "Quiz et tests interactifs", pt: "Questionários e testes interativos", it: "Quiz e test interattivi" },
    { sq: "Certifikata dixhitale pas kalimit të provimit", en: "Digital certificates after passing the test", es: "Certificados digitales tras aprobar la prueba", de: "Digitale Zertifikate nach Bestehen des Tests", mk: "Дигитални сертификати по полагање на тестот" , fr: "Certificats numériques après réussite du test", pt: "Certificados digitais após aprovação no teste", it: "Certificati digitali dopo aver superato il test" },
    { sq: "Programe trajnimi me module të ndryshme", en: "Training programs with different modules", es: "Programas de capacitación con diferentes módulos", de: "Schulungsprogramme mit verschiedenen Modulen", mk: "Програми за обука со различни модули" , fr: "Programmes de formation avec différents modules", pt: "Programas de formação com diferentes módulos", it: "Programmi di formazione con diversi moduli" },
    { sq: "Gjurmim i progresit të çdo punonjësi", en: "Progress tracking for each employee", es: "Seguimiento del progreso de cada empleado", de: "Fortschrittsverfolgung für jeden Mitarbeiter", mk: "Следење на напредокот на секој вработен" , fr: "Suivi de la progression pour chaque employé", pt: "Rastreamento de progresso para cada funcionário", it: "Monitoraggio dei progressi per ogni dipendente" },
    { sq: "Material trajnimi: video, PDF, artikuj", en: "Training materials: video, PDF, articles", es: "Materiales de capacitación: video, PDF, artículos", de: "Schulungsmaterialien: Video, PDF, Artikel", mk: "Материјали за обука: видео, PDF, статии" , fr: "Matériaux de formation: vidéo, PDF, articles", pt: "Materiais de formação: vídeo, PDF, artigos", it: "Materiali di formazione: video, PDF, articoli" },
    { sq: "Raporte detajuara të trajnimit të ekipit", en: "Detailed team training reports", es: "Informes detallados de capacitación del equipo", de: "Detaillierte Team-Schulungsberichte", mk: "Детални извештаи за обука на тимот" , fr: "Rapports détaillés de formation de l'équipe", pt: "Relatórios detalhados de formação da equipa", it: "Report dettagliati sulla formazione del team" },
  ],
  workflow: [
    { step: "1", sq: "Krijoni programin e trajnimit me titull, përshkrim dhe modulet e nevojshme", en: "Create the training program with title, description and required modules", es: "Cree el programa de capacitación con título, descripción y módulos requeridos", de: "Erstellen Sie das Schulungsprogramm mit Titel, Beschreibung und erforderlichen Modulen", mk: "Креирајте ја програмата за обука со наслов, опис и потребни модули" , fr: "Créez le programme de formation avec titre, description et modules requis", pt: "Crie o programa de formação com título, descrição e módulos obrigatórios", it: "Crea il programma di formazione con titolo, descrizione e moduli richiesti" },
    { step: "2", sq: "Ngarkoni materialet: video, PDF, artikuj — dhe krijoni kuizet me pyetje", en: "Upload materials: video, PDF, articles — and create quizzes with questions", es: "Cargue materiales: video, PDF, artículos — y cree cuestionarios con preguntas", de: "Materialien hochladen: Video, PDF, Artikel — und Quizze mit Fragen erstellen", mk: "Прикачете материјали: видео, PDF, статии — и креирајте квизови со прашања" , fr: "Téléchargez des matériaux: vidéo, PDF, articles — et créez des quiz avec des questions", pt: "Carregue materiais: vídeo, PDF, artigos — e crie questionários com perguntas", it: "Carica materiali: video, PDF, articoli — e crea quiz con domande" },
    { step: "3", sq: "Caktoni trajnimin te punonjësit ose ekipet specifike", en: "Assign the training to specific employees or teams", es: "Asigne la capacitación a empleados o equipos específicos", de: "Weisen Sie die Schulung bestimmten Mitarbeitern oder Teams zu", mk: "Доделете ја обуката на одредени вработени или тимови" , fr: "Assignez la formation à des employés ou équipes spécifiques", pt: "Atribua a formação a funcionários ou equipas específicos", it: "Assegna la formazione a dipendenti o team specifici" },
    { step: "4", sq: "Punonjësit studiojnë materialet dhe plotësojnë kuizet nga telefoni ose PC", en: "Employees study materials and complete quizzes from phone or PC", es: "Los empleados estudian materiales y completan cuestionarios desde teléfono o PC", de: "Mitarbeiter studieren Materialien und absolvieren Quizze vom Telefon oder PC", mk: "Вработените ги изучуваат материјалите и ги пополнуваат квизовите од телефон или PC" , fr: "Les employés étudient les matériaux et complètent les quiz depuis téléphone ou PC", pt: "Os funcionários estudam materiais e completam questionários do telemóvel ou PC", it: "I dipendenti studiano i materiali e completano i quiz dal telefono o PC" },
    { step: "5", sq: "Pas kalimit të provimit, certifikata dixhitale gjenerohet automatikisht", en: "After passing the test, the digital certificate is generated automatically", es: "Tras aprobar la prueba, el certificado digital se genera automáticamente", de: "Nach Bestehen des Tests wird das digitale Zertifikat automatisch generiert", mk: "По полагање на тестот, дигиталниот сертификат се генерира автоматски" , fr: "Après réussite du test, le certificat numérique est généré automatiquement", pt: "Após aprovação no teste, o certificado digital é gerado automaticamente", it: "Dopo aver superato il test, il certificato digitale viene generato automaticamente" },
  ],
  capabilities: [
    { icon: "📝", title: { sq: "Kuize Interaktive", en: "Interactive Quizzes", es: "Cuestionarios Interactivos", de: "Interaktive Quizze", mk: "Интерактивни Квизови" , fr: "Quiz interactifs", pt: "Questionários interativos", it: "Quiz interattivi" }, desc: { sq: "Krijoni pyetje me zgjedhje, tekst ose pikë — me rezultate automatike", en: "Create multiple choice, text or point questions — with auto scoring", es: "Cree preguntas de opción múltiple, texto o puntos — con puntuación automática", de: "Multiple-Choice-, Text- oder Punktfragen erstellen — mit automatischer Bewertung", mk: "Креирајте прашања со избор, текст или поени — со автоматско оценување" , fr: "Créez des questions à choix multiples, texte ou points — avec notation automatique", pt: "Crie questões de escolha múltipla, texto ou pontos — com pontuação automática", it: "Crea domande a scelta multipla, testo o punti — con punteggio automatico" } },
    { icon: "🎓", title: { sq: "Certifikata Dixhitale", en: "Digital Certificates", es: "Certificados Digitales", de: "Digitale Zertifikate", mk: "Дигитални Сертификати" , fr: "Certificats numériques", pt: "Certificados digitais", it: "Certificati digitali" }, desc: { sq: "Certifikata e personalizuar me logon tuaj gjenerohet pas kalimit të provimit", en: "Customized certificate with your logo generated after passing the test", es: "Certificado personalizado con su logo generado tras aprobar la prueba", de: "Personalisiertes Zertifikat mit Ihrem Logo wird nach Bestehen des Tests generiert", mk: "Персонализиран сертификат со вашето лого се генерира по полагање на тестот" , fr: "Certificat personnalisé avec votre logo généré après réussite du test", pt: "Certificado personalizado com o seu logótipo gerado após aprovação no teste", it: "Certificato personalizzato con il tuo logo generato dopo aver superato il test" } },
    { icon: "📹", title: { sq: "Material Multimediale", en: "Multimedia Materials", es: "Materiales Multimedia", de: "Multimedia-Materialien", mk: "Мултимедијални Материјали" , fr: "Matériaux multimédias", pt: "Materiais multimédia", it: "Materiali multimediali" }, desc: { sq: "Ngarkoni video, PDF, artikuj dhe prezantime si material trajnimi", en: "Upload video, PDF, articles and presentations as training material", es: "Cargue video, PDF, artículos y presentaciones como material de capacitación", de: "Video, PDF, Artikel und Präsentationen als Schulungsmaterial hochladen", mk: "Прикачете видео, PDF, статии и презентации како материјал за обука" , fr: "Téléchargez vidéo, PDF, articles et présentations comme matériel de formation", pt: "Carregue vídeo, PDF, artigos e apresentações como material de formação", it: "Carica video, PDF, articoli e presentazioni come materiale di formazione" } },
    { icon: "📊", title: { sq: "Gjurmim Progresit", en: "Progress Tracking", es: "Seguimiento del Progreso", de: "Fortschrittsverfolgung", mk: "Следење на Напредок" , fr: "Suivi des progrès", pt: "Rastreamento de progresso", it: "Monitoraggio dei progressi" }, desc: { sq: "Shikoni kush e ka përfunduar trajnimin, rezultatet dhe kohën", en: "See who completed training, results and time spent", es: "Vea quién completó la capacitación, resultados y tiempo invertido", de: "Sehen Sie, wer die Schulung abgeschlossen hat, Ergebnisse und aufgewendete Zeit", mk: "Видете кој ја завршил обуката, резултатите и потрошеното време" , fr: "Voir qui a terminé la formation, les résultats et le temps passé", pt: "Ver quem concluiu a formação, os resultados e o tempo gasto", it: "Vedere chi ha completato la formazione, i risultati e il tempo trascorso" } },
    { icon: "👥", title: { sq: "Caktim Ekipor", en: "Team Assignment", es: "Asignación de Equipo", de: "Teamzuweisung", mk: "Тимско Доделување" , fr: "Affectation de l'équipe", pt: "Atribuição de equipa", it: "Assegnazione del team" }, desc: { sq: "Caktoni trajnime specifike për departamente, pozita ose individë", en: "Assign specific training to departments, positions or individuals", es: "Asigne capacitación específica a departamentos, posiciones o individuos", de: "Weisen Sie bestimmte Schulungen Abteilungen, Positionen oder Einzelpersonen zu", mk: "Доделете специфична обука на одделенија, позиции или поединци" , fr: "Assignez une formation spécifique aux départements, postes ou individus", pt: "Atribua formação específica a departamentos, cargos ou indivíduos", it: "Assegna formazione specifica a dipartimenti, posizioni o individui" } },
    { icon: "🔄", title: { sq: "Ritrajnim Automatik", en: "Auto Retraining", es: "Recapacitación Automática", de: "Automatische Nachschulung", mk: "Автоматска Преобука" , fr: "Formation automatique", pt: "Formação automática", it: "Riaddestramento automatico" }, desc: { sq: "Caktoni afate skadimi dhe ritrajnim automatik kur certifikata skadon", en: "Set expiry dates and auto retraining when certificate expires", es: "Establezca fechas de vencimiento y recapacitación automática cuando el certificado expire", de: "Verfallsdaten und automatische Nachschulung bei Zertifikatsablauf festlegen", mk: "Поставете рокови на истекување и автоматска преобука кога сертификатот истекува" , fr: "Définissez des dates d'expiration et formation automatique à l'expiration du certificat", pt: "Defina datas de expiração e formação automática quando o certificado expirar", it: "Imposta date di scadenza e riaddestramento automatico quando il certificato scade" } },
  ],
};

export default function FeatureTraining() {
  return <FeatureDetail data={data} />;
}
