import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureVendors() {
  return <FeatureDetail data={{
    category: { sq: "Operacione", en: "Operations", es: "Operaciones", de: "Betrieb", mk: "Операции", fr: "Opérations", pt: "Operações", it: "Operazioni" },
    categoryColor: "bg-orange-500",
    title: { sq: "Menaxhim Furnitorësh", en: "Vendor Management", es: "Gestión de Proveedores", de: "Lieferantenverwaltung", mk: "Управување со Добавувачи" , fr: "Gestion des fournisseurs", pt: "Gestão de fornecedores", it: "Gestione fornitori" },
    tagline: { sq: "Organizoni furnitorët dhe blerjet pa kaos", en: "Organize vendors and purchases without chaos", es: "Organice proveedores y compras sin caos", de: "Organisieren Sie Lieferanten und Einkäufe ohne Chaos", mk: "Организирајте добавувачи и набавки без хаос" , fr: "Organisez fournisseurs et achats sans chaos", pt: "Organize fornecedores e compras sem caos", it: "Organizza fornitori e acquisti senza caos" },
    stat: { sq: "20% ulje kostosh", en: "20% cost reduction", es: "20% reducción de costos", de: "20% Kostenreduzierung", mk: "20% намалување на трошоци" , fr: "20% de réduction des coûts", pt: "20% de redução de custos", it: "20% di riduzione dei costi" },
    description: {
      sq: "Gjurmoni furnitorët, porositë e blerjes dhe performancën e tyre. Negocioni me të dhëna reale dhe zgjidhni furnitorët më të mirë.",
      en: "Track vendors, purchase orders and their performance. Negotiate with real data and choose the best vendors.",
      es: "Rastree proveedores, órdenes de compra y su rendimiento. Negocie con datos reales y elija los mejores proveedores.",
      de: "Verfolgen Sie Lieferanten, Bestellungen und deren Leistung. Verhandeln Sie mit realen Daten und wählen Sie die besten Lieferanten.",
      mk: "Следете добавувачи, нарачки за набавка и нивните перформанси. Преговарајте со реални податоци и изберете ги најдобрите добавувачи.",
    fr: "Suivez les fournisseurs, bons de commande et leurs performances. Négociez avec des données réelles et choisissez les meilleurs fournisseurs.", pt: "Acompanhe fornecedores, ordens de compra e o seu desempenho. Negoceie com dados reais e escolha os melhores fornecedores.", it: "Monitora fornitori, ordini di acquisto e le loro prestazioni. Negozia con dati reali e scegli i migliori fornitori." },
    benefits: [
      { sq: "Katalog furnitorësh me rating dhe vlerësim", en: "Vendor catalog with rating and evaluation", es: "Catálogo de proveedores con calificación y evaluación", de: "Lieferantenkatalog mit Bewertung und Evaluation", mk: "Каталог на добавувачи со оценка и евалуација" , fr: "Catalogue fournisseurs avec note et évaluation", pt: "Catálogo de fornecedores com classificação e avaliação", it: "Catalogo fornitori con valutazione e rating" },
      { sq: "Menaxhim porosish blerje (PO)", en: "Purchase order management (PO)", es: "Gestión de órdenes de compra (PO)", de: "Bestellungsverwaltung (PO)", mk: "Управување со нарачки за набавка (PO)" , fr: "Gestion des bons de commande (BC)", pt: "Gestão de ordens de compra (OC)", it: "Gestione ordini di acquisto (OA)" },
      { sq: "Krahasim çmimesh mes furnitorëve", en: "Price comparison between vendors", es: "Comparación de precios entre proveedores", de: "Preisvergleich zwischen Lieferanten", mk: "Споредба на цени меѓу добавувачи" , fr: "Comparaison des prix entre fournisseurs", pt: "Comparação de preços entre fornecedores", it: "Confronto prezzi tra fornitori" },
      { sq: "Historiku i blerjieve dhe pagesave", en: "Purchase and payment history", es: "Historial de compras y pagos", de: "Einkaufs- und Zahlungshistorie", mk: "Историја на набавки и плаќања" , fr: "Historique des achats et paiements", pt: "Histórico de compras e pagamentos", it: "Cronologia acquisti e pagamenti" },
      { sq: "Alarme kontratash dhe afatesh", en: "Contract and deadline alerts", es: "Alertas de contratos y plazos", de: "Vertrags- und Fristwarnungen", mk: "Аларми за договори и рокови" , fr: "Alertes de contrat et d'échéance", pt: "Alertas de contrato e prazo", it: "Avvisi di contratto e scadenza" },
    ],
    workflow: [
      { step: "1", sq: "Regjistroni furnitorin: emrin, kontaktin, produktet dhe kushtet", en: "Register the vendor: name, contact, products and terms", es: "Registre al proveedor: nombre, contacto, productos y condiciones", de: "Registrieren Sie den Lieferanten: Name, Kontakt, Produkte und Konditionen", mk: "Регистрирајте го добавувачот: име, контакт, производи и услови" , fr: "Enregistrez le fournisseur: nom, contact, produits et conditions", pt: "Registe o fornecedor: nome, contacto, produtos e condições", it: "Registra il fornitore: nome, contatto, prodotti e condizioni" },
      { step: "2", sq: "Krijoni porosi blerje (PO) me artikujt, sasitë dhe çmimet", en: "Create a purchase order (PO) with items, quantities and prices", es: "Cree una orden de compra (PO) con artículos, cantidades y precios", de: "Erstellen Sie eine Bestellung (PO) mit Artikeln, Mengen und Preisen", mk: "Креирајте нарачка за набавка (PO) со артикли, количини и цени" , fr: "Créez un bon de commande (BC) avec articles, quantités et prix", pt: "Crie uma ordem de compra (OC) com artigos, quantidades e preços", it: "Crea un ordine di acquisto (OA) con articoli, quantità e prezzi" },
      { step: "3", sq: "Krahasoni çmimet mes furnitorëve para porosisë", en: "Compare prices between vendors before ordering", es: "Compare precios entre proveedores antes de ordenar", de: "Vergleichen Sie Preise zwischen Lieferanten vor der Bestellung", mk: "Споредете цени меѓу добавувачи пред нарачка" , fr: "Comparez les prix entre fournisseurs avant de commander", pt: "Compare os preços entre fornecedores antes de encomendar", it: "Confronta i prezzi tra i fornitori prima di ordinare" },
      { step: "4", sq: "Gjurmoni dërgesën, aprovoni pranimin dhe regjistroni pagesën", en: "Track delivery, approve receipt and record payment", es: "Rastree la entrega, apruebe la recepción y registre el pago", de: "Verfolgen Sie die Lieferung, genehmigen Sie den Empfang und erfassen Sie die Zahlung", mk: "Следете ја испораката, одобрете го приемот и евидентирајте го плаќањето" , fr: "Suivez la livraison, approuvez la réception et enregistrez le paiement", pt: "Acompanhe a entrega, aprove a receção e registe o pagamento", it: "Monitora la consegna, approva la ricezione e registra il pagamento" },
    ],
    capabilities: [
      { icon: "📒", title: { sq: "Katalog Furnitorësh", en: "Vendor Catalog", es: "Catálogo de Proveedores", de: "Lieferantenkatalog", mk: "Каталог на Добавувачи" , fr: "Catalogue fournisseurs", pt: "Catálogo de fornecedores", it: "Catalogo fornitori" }, desc: { sq: "Listë e organizuar e furnitorëve me rating, kontakte dhe kushte", en: "Organized vendor list with rating, contacts and terms", es: "Lista organizada de proveedores con calificación, contactos y condiciones", de: "Organisierte Lieferantenliste mit Bewertung, Kontakten und Konditionen", mk: "Организирана листа на добавувачи со оценка, контакти и услови" , fr: "Liste organisée des fournisseurs avec note, contacts et conditions", pt: "Lista organizada de fornecedores com classificação, contactos e condições", it: "Elenco organizzato dei fornitori con valutazione, contatti e condizioni" } },
      { icon: "📦", title: { sq: "Porosi Blerje (PO)", en: "Purchase Orders (PO)", es: "Órdenes de Compra (PO)", de: "Bestellungen (PO)", mk: "Нарачки за Набавка (PO)" , fr: "Bons de commande (BC)", pt: "Ordens de compra (OC)", it: "Ordini di acquisto (OA)" }, desc: { sq: "Krijoni dhe gjurmoni porosite e blerjes me status real-time", en: "Create and track purchase orders with real-time status", es: "Cree y rastree órdenes de compra con estado en tiempo real", de: "Erstellen und verfolgen Sie Bestellungen mit Echtzeit-Status", mk: "Креирајте и следете нарачки за набавка со статус во реално време" , fr: "Créez et suivez les bons de commande avec statut en temps réel", pt: "Crie e acompanhe ordens de compra com estado em tempo real", it: "Crea e monitora gli ordini di acquisto con stato in tempo reale" } },
      { icon: "⚖️", title: { sq: "Krahasim Çmimesh", en: "Price Comparison", es: "Comparación de Precios", de: "Preisvergleich", mk: "Споредба на Цени" , fr: "Comparaison des prix", pt: "Comparação de preços", it: "Confronto prezzi" }, desc: { sq: "Krahasoni çmimet e furnitorëve për të njëjtin produkt", en: "Compare vendor prices for the same product", es: "Compare precios de proveedores para el mismo producto", de: "Vergleichen Sie Lieferantenpreise für dasselbe Produkt", mk: "Споредете цени на добавувачи за ист производ" , fr: "Comparez les prix des fournisseurs pour le même produit", pt: "Compare os preços dos fornecedores para o mesmo produto", it: "Confronta i prezzi dei fornitori per lo stesso prodotto" } },
      { icon: "⭐", title: { sq: "Rating Furnitori", en: "Vendor Rating", es: "Calificación de Proveedores", de: "Lieferantenbewertung", mk: "Оценка на Добавувачи" , fr: "Note du fournisseur", pt: "Classificação do fornecedor", it: "Valutazione del fornitore" }, desc: { sq: "Vlerësoni furnitorët sipas cilësisë, afatit dhe çmimit", en: "Evaluate vendors by quality, deadline and price", es: "Evalúe proveedores por calidad, plazo y precio", de: "Bewerten Sie Lieferanten nach Qualität, Frist und Preis", mk: "Оценете добавувачи по квалитет, рок и цена" , fr: "Évaluez les fournisseurs par qualité, délai et prix", pt: "Avalie os fornecedores por qualidade, prazo e preço", it: "Valuta i fornitori per qualità, scadenza e prezzo" } },
      { icon: "📋", title: { sq: "Historik Blerjesh", en: "Purchase History", es: "Historial de Compras", de: "Einkaufshistorie", mk: "Историја на Набавки" , fr: "Historique des achats", pt: "Histórico de compras", it: "Cronologia acquisti" }, desc: { sq: "Historiku i plotë i çdo blerje, pagese dhe dërgese", en: "Complete history of every purchase, payment and delivery", es: "Historial completo de cada compra, pago y entrega", de: "Vollständige Historie jedes Einkaufs, jeder Zahlung und Lieferung", mk: "Целосна историја на секоја набавка, плаќање и испорака" , fr: "Historique complet de chaque achat, paiement et livraison", pt: "Histórico completo de cada compra, pagamento e entrega", it: "Cronologia completa di ogni acquisto, pagamento e consegna" } },
      { icon: "🔔", title: { sq: "Alarme Kontratash", en: "Contract Alerts", es: "Alertas de Contratos", de: "Vertragswarnungen", mk: "Аларми за Договори" , fr: "Alertes de contrat", pt: "Alertas de contrato", it: "Avvisi di contratto" }, desc: { sq: "Merrni njoftimet para skadimit të kontratave me furnitorë", en: "Receive notifications before vendor contracts expire", es: "Reciba notificaciones antes de que expiren los contratos con proveedores", de: "Erhalten Sie Benachrichtigungen bevor Lieferantenverträge ablaufen", mk: "Добивајте известувања пред истекување на договорите со добавувачи" , fr: "Recevez des notifications avant l'expiration des contrats fournisseurs", pt: "Receba notificações antes da expiração dos contratos dos fornecedores", it: "Ricevi notifiche prima della scadenza dei contratti dei fornitori" } },
    ],
  }} />;
}
