import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureAttendance() {
  return <FeatureDetail data={{
    category: { sq: "HR & Ekipi", en: "HR & Team", es: "RRHH & Equipo", de: "HR & Team", mk: "HR & Тим", fr: "RH & Équipe", pt: "RH & Equipa", it: "HR & Team" },
    categoryColor: "bg-emerald-500",
    title: { sq: "Prezencë & Check‑In Mobile", en: "Attendance & Mobile Check‑In", es: "Asistencia & Check-In Móvil", de: "Anwesenheit & Mobiler Check-In", mk: "Присуство & Мобилен Check-In" , fr: "Présence & Pointage mobile", pt: "Presença & Check-in móvel", it: "Presenze & Check-in mobile" },
    tagline: { sq: "Pa pajisje në zyrë — vetëm telefon dhe GPS", en: "No office equipment — just phone and GPS", es: "Sin equipos de oficina — solo teléfono y GPS", de: "Keine Bürogeräte — nur Telefon und GPS", mk: "Без канцелариска опрема — само телефон и GPS" , fr: "Aucun équipement de bureau — juste un téléphone et GPS", pt: "Sem equipamento de escritório — apenas telemóvel e GPS", it: "Nessuna apparecchiatura d'ufficio — solo telefono e GPS" },
    stat: { sq: "100% saktësi lokacioni", en: "100% location accuracy", es: "100% precisión de ubicación", de: "100% Standortgenauigkeit", mk: "100% точност на локација" , fr: "100% de précision de localisation", pt: "100% de precisão de localização", it: "100% di precisione della posizione" },
    description: {
      sq: "Punonjësit bëjnë check-in dhe check-out direkt nga telefoni me lokacion GPS të saktë — pa karta, pa pajisje të instaluara. Orari i punës, turnet dhe overtime llogariten automatikisht.",
      en: "Employees check in and out directly from their phone with accurate GPS location — no cards, no installed devices. Work hours, shifts and overtime are calculated automatically.",
      es: "Los empleados registran entrada y salida directamente desde su teléfono con ubicación GPS precisa — sin tarjetas, sin dispositivos instalados. Las horas de trabajo, turnos y horas extra se calculan automáticamente.",
      de: "Mitarbeiter checken direkt vom Telefon mit genauem GPS-Standort ein und aus — keine Karten, keine installierten Geräte. Arbeitszeiten, Schichten und Überstunden werden automatisch berechnet.",
      mk: "Вработените се пријавуваат и одјавуваат директно од телефонот со точна GPS локација — без картички, без инсталирани уреди. Работните часови, смените и прекувремената работа се пресметуваат автоматски.",
    fr: "Les employés s'enregistrent depuis leur téléphone avec GPS précis — pas de cartes, pas d'appareils installés. Les heures de travail, équipes et heures supplémentaires sont calculées automatiquement.", pt: "Os funcionários registam a entrada e saída diretamente do telemóvel com GPS preciso — sem cartões, sem dispositivos instalados. As horas de trabalho, turnos e horas extras são calculadas automaticamente.", it: "I dipendenti registrano entrata e uscita dal loro telefono con GPS preciso — niente tessere, niente dispositivi installati. Le ore lavorative, i turni e gli straordinari vengono calcolati automaticamente." },
    benefits: [
      { sq: "Check-in/out nga telefoni me GPS + foto", en: "Check-in/out from phone with GPS + photo", es: "Check-in/out desde el teléfono con GPS + foto", de: "Check-in/out vom Telefon mit GPS + Foto", mk: "Check-in/out од телефон со GPS + фотографија" , fr: "Pointage depuis le téléphone avec GPS + photo", pt: "Registo de entrada/saída do telemóvel com GPS + foto", it: "Registrazione entrata/uscita dal telefono con GPS + foto" },
      { sq: "Pa pajisje në zyrë — zero instalim harduer", en: "No office devices — zero hardware installation", es: "Sin dispositivos de oficina — cero instalación de hardware", de: "Keine Bürogeräte — null Hardwareinstallation", mk: "Без канцелариски уреди — нула хардверска инсталација" , fr: "Aucun appareil de bureau — zéro installation de matériel", pt: "Sem dispositivos de escritório — zero instalação de hardware", it: "Nessun dispositivo in ufficio — zero installazione hardware" },
      { sq: "Llogaritje automatike orësh dhe overtime", en: "Automatic calculation of hours and overtime", es: "Cálculo automático de horas y horas extra", de: "Automatische Berechnung von Stunden und Überstunden", mk: "Автоматско пресметување на часови и прекувремена работа" , fr: "Calcul automatique des heures et heures supplémentaires", pt: "Cálculo automático de horas e horas extras", it: "Calcolo automatico delle ore e degli straordinari" },
      { sq: "Caktim orarit dhe turneve të punës", en: "Work schedule and shift assignment", es: "Asignación de horarios y turnos de trabajo", de: "Arbeitsplan- und Schichtzuweisung", mk: "Распоред на работно време и смени" , fr: "Planning de travail et attribution des équipes", pt: "Horário de trabalho e atribuição de turnos", it: "Orario di lavoro e assegnazione dei turni" },
      { sq: "Raporte të avancuara prezence (ditore/mujore)", en: "Advanced attendance reports (daily/monthly)", es: "Informes avanzados de asistencia (diarios/mensuales)", de: "Erweiterte Anwesenheitsberichte (täglich/monatlich)", mk: "Напредни извештаи за присуство (дневни/месечни)" , fr: "Rapports de présence avancés (quotidiens/mensuels)", pt: "Relatórios de presença avançados (diários/mensais)", it: "Report presenze avanzati (giornalieri/mensili)" },
      { sq: "Eksport automatik për llogaritje page", en: "Automatic export for payroll calculation", es: "Exportación automática para cálculo de nómina", de: "Automatischer Export für Gehaltsabrechnung", mk: "Автоматски извоз за пресметка на плата" , fr: "Export automatique pour le calcul de la paie", pt: "Exportação automática para cálculo de salários", it: "Esportazione automatica per il calcolo degli stipendi" },
    ],
    workflow: [
      { step: "1", sq: "Punonjësi hap aplikacionin dhe shtyp 'Check-In' — GPS dhe foto ruhen", en: "Employee opens the app and taps 'Check-In' — GPS and photo are saved", es: "El empleado abre la app y pulsa 'Check-In' — GPS y foto se guardan", de: "Mitarbeiter öffnet die App und tippt 'Check-In' — GPS und Foto werden gespeichert", mk: "Вработениот ја отвора апликацијата и притиска 'Check-In' — GPS и фотографија се зачувуваат" , fr: "L'employé ouvre l'application et appuie sur 'Pointer' — GPS et photo sont sauvegardés", pt: "O funcionário abre a aplicação e toca em 'Registar' — GPS e foto são guardados", it: "Il dipendente apre l'app e tocca 'Check-In' — GPS e foto vengono salvati" },
      { step: "2", sq: "Sistemi regjistron orën e fillimit dhe lokacionin automatikisht", en: "System records start time and location automatically", es: "El sistema registra la hora de inicio y la ubicación automáticamente", de: "System erfasst Startzeit und Standort automatisch", mk: "Системот го евидентира времето на почеток и локацијата автоматски" , fr: "Le système enregistre l'heure de début et la localisation automatiquement", pt: "O sistema regista automaticamente a hora de início e a localização", it: "Il sistema registra automaticamente l'ora di inizio e la posizione" },
      { step: "3", sq: "Në fund të ditës, punonjësi bën 'Check-Out' — orët llogariten", en: "At end of day, employee does 'Check-Out' — hours are calculated", es: "Al final del día, el empleado hace 'Check-Out' — las horas se calculan", de: "Am Ende des Tages macht der Mitarbeiter 'Check-Out' — Stunden werden berechnet", mk: "На крајот на денот, вработениот прави 'Check-Out' — часовите се пресметуваат" , fr: "En fin de journée, l'employé fait 'Check-Out' — les heures sont calculées", pt: "No final do dia, o funcionário faz 'Check-Out' — as horas são calculadas", it: "A fine giornata, il dipendente fa 'Check-Out' — le ore vengono calcolate" },
      { step: "4", sq: "Menaxheri shikon raportin ditor: kush erdhi, kush vonoi, orë totale", en: "Manager views daily report: who came, who was late, total hours", es: "El gerente ve el informe diario: quién vino, quién llegó tarde, horas totales", de: "Manager sieht Tagesbericht: wer kam, wer zu spät war, Gesamtstunden", mk: "Менаџерот го гледа дневниот извештај: кој дошол, кој доцнел, вкупни часови" , fr: "Le manager consulte le rapport quotidien: qui est venu, qui était en retard, total des heures", pt: "O gestor visualiza o relatório diário: quem veio, quem chegou tarde, total de horas", it: "Il manager visualizza il report giornaliero: chi è venuto, chi è arrivato tardi, totale ore" },
      { step: "5", sq: "Në fund të muajit, eksportoni orët direkt për llogaritjen e pagës", en: "At month end, export hours directly for payroll calculation", es: "Al final del mes, exporte las horas directamente para el cálculo de nómina", de: "Am Monatsende exportieren Sie die Stunden direkt für die Gehaltsabrechnung", mk: "На крајот на месецот, извезете ги часовите директно за пресметка на плата" , fr: "En fin de mois, exportez les heures directement pour le calcul de la paie", pt: "No final do mês, exporte as horas diretamente para o cálculo de salários", it: "A fine mese, esporta le ore direttamente per il calcolo degli stipendi" },
    ],
    capabilities: [
      { icon: "📍", title: { sq: "GPS Check-In", en: "GPS Check-In", es: "Check-In GPS", de: "GPS Check-In", mk: "GPS Check-In" , fr: "Pointage GPS", pt: "Check-in GPS", it: "Check-in GPS" }, desc: { sq: "Lokacion i saktë GPS kur punonjësi bën check-in — pa mundësi mashtrimi", en: "Accurate GPS location when employee checks in — no fraud possible", es: "Ubicación GPS precisa cuando el empleado registra entrada — sin posibilidad de fraude", de: "Genauer GPS-Standort beim Check-in des Mitarbeiters — kein Betrug möglich", mk: "Точна GPS локација кога вработениот се пријавува — без можност за измама" , fr: "Localisation GPS précise lors du pointage de l'employé — aucune fraude possible", pt: "Localização GPS precisa quando o funcionário regista a entrada — sem fraude possível", it: "Posizione GPS accurata quando il dipendente fa check-in — nessuna frode possibile" } },
      { icon: "📸", title: { sq: "Foto Verifikimi", en: "Photo Verification", es: "Verificación con Foto", de: "Fotoverifizierung", mk: "Фото Верификација" , fr: "Vérification photo", pt: "Verificação por foto", it: "Verifica fotografica" }, desc: { sq: "Foto selfie automatike gjatë check-in për verifikim identiteti", en: "Automatic selfie photo during check-in for identity verification", es: "Foto selfie automática durante el check-in para verificación de identidad", de: "Automatisches Selfie-Foto beim Check-in zur Identitätsüberprüfung", mk: "Автоматска селфи фотографија при пријавување за верификација на идентитет" , fr: "Photo selfie automatique lors du pointage pour la vérification d'identité", pt: "Foto selfie automática durante o check-in para verificação de identidade", it: "Foto selfie automatica durante il check-in per la verifica dell'identità" } },
      { icon: "⏰", title: { sq: "Llogaritje Orësh", en: "Hours Calculation", es: "Cálculo de Horas", de: "Stundenberechnung", mk: "Пресметка на Часови" , fr: "Calcul des heures", pt: "Cálculo de horas", it: "Calcolo delle ore" }, desc: { sq: "Orë normale, overtime, vonesa — gjithçka llogaritet automatikisht", en: "Normal hours, overtime, lateness — everything calculated automatically", es: "Horas normales, horas extra, retrasos — todo calculado automáticamente", de: "Normalstunden, Überstunden, Verspätungen — alles automatisch berechnet", mk: "Нормални часови, прекувремена работа, доцнење — сè се пресметува автоматски" , fr: "Heures normales, heures supplémentaires, retard — tout calculé automatiquement", pt: "Horas normais, horas extras, atraso — tudo calculado automaticamente", it: "Ore normali, straordinari, ritardi — tutto calcolato automaticamente" } },
      { icon: "📋", title: { sq: "Turne Pune", en: "Work Shifts", es: "Turnos de Trabajo", de: "Arbeitsschichten", mk: "Работни Смени" , fr: "Équipes de travail", pt: "Turnos de trabalho", it: "Turni di lavoro" }, desc: { sq: "Caktoni turne: mëngjes, mbasdite, natë — me rotacion automatik", en: "Assign shifts: morning, afternoon, night — with automatic rotation", es: "Asigne turnos: mañana, tarde, noche — con rotación automática", de: "Schichten zuweisen: Morgen, Nachmittag, Nacht — mit automatischer Rotation", mk: "Доделете смени: утро, попладне, ноќ — со автоматска ротација" , fr: "Attribuez des équipes: matin, après-midi, nuit — avec rotation automatique", pt: "Atribua turnos: manhã, tarde, noite — com rotação automática", it: "Assegna turni: mattina, pomeriggio, notte — con rotazione automatica" } },
      { icon: "📊", title: { sq: "Raporte Prezence", en: "Attendance Reports", es: "Informes de Asistencia", de: "Anwesenheitsberichte", mk: "Извештаи за Присуство" , fr: "Rapports de présence", pt: "Relatórios de presença", it: "Report delle presenze" }, desc: { sq: "Raporte ditore dhe mujore me grafiqe, vonesa dhe mungesa", en: "Daily and monthly reports with charts, lateness and absences", es: "Informes diarios y mensuales con gráficos, retrasos y ausencias", de: "Tägliche und monatliche Berichte mit Diagrammen, Verspätungen und Abwesenheiten", mk: "Дневни и месечни извештаи со графикони, доцнења и отсуства" , fr: "Rapports quotidiens et mensuels avec graphiques, retards et absences", pt: "Relatórios diários e mensais com gráficos, atrasos e ausências", it: "Report giornalieri e mensili con grafici, ritardi e assenze" } },
      { icon: "💰", title: { sq: "Eksport Payroll", en: "Payroll Export", es: "Exportación de Nómina", de: "Gehaltsexport", mk: "Извоз на Плата" , fr: "Export de paie", pt: "Exportação de salários", it: "Esportazione stipendi" }, desc: { sq: "Eksportoni orët direkt për modulin e pagave — zero hyrje manuale", en: "Export hours directly to payroll module — zero manual entry", es: "Exporte horas directamente al módulo de nómina — cero entrada manual", de: "Stunden direkt in das Gehaltsmodul exportieren — null manuelle Eingabe", mk: "Извезете часови директно во модулот за плати — нула рачно внесување" , fr: "Exportez les heures directement vers le module de paie — zéro saisie manuelle", pt: "Exporte horas diretamente para o módulo de salários — zero entrada manual", it: "Esporta le ore direttamente nel modulo stipendi — zero inserimento manuale" } },
    ],
  }} />;
}
