import FeatureDetail from "@/components/FeatureDetail";

const data = {
  category: { sq: "Financë", en: "Finance", es: "Finanzas", de: "Finanzen", mk: "Финансии" },
  categoryColor: "bg-amber-500",
  title: { sq: "Kartelat e Blerësit", en: "Buyer Cards", es: "Tarjetas de Comprador", de: "Käuferkarten", mk: "Картички на Купувач" },
  tagline: { sq: "Menaxhoni kartelat dhe historikun e blerësve", en: "Manage buyer cards and purchase history", es: "Gestione tarjetas de compradores e historial de compras", de: "Käuferkarten und Kaufhistorie verwalten", mk: "Управувајте со картичките и историјата на купувачите" },
  stat: { sq: "100% transparencë blerësi", en: "100% buyer transparency", es: "100% transparencia del comprador", de: "100% Käufertransparenz", mk: "100% транспарентност на купувач" },
  description: {
    sq: "Krijoni kartela dixhitale për çdo blerës me historikun e plotë të blerjeve, pagesave dhe borxheve. Çdo blerës ka profilin e vet me saldo aktuale, limitet e kreditit dhe statistikat e blerjeve. Ju gjithmonë e dini saktësisht ku qëndroni me çdo klient.",
    en: "Create digital cards for each buyer with complete purchase, payment and debt history. Each buyer has their own profile with current balance, credit limits and purchase statistics. You always know exactly where you stand with each client.",
    es: "Cree tarjetas digitales para cada comprador con historial completo de compras, pagos y deudas. Cada comprador tiene su propio perfil con saldo actual, límites de crédito y estadísticas de compras. Usted siempre sabe exactamente dónde se encuentra con cada cliente.",
    de: "Erstellen Sie digitale Karten für jeden Käufer mit vollständiger Kauf-, Zahlungs- und Schuldenhistorie. Jeder Käufer hat sein eigenes Profil mit aktuellem Saldo, Kreditlimits und Kaufstatistiken. Sie wissen immer genau, wo Sie mit jedem Kunden stehen.",
    mk: "Креирајте дигитални картички за секој купувач со целосна историја на купувања, плаќања и долгови. Секој купувач има свој профил со тековно салдо, кредитни лимити и статистики на купувања. Секогаш точно знаете каде стоите со секој клиент.",
  },
  benefits: [
    { sq: "Kartela dixhitale me saldo dhe historik blerje", en: "Digital cards with balance and purchase history", es: "Tarjetas digitales con saldo e historial de compras", de: "Digitale Karten mit Saldo und Kaufhistorie", mk: "Дигитални картички со салдо и историја на купувања" },
    { sq: "Limit krediti dhe njoftim automatik", en: "Credit limit and automatic notification", es: "Límite de crédito y notificación automática", de: "Kreditlimit und automatische Benachrichtigung", mk: "Кредитен лимит и автоматско известување" },
    { sq: "Gjurmim i pagesave dhe borxheve të blerësit", en: "Tracking buyer payments and debts", es: "Seguimiento de pagos y deudas del comprador", de: "Verfolgung von Käuferzahlungen und Schulden", mk: "Следење на плаќања и долгови на купувачот" },
    { sq: "Raport detajuar i çdo blerësi", en: "Detailed report for each buyer", es: "Informe detallado de cada comprador", de: "Detaillierter Bericht für jeden Käufer", mk: "Детален извештај за секој купувач" },
    { sq: "Kategorizim sipas llojit të blerësit", en: "Categorization by buyer type", es: "Categorización por tipo de comprador", de: "Kategorisierung nach Käufertyp", mk: "Категоризација според тип на купувач" },
    { sq: "Eksport i listës së blerësve (PDF/Excel)", en: "Export buyer list (PDF/Excel)", es: "Exportar lista de compradores (PDF/Excel)", de: "Käuferliste exportieren (PDF/Excel)", mk: "Извоз на листа на купувачи (PDF/Excel)" },
  ],
  workflow: [
    { step: "1", sq: "Shtoni blerësin e ri me të dhënat bazë: emër, kontakt, lloj biznesi", en: "Add the new buyer with basic data: name, contact, business type", es: "Agregue al nuevo comprador con datos básicos: nombre, contacto, tipo de negocio", de: "Neuen Käufer mit Basisdaten hinzufügen: Name, Kontakt, Geschäftstyp", mk: "Додајте го новиот купувач со основни податоци: име, контакт, тип на бизнис" },
    { step: "2", sq: "Caktoni limitin e kreditit dhe kushtet e pagesës për blerësin", en: "Set the credit limit and payment terms for the buyer", es: "Establezca el límite de crédito y los términos de pago para el comprador", de: "Kreditlimit und Zahlungsbedingungen für den Käufer festlegen", mk: "Поставете го кредитниот лимит и условите за плаќање за купувачот" },
    { step: "3", sq: "Çdo blerje dhe pagesë regjistrohet automatikisht në kartelën e blerësit", en: "Every purchase and payment is automatically recorded on the buyer's card", es: "Cada compra y pago se registra automáticamente en la tarjeta del comprador", de: "Jeder Kauf und jede Zahlung wird automatisch auf der Käuferkarte erfasst", mk: "Секое купување и плаќање автоматски се евидентира на картичката на купувачот" },
    { step: "4", sq: "Merrni alarme kur blerësi i afrohet limitit ose ka borxh të vonuar", en: "Get alerts when the buyer approaches the limit or has overdue debt", es: "Reciba alertas cuando el comprador se acerque al límite o tenga deuda vencida", de: "Erhalten Sie Alarme, wenn der Käufer sich dem Limit nähert oder überfällige Schulden hat", mk: "Добијте аларми кога купувачот се приближува до лимитот или има достасан долг" },
    { step: "5", sq: "Gjeneroni raporte për blerësit — saldo, historik blerje, profitabilitet", en: "Generate reports for buyers — balance, purchase history, profitability", es: "Genere informes para compradores — saldo, historial de compras, rentabilidad", de: "Berichte für Käufer generieren — Saldo, Kaufhistorie, Rentabilität", mk: "Генерирајте извештаи за купувачите — салдо, историја на купувања, профитабилност" },
  ],
  capabilities: [
    { icon: "💳", title: { sq: "Kartela Dixhitale", en: "Digital Cards", es: "Tarjetas Digitales", de: "Digitale Karten", mk: "Дигитални Картички" }, desc: { sq: "Profil i plotë për çdo blerës me të gjitha të dhënat financiare në një vend", en: "Complete profile for each buyer with all financial data in one place", es: "Perfil completo para cada comprador con todos los datos financieros en un solo lugar", de: "Vollständiges Profil für jeden Käufer mit allen Finanzdaten an einem Ort", mk: "Целосен профил за секој купувач со сите финансиски податоци на едно место" } },
    { icon: "📈", title: { sq: "Saldo në Kohë Reale", en: "Real-time Balance", es: "Saldo en Tiempo Real", de: "Echtzeit-Saldo", mk: "Салдо во Реално Време" }, desc: { sq: "Shikoni saldot aktuale, pagesat e pritshme dhe borxhet e çdo blerësi", en: "View current balances, expected payments and debts for each buyer", es: "Vea saldos actuales, pagos esperados y deudas de cada comprador", de: "Aktuelle Salden, erwartete Zahlungen und Schulden für jeden Käufer einsehen", mk: "Погледнете тековни салда, очекувани плаќања и долгови за секој купувач" } },
    { icon: "⚠️", title: { sq: "Alarme Krediti", en: "Credit Alerts", es: "Alertas de Crédito", de: "Kreditalarme", mk: "Кредитни Аларми" }, desc: { sq: "Njoftim automatik kur blerësi i afrohet ose e kalon limitin e kreditit", en: "Auto notification when buyer approaches or exceeds credit limit", es: "Notificación automática cuando el comprador se acerca o excede el límite de crédito", de: "Automatische Benachrichtigung, wenn der Käufer sich dem Kreditlimit nähert oder es überschreitet", mk: "Автоматско известување кога купувачот се приближува или го надминува кредитниот лимит" } },
    { icon: "📋", title: { sq: "Historik i Plotë", en: "Complete History", es: "Historial Completo", de: "Vollständige Historie", mk: "Целосна Историја" }, desc: { sq: "Çdo blerje, pagesë dhe kthim i regjistruar me data dhe detaje", en: "Every purchase, payment and return recorded with dates and details", es: "Cada compra, pago y devolución registrada con fechas y detalles", de: "Jeder Kauf, jede Zahlung und Rückgabe mit Daten und Details erfasst", mk: "Секое купување, плаќање и враќање евидентирано со датуми и детали" } },
    { icon: "🏷️", title: { sq: "Kategorizim", en: "Categorization", es: "Categorización", de: "Kategorisierung", mk: "Категоризација" }, desc: { sq: "Gruponi blerësit sipas llojit, rajonit ose volumit të blerjeve", en: "Group buyers by type, region or purchase volume", es: "Agrupe compradores por tipo, región o volumen de compras", de: "Käufer nach Typ, Region oder Kaufvolumen gruppieren", mk: "Групирајте купувачи според тип, регион или обем на купувања" } },
    { icon: "📊", title: { sq: "Raporte Blerësi", en: "Buyer Reports", es: "Informes de Comprador", de: "Käuferberichte", mk: "Извештаи за Купувачи" }, desc: { sq: "Analiza detajuara: blerësi më profitabil, borxhet, trendet e blerjeve", en: "Detailed analysis: most profitable buyer, debts, purchase trends", es: "Análisis detallado: comprador más rentable, deudas, tendencias de compra", de: "Detaillierte Analyse: profitabelster Käufer, Schulden, Kauftrends", mk: "Детална анализа: најпрофитабилен купувач, долгови, трендови на купување" } },
  ],
};

export default function FeatureBuyerCards() {
  return <FeatureDetail data={data} />;
}
