import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureFleet() {
  return <FeatureDetail data={{
    category: { sq: "Flotë", en: "Fleet", es: "Flota", de: "Flotte", mk: "Флота", fr: "Flotte", pt: "Frota", it: "Flotta" },
    categoryColor: "bg-amber-500",
    title: { sq: "Motorpool & Flotë Makinash", en: "Motorpool & Fleet Management", es: "Parque Automotor & Gestión de Flota", de: "Fuhrpark & Flottenmanagement", mk: "Возен Парк & Управување со Флота" , fr: "Gestion du parc automobile", pt: "Gestão de frota motorizada", it: "Gestione del parco veicoli" },
    tagline: { sq: "Menaxhoni çdo makinë, shofer dhe shërbim nga telefoni", en: "Manage every vehicle, driver and service from your phone", es: "Gestione cada vehículo, conductor y servicio desde su teléfono", de: "Verwalten Sie jedes Fahrzeug, jeden Fahrer und jede Wartung vom Telefon", mk: "Управувајте со секое возило, возач и сервис од телефонот" , fr: "Gérez chaque véhicule, conducteur et service depuis votre téléphone", pt: "Gira cada veículo, condutor e serviço a partir do seu telemóvel", it: "Gestisci ogni veicolo, autista e servizio dal tuo telefono" },
    stat: { sq: "100% afate të ndjekura", en: "100% deadlines tracked", es: "100% plazos rastreados", de: "100% Fristen verfolgt", mk: "100% следени рокови" , fr: "100% des délais suivis", pt: "100% dos prazos acompanhados", it: "100% delle scadenze monitorate" },
    description: {
      sq: "Sistemi i flotës mbulon gjithçka — nga caktimi i shoferëve për udhëtime tek gjurmimi i mirëmbajtjeve, rinovimi i sigurimeve dhe skadencat e regjistrimit. Asnjë afat nuk kalohet pa u vënë re.",
      en: "The fleet system covers everything — from assigning drivers for trips to tracking maintenance, insurance renewals and registration deadlines. No deadline passes unnoticed.",
      es: "El sistema de flota cubre todo — desde la asignación de conductores para viajes hasta el seguimiento de mantenimiento, renovaciones de seguros y plazos de registro. Ningún plazo pasa desapercibido.",
      de: "Das Flottensystem deckt alles ab — von der Zuweisung von Fahrern für Fahrten bis zur Verfolgung von Wartungen, Versicherungserneuerungen und Registrierungsfristen. Keine Frist verstreicht unbemerkt.",
      mk: "Системот за флота покрива сè — од доделување на возачи за патувања до следење на одржување, обновување на осигурувања и рокови за регистрација. Ниту еден рок не поминува незабележано.",
    fr: "Le système de flotte couvre tout — de l'affectation des conducteurs aux trajets au suivi de la maintenance, renouvellements d'assurance et délais d'immatriculation. Aucune échéance ne passe inaperçue.", pt: "O sistema de frota cobre tudo — desde a atribuição de condutores para viagens ao rastreamento de manutenção, renovações de seguro e prazos de registo. Nenhum prazo passa despercebido.", it: "Il sistema di flotta copre tutto — dall'assegnazione degli autisti per i viaggi al monitoraggio della manutenzione, rinnovi assicurativi e scadenze di immatricolazione. Nessuna scadenza passa inosservata." },
    benefits: [
      { sq: "Regjistrim i flotës: makina, targë, pronësi", en: "Fleet registration: vehicles, plates, ownership", es: "Registro de flota: vehículos, placas, propiedad", de: "Flottenregistrierung: Fahrzeuge, Kennzeichen, Eigentum", mk: "Регистрација на флота: возила, таблички, сопственост" , fr: "Enregistrement de la flotte: véhicules, plaques, propriété", pt: "Registo da frota: veículos, matrículas, propriedade", it: "Registrazione flotta: veicoli, targhe, proprietà" },
      { sq: "Caktim shoferësh për udhëtime (ride dispatch)", en: "Driver assignment for trips (ride dispatch)", es: "Asignación de conductores para viajes (despacho)", de: "Fahrerzuweisung für Fahrten (Disposition)", mk: "Доделување возачи за патувања (диспечирање)" , fr: "Affectation des conducteurs pour les trajets (dispatch)", pt: "Atribuição de condutores para viagens (despacho)", it: "Assegnazione autisti per i viaggi (dispatch)" },
      { sq: "Gjurmim mirëmbajtjesh dhe servisimesh", en: "Maintenance and service tracking", es: "Seguimiento de mantenimiento y servicios", de: "Wartungs- und Serviceverfolgung", mk: "Следење на одржување и сервисирање" , fr: "Suivi de la maintenance et des services", pt: "Rastreamento de manutenção e serviços", it: "Monitoraggio manutenzione e servizi" },
      { sq: "Alarme rinovimi: sigurim, kasko, regjistrimi", en: "Renewal alerts: insurance, casco, registration", es: "Alertas de renovación: seguro, casco, registro", de: "Erneuerungsalarme: Versicherung, Kasko, Registrierung", mk: "Аларми за обновување: осигурување, каско, регистрација" , fr: "Alertes de renouvellement: assurance, casco, immatriculation", pt: "Alertas de renovação: seguro, casco, registo", it: "Avvisi di rinnovo: assicurazione, casco, immatricolazione" },
      { sq: "Historiku i plotë i shpenzimeve për çdo makinë", en: "Complete expense history for every vehicle", es: "Historial completo de gastos para cada vehículo", de: "Vollständige Ausgabenhistorie für jedes Fahrzeug", mk: "Целосна историја на трошоци за секое возило" , fr: "Historique complet des dépenses pour chaque véhicule", pt: "Histórico completo de despesas para cada veículo", it: "Cronologia completa delle spese per ogni veicolo" },
      { sq: "Raporte km, karburant dhe kosto/makina", en: "km, fuel and cost/vehicle reports", es: "Informes de km, combustible y costo/vehículo", de: "km-, Kraftstoff- und Kosten-/Fahrzeugberichte", mk: "Извештаи за km, гориво и трошок/возило" , fr: "Rapports km, carburant et coût/véhicule", pt: "Relatórios km, combustível e custo/veículo", it: "Report km, carburante e costo/veicolo" },
    ],
    workflow: [
      { step: "1", sq: "Regjistroni automjetin: targë, markë, model, viti, pronësia", en: "Register the vehicle: plate, make, model, year, ownership", es: "Registre el vehículo: placa, marca, modelo, año, propiedad", de: "Fahrzeug registrieren: Kennzeichen, Marke, Modell, Jahr, Eigentum", mk: "Регистрирајте го возилото: таблички, марка, модел, година, сопственост" , fr: "Enregistrez le véhicule: plaque, marque, modèle, année, propriété", pt: "Registe o veículo: matrícula, marca, modelo, ano, propriedade", it: "Registra il veicolo: targa, marca, modello, anno, proprietà" },
      { step: "2", sq: "Caktoni shoferin dhe konfiguroni skadencat (sigurim, kasko, regjistrimi)", en: "Assign the driver and configure deadlines (insurance, casco, registration)", es: "Asigne al conductor y configure los plazos (seguro, casco, registro)", de: "Fahrer zuweisen und Fristen konfigurieren (Versicherung, Kasko, Registrierung)", mk: "Доделете го возачот и конфигурирајте ги роковите (осигурување, каско, регистрација)" , fr: "Affectez le conducteur et configurez les échéances (assurance, casco, immatriculation)", pt: "Atribua o condutor e configure os prazos (seguro, casco, registo)", it: "Assegna l'autista e configura le scadenze (assicurazione, casco, immatricolazione)" },
      { step: "3", sq: "Shoferi raporton km-të dhe karburantin direkt nga telefoni", en: "Driver reports km and fuel directly from phone", es: "El conductor reporta km y combustible directamente desde el teléfono", de: "Fahrer meldet km und Kraftstoff direkt vom Telefon", mk: "Возачот пријавува km и гориво директно од телефонот" , fr: "Le conducteur signale les km et le carburant directement depuis le téléphone", pt: "O condutor reporta km e combustível diretamente do telemóvel", it: "L'autista segnala km e carburante direttamente dal telefono" },
      { step: "4", sq: "Sistemi dërgon alarme automatike kur afrohet skadenca e sigurimeve", en: "System sends automatic alerts when insurance deadlines approach", es: "El sistema envía alertas automáticas cuando se acercan los plazos del seguro", de: "System sendet automatische Alarme, wenn sich Versicherungsfristen nähern", mk: "Системот испраќа автоматски аларми кога се приближуваат роковите за осигурување" , fr: "Le système envoie des alertes automatiques quand les échéances d'assurance approchent", pt: "O sistema envia alertas automáticos quando os prazos de seguro se aproximam", it: "Il sistema invia avvisi automatici quando si avvicinano le scadenze assicurative" },
      { step: "5", sq: "Shikoni raporte: kosto/makinë, km/muaj, karburant/100km", en: "View reports: cost/vehicle, km/month, fuel/100km", es: "Vea informes: costo/vehículo, km/mes, combustible/100km", de: "Berichte ansehen: Kosten/Fahrzeug, km/Monat, Kraftstoff/100km", mk: "Погледнете извештаи: трошок/возило, km/месец, гориво/100km" , fr: "Consultez les rapports: coût/véhicule, km/mois, carburant/100km", pt: "Visualize relatórios: custo/veículo, km/mês, combustível/100km", it: "Visualizza i report: costo/veicolo, km/mese, carburante/100km" },
    ],
    capabilities: [
      { icon: "🚗", title: { sq: "Regjistrim Flotë", en: "Fleet Registration", es: "Registro de Flota", de: "Flottenregistrierung", mk: "Регистрација на Флота" , fr: "Enregistrement de la flotte", pt: "Registo da frota", it: "Registrazione della flotta" }, desc: { sq: "Regjistroni çdo automjet me targë, model, vit dhe dokumentacion", en: "Register every vehicle with plate, model, year and documentation", es: "Registre cada vehículo con placa, modelo, año y documentación", de: "Registrieren Sie jedes Fahrzeug mit Kennzeichen, Modell, Jahr und Dokumentation", mk: "Регистрирајте секое возило со таблички, модел, година и документација" , fr: "Enregistrez chaque véhicule avec plaque, modèle, année et documentation", pt: "Registe cada veículo com matrícula, modelo, ano e documentação", it: "Registra ogni veicolo con targa, modello, anno e documentazione" } },
      { icon: "👨‍✈️", title: { sq: "Dispatch Shoferësh", en: "Driver Dispatch", es: "Despacho de Conductores", de: "Fahrerdisposition", mk: "Диспечирање на Возачи" , fr: "Dispatch des conducteurs", pt: "Despacho de condutores", it: "Dispatch autisti" }, desc: { sq: "Caktoni shoferë për udhëtime me orar, destinacion dhe status", en: "Assign drivers for trips with schedule, destination and status", es: "Asigne conductores para viajes con horario, destino y estado", de: "Weisen Sie Fahrern Fahrten mit Zeitplan, Ziel und Status zu", mk: "Доделете возачи за патувања со распоред, дестинација и статус" , fr: "Affectez des conducteurs pour les trajets avec planning, destination et statut", pt: "Atribua condutores para viagens com horário, destino e estado", it: "Assegna autisti per i viaggi con orario, destinazione e stato" } },
      { icon: "⏰", title: { sq: "Alarme Skadence", en: "Deadline Alerts", es: "Alertas de Vencimiento", de: "Fristalarme", mk: "Аларми за Рокови" , fr: "Alertes d'échéance", pt: "Alertas de prazo", it: "Avvisi di scadenza" }, desc: { sq: "Asnjë sigurim, regjistrimi apo kasko nuk skadon pa alarme", en: "No insurance, registration or casco expires without alerts", es: "Ningún seguro, registro o casco vence sin alertas", de: "Keine Versicherung, Registrierung oder Kasko läuft ohne Alarm ab", mk: "Ниту едно осигурување, регистрација или каско не истекува без аларми" , fr: "Aucune assurance, immatriculation ou casco n'expire sans alertes", pt: "Nenhum seguro, registo ou casco expira sem alertas", it: "Nessuna assicurazione, immatricolazione o casco scade senza avvisi" } },
      { icon: "⛽", title: { sq: "Gjurmim Karburanti", en: "Fuel Tracking", es: "Seguimiento de Combustible", de: "Kraftstoffverfolgung", mk: "Следење на Гориво" , fr: "Suivi du carburant", pt: "Rastreamento de combustível", it: "Monitoraggio carburante" }, desc: { sq: "Monitoroni konsumin e karburantit për çdo automjet", en: "Monitor fuel consumption for every vehicle", es: "Monitoree el consumo de combustible de cada vehículo", de: "Überwachen Sie den Kraftstoffverbrauch für jedes Fahrzeug", mk: "Следете ја потрошувачката на гориво за секое возило" , fr: "Surveillez la consommation de carburant pour chaque véhicule", pt: "Monitorize o consumo de combustível para cada veículo", it: "Monitora il consumo di carburante per ogni veicolo" } },
      { icon: "💶", title: { sq: "Kosto per Makinë", en: "Cost per Vehicle", es: "Costo por Vehículo", de: "Kosten pro Fahrzeug", mk: "Трошок по Возило" , fr: "Coût par véhicule", pt: "Custo por veículo", it: "Costo per veicolo" }, desc: { sq: "Shpenzimet totale: karburant, mirëmbajtje, sigurim, goba", en: "Total expenses: fuel, maintenance, insurance, fines", es: "Gastos totales: combustible, mantenimiento, seguro, multas", de: "Gesamtkosten: Kraftstoff, Wartung, Versicherung, Bußgelder", mk: "Вкупни трошоци: гориво, одржување, осигурување, казни" , fr: "Dépenses totales: carburant, maintenance, assurance, amendes", pt: "Despesas totais: combustível, manutenção, seguro, multas", it: "Spese totali: carburante, manutenzione, assicurazione, multe" } },
      { icon: "📊", title: { sq: "Raporte Flotë", en: "Fleet Reports", es: "Informes de Flota", de: "Flottenberichte", mk: "Извештаи за Флота" , fr: "Rapports de flotte", pt: "Relatórios de frota", it: "Report della flotta" }, desc: { sq: "Analiza me grafiqe: km, kosto, efikasiteti, shoferi më i mirë", en: "Chart analytics: km, cost, efficiency, best driver", es: "Análisis con gráficos: km, costo, eficiencia, mejor conductor", de: "Diagrammanalysen: km, Kosten, Effizienz, bester Fahrer", mk: "Анализи со графикони: km, трошок, ефикасност, најдобар возач" , fr: "Analyses graphiques: km, coût, efficacité, meilleur conducteur", pt: "Análises gráficas: km, custo, eficiência, melhor condutor", it: "Analisi grafiche: km, costo, efficienza, miglior autista" } },
    ],
  }} />;
}
