import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureInvoicing() {
  return <FeatureDetail data={{
    category: { sq: "Financë", en: "Finance", es: "Finanzas", de: "Finanzen", mk: "Финансии" },
    categoryColor: "bg-blue-500",
    title: { sq: "Faturim Profesional Elektronik", en: "Professional Electronic Invoicing", es: "Facturación Electrónica Profesional", de: "Professionelle Elektronische Rechnungsstellung", mk: "Професионално Електронско Фактурирање" },
    tagline: { sq: "Dërgoni me email, gjurmoni hapjen, nënshkruani dixhitalisht", en: "Send by email, track opening, sign digitally", es: "Envíe por correo, rastree la apertura, firme digitalmente", de: "Per E-Mail senden, Öffnung verfolgen, digital unterschreiben", mk: "Испратете по е-пошта, следете го отворањето, потпишете дигитално" },
    stat: { sq: "40% pagesa më shpejt", en: "40% faster payments", es: "40% pagos más rápidos", de: "40% schnellere Zahlungen", mk: "40% побрзи плаќања" },
    description: {
      sq: "Krijoni dhe dërgoni fatura me email me një klikim. Ju shikoni nëse klienti e ka hapur faturën ose jo, dhe klienti mund ta nënshkruajë direkt nga telefoni ose kompjuteri pa asnjë printer.",
      en: "Create and send invoices by email with one click. You can see whether the client has opened the invoice, and the client can sign it directly from their phone or computer without any printer.",
      es: "Cree y envíe facturas por correo electrónico con un solo clic. Puede ver si el cliente ha abierto la factura, y el cliente puede firmarla directamente desde su teléfono u ordenador sin necesidad de impresora.",
      de: "Erstellen und versenden Sie Rechnungen per E-Mail mit einem Klick. Sie können sehen, ob der Kunde die Rechnung geöffnet hat, und der Kunde kann sie direkt vom Telefon oder Computer ohne Drucker unterschreiben.",
      mk: "Креирајте и испраќајте фактури по е-пошта со еден клик. Можете да видите дали клиентот ја отворил фактурата, а клиентот може да ја потпише директно од телефон или компјутер без печатач.",
    },
    benefits: [
      { sq: "Dërgim fature me email — profesional dhe i menjëhershëm", en: "Invoice delivery by email — professional and immediate", es: "Envío de facturas por correo — profesional e inmediato", de: "Rechnungsversand per E-Mail — professionell und sofort", mk: "Испраќање фактури по е-пошта — професионално и моментално" },
      { sq: "Shiko nëse fatura është hapur nga klienti", en: "See if the invoice has been opened by the client", es: "Vea si la factura ha sido abierta por el cliente", de: "Sehen Sie, ob die Rechnung vom Kunden geöffnet wurde", mk: "Видете дали фактурата е отворена од клиентот" },
      { sq: "Nënshkrim dixhital i klientit (telefon ose PC)", en: "Client digital signature (phone or PC)", es: "Firma digital del cliente (teléfono o PC)", de: "Digitale Unterschrift des Kunden (Telefon oder PC)", mk: "Дигитален потпис на клиентот (телефон или компјутер)" },
      { sq: "Nënshkrim nga ana e kompanisë suaj gjithashtu", en: "Signature from your company as well", es: "Firma de su empresa también", de: "Unterschrift auch von Ihrem Unternehmen", mk: "Потпис и од ваша компанија исто така" },
      { sq: "Rikujtime automatike kur fatura nuk paguhet", en: "Automatic reminders when invoice is unpaid", es: "Recordatorios automáticos cuando la factura no se paga", de: "Automatische Erinnerungen bei unbezahlter Rechnung", mk: "Автоматски потсетници кога фактурата не е платена" },
      { sq: "Shabllone të ndryshme me markën tuaj", en: "Different templates with your brand", es: "Diferentes plantillas con su marca", de: "Verschiedene Vorlagen mit Ihrer Marke", mk: "Различни шаблони со вашиот бренд" },
    ],
    workflow: [
      { step: "1", sq: "Zgjidhni shabllon fature dhe plotësoni artikujt, sasitë dhe çmimet", en: "Choose an invoice template and fill in items, quantities and prices", es: "Elija una plantilla de factura y complete artículos, cantidades y precios", de: "Wählen Sie eine Rechnungsvorlage und füllen Sie Artikel, Mengen und Preise aus", mk: "Изберете шаблон за фактура и пополнете артикли, количини и цени" },
      { step: "2", sq: "Dërgoni faturën me email — klienti merr linkun për ta hapur", en: "Send the invoice by email — the client receives the link to open it", es: "Envíe la factura por correo — el cliente recibe el enlace para abrirla", de: "Senden Sie die Rechnung per E-Mail — der Kunde erhält den Link zum Öffnen", mk: "Испратете ја фактурата по е-пошта — клиентот добива линк за отворање" },
      { step: "3", sq: "Gjurmoni: kur hapet, sa herë lexohet, dhe statusin e pagesës", en: "Track: when it's opened, how many times read, and payment status", es: "Rastree: cuándo se abre, cuántas veces se lee y el estado del pago", de: "Verfolgen: wann geöffnet, wie oft gelesen und Zahlungsstatus", mk: "Следете: кога е отворена, колку пати е прочитана и статус на плаќање" },
      { step: "4", sq: "Klienti nënshkruan dixhitalisht dhe ju merrni konfirmimin menjëherë", en: "Client signs digitally and you get confirmation immediately", es: "El cliente firma digitalmente y usted recibe la confirmación de inmediato", de: "Der Kunde unterschreibt digital und Sie erhalten sofort eine Bestätigung", mk: "Клиентот потпишува дигитално и вие добивате потврда веднаш" },
      { step: "5", sq: "Rikujtime automatike dërgohen nëse fatura nuk paguhet brenda afatit", en: "Auto reminders sent if invoice is unpaid within the deadline", es: "Se envían recordatorios automáticos si la factura no se paga dentro del plazo", de: "Automatische Erinnerungen werden gesendet, wenn die Rechnung nicht fristgerecht bezahlt wird", mk: "Автоматски потсетници се испраќаат ако фактурата не е платена во рок" },
    ],
    capabilities: [
      { icon: "📧", title: { sq: "Dërgim me Email", en: "Email Delivery", es: "Envío por Correo", de: "E-Mail-Versand", mk: "Испраќање по Е-пошта" }, desc: { sq: "Fatura dërgohet direkt me email — profesionale dhe e menjëhershme", en: "Invoice sent directly by email — professional and immediate", es: "Factura enviada directamente por correo — profesional e inmediata", de: "Rechnung direkt per E-Mail gesendet — professionell und sofort", mk: "Фактурата се испраќа директно по е-пошта — професионално и моментално" } },
      { icon: "👁️", title: { sq: "Gjurmim Hapjeje", en: "Open Tracking", es: "Rastreo de Apertura", de: "Öffnungsverfolgung", mk: "Следење на Отворање" }, desc: { sq: "Shikoni kur klienti e hap faturën dhe sa herë e lexon", en: "See when client opens the invoice and how many times they read it", es: "Vea cuándo el cliente abre la factura y cuántas veces la lee", de: "Sehen Sie, wann der Kunde die Rechnung öffnet und wie oft er sie liest", mk: "Видете кога клиентот ја отвора фактурата и колку пати ја чита" } },
      { icon: "✍️", title: { sq: "Nënshkrim Dixhital", en: "Digital Signature", es: "Firma Digital", de: "Digitale Unterschrift", mk: "Дигитален Потпис" }, desc: { sq: "Nënshkrim ligjërisht i vlefshëm nga telefoni ose kompjuteri", en: "Legally valid signature from phone or computer", es: "Firma legalmente válida desde teléfono u ordenador", de: "Rechtsgültige Unterschrift vom Telefon oder Computer", mk: "Правно валиден потпис од телефон или компјутер" } },
      { icon: "🔔", title: { sq: "Rikujtime Automatike", en: "Auto Reminders", es: "Recordatorios Automáticos", de: "Automatische Erinnerungen", mk: "Автоматски Потсетници" }, desc: { sq: "Sistemi dërgon rikujtime nëse fatura nuk paguhet brenda afatit", en: "System sends reminders if invoice is unpaid within deadline", es: "El sistema envía recordatorios si la factura no se paga dentro del plazo", de: "System sendet Erinnerungen, wenn die Rechnung nicht fristgerecht bezahlt wird", mk: "Системот испраќа потсетници ако фактурата не е платена во рок" } },
      { icon: "🎨", title: { sq: "Shabllone të Markës", en: "Branded Templates", es: "Plantillas de Marca", de: "Markenvorlagen", mk: "Брендирани Шаблони" }, desc: { sq: "Shabllone profesionale me logon, ngjyrat dhe stilin tuaj", en: "Professional templates with your logo, colors and style", es: "Plantillas profesionales con su logotipo, colores y estilo", de: "Professionelle Vorlagen mit Ihrem Logo, Farben und Stil", mk: "Професионални шаблони со вашето лого, бои и стил" } },
      { icon: "📊", title: { sq: "Raporte Faturash", en: "Invoice Reports", es: "Informes de Facturas", de: "Rechnungsberichte", mk: "Извештаи за Фактури" }, desc: { sq: "Statistika: paguar, në pritje, të vonuara — me grafikë dhe eksport", en: "Statistics: paid, pending, overdue — with charts and export", es: "Estadísticas: pagadas, pendientes, vencidas — con gráficos y exportación", de: "Statistiken: bezahlt, ausstehend, überfällig — mit Diagrammen und Export", mk: "Статистики: платени, во чекање, задоцнети — со графикони и извоз" } },
    ],
  }} />;
}
