import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureExpenses() {
  return <FeatureDetail data={{
    category: { sq: "Financë", en: "Finance", es: "Finanzas", de: "Finanzen", mk: "Финансии" },
    categoryColor: "bg-green-500",
    title: { sq: "Gjurmim Shpenzimesh", en: "Expense Tracking", es: "Seguimiento de Gastos", de: "Ausgabenverfolgung", mk: "Следење на Трошоци" },
    tagline: { sq: "Organizoni shpenzimet, kurseni kohë dhe para", en: "Organize expenses, save time and money", es: "Organice gastos, ahorre tiempo y dinero", de: "Ausgaben organisieren, Zeit und Geld sparen", mk: "Организирајте трошоци, заштедете време и пари" },
    stat: { sq: "0 hyrje manuale mes bizneseve Clientlly", en: "0 manual entries between Clientlly businesses", es: "0 entradas manuales entre negocios Clientlly", de: "0 manuelle Eingaben zwischen Clientlly-Unternehmen", mk: "0 рачни внесувања меѓу Clientlly бизниси" },
    description: {
      sq: "Nëse shitësi përdor Clientlly, fatura e tij regjistrohet direkt si shpenzim për ju — pa asnjë hyrje manuale. Thjesht aprovoni dhe sistemi e bën vetë. Për blerjet e tjera, skanoni faturën me kamerë.",
      en: "If the vendor uses Clientlly, their invoice is recorded directly as an expense for you — without any manual entry. Just approve and the system does the rest. For other purchases, scan the invoice with camera.",
      es: "Si el proveedor usa Clientlly, su factura se registra directamente como gasto para usted — sin ninguna entrada manual. Solo apruebe y el sistema hace el resto. Para otras compras, escanee la factura con la cámara.",
      de: "Wenn der Lieferant Clientlly verwendet, wird seine Rechnung direkt als Ausgabe für Sie erfasst — ohne manuelle Eingabe. Einfach genehmigen und das System erledigt den Rest. Für andere Einkäufe scannen Sie die Rechnung mit der Kamera.",
      mk: "Ако продавачот користи Clientlly, неговата фактура се евидентира директно како трошок за вас — без рачно внесување. Само одобрете и системот го прави остатокот. За други набавки, скенирајте ја фактурата со камера.",
    },
    benefits: [
      { sq: "Fatura e shitësit Clientlly → shpenzim automatik për ju", en: "Clientlly vendor invoice → automatic expense for you", es: "Factura del proveedor Clientlly → gasto automático para usted", de: "Clientlly-Lieferantenrechnung → automatische Ausgabe für Sie", mk: "Фактура од Clientlly продавач → автоматски трошок за вас" },
      { sq: "Pa hyrje manuale — thjesht aprovoni me 1 klikim", en: "No manual entry — just approve with 1 click", es: "Sin entrada manual — solo apruebe con 1 clic", de: "Keine manuelle Eingabe — einfach mit 1 Klick genehmigen", mk: "Без рачно внесување — само одобрете со 1 клик" },
      { sq: "Skanim automatik i faturave me kamerë (të tjerët)", en: "Automatic invoice scanning with camera (others)", es: "Escaneo automático de facturas con cámara (otros)", de: "Automatisches Rechnungsscannen mit Kamera (andere)", mk: "Автоматско скенирање на фактури со камера (други)" },
      { sq: "Kategorizim inteligjent i shpenzimeve", en: "Intelligent expense categorization", es: "Categorización inteligente de gastos", de: "Intelligente Ausgabenkategorisierung", mk: "Интелигентна категоризација на трошоци" },
      { sq: "Raporte të gatshme për taksën", en: "Tax-ready reports", es: "Informes listos para impuestos", de: "Steuerfertige Berichte", mk: "Извештаи подготвени за данок" },
      { sq: "Buxhet, alarme tejkalimi dhe lidhje me flotën", en: "Budget, overage alerts and fleet integration", es: "Presupuesto, alertas de exceso e integración de flota", de: "Budget, Überschreitungswarnungen und Flottenintegration", mk: "Буџет, аларми за прекорачување и интеграција со флота" },
    ],
    workflow: [
      { step: "1", sq: "Shitësi Clientlly ju dërgon faturën — ajo shfaqet automatikisht te shpenzimet tuaja", en: "Clientlly vendor sends you an invoice — it appears automatically in your expenses", es: "El proveedor Clientlly le envía una factura — aparece automáticamente en sus gastos", de: "Der Clientlly-Lieferant sendet Ihnen eine Rechnung — sie erscheint automatisch in Ihren Ausgaben", mk: "Clientlly продавачот ви испраќа фактура — таа автоматски се појавува во вашите трошоци" },
      { step: "2", sq: "Aprovoni shpenzimin me një klikim — sistemi e kategorizon vetë", en: "Approve the expense with one click — the system categorizes it automatically", es: "Apruebe el gasto con un clic — el sistema lo categoriza automáticamente", de: "Genehmigen Sie die Ausgabe mit einem Klick — das System kategorisiert sie automatisch", mk: "Одобрете го трошокот со еден клик — системот го категоризира автоматски" },
      { step: "3", sq: "Për blerje jashtë Clientlly, skanoni faturën me kamerë ose ngarkoni PDF", en: "For purchases outside Clientlly, scan the invoice with camera or upload PDF", es: "Para compras fuera de Clientlly, escanee la factura con cámara o suba PDF", de: "Für Einkäufe außerhalb von Clientlly scannen Sie die Rechnung mit der Kamera oder laden Sie ein PDF hoch", mk: "За набавки надвор од Clientlly, скенирајте ја фактурата со камера или прикачете PDF" },
      { step: "4", sq: "Shikoni raportet mujore me kategorit, buxhetin dhe alarmet", en: "View monthly reports with categories, budget and alerts", es: "Vea informes mensuales con categorías, presupuesto y alertas", de: "Sehen Sie monatliche Berichte mit Kategorien, Budget und Warnungen", mk: "Прегледајте месечни извештаи со категории, буџет и аларми" },
    ],
    capabilities: [
      { icon: "🔄", title: { sq: "Integrim Automatik", en: "Auto Integration", es: "Integración Automática", de: "Automatische Integration", mk: "Автоматска Интеграција" }, desc: { sq: "Faturat nga biznese Clientlly regjistrohen automatikisht si shpenzime", en: "Invoices from Clientlly businesses auto-recorded as expenses", es: "Las facturas de negocios Clientlly se registran automáticamente como gastos", de: "Rechnungen von Clientlly-Unternehmen werden automatisch als Ausgaben erfasst", mk: "Фактурите од Clientlly бизниси автоматски се евидентираат како трошоци" } },
      { icon: "📸", title: { sq: "Skanim me Kamerë", en: "Camera Scanning", es: "Escaneo con Cámara", de: "Kamerascannen", mk: "Скенирање со Камера" }, desc: { sq: "Fotografoni faturën dhe sistemi e lexon e kategorizon automatikisht", en: "Photo the invoice and the system reads and categorizes automatically", es: "Fotografíe la factura y el sistema la lee y categoriza automáticamente", de: "Fotografieren Sie die Rechnung und das System liest und kategorisiert automatisch", mk: "Фотографирајте ја фактурата и системот ја чита и категоризира автоматски" } },
      { icon: "📁", title: { sq: "Kategorizim i Zgjuar", en: "Smart Categorization", es: "Categorización Inteligente", de: "Intelligente Kategorisierung", mk: "Паметна Категоризација" }, desc: { sq: "Shpenzimet grupohen sipas kategorisë: zyrë, udhëtim, material, etj.", en: "Expenses grouped by category: office, travel, materials, etc.", es: "Gastos agrupados por categoría: oficina, viajes, materiales, etc.", de: "Ausgaben nach Kategorie gruppiert: Büro, Reisen, Material usw.", mk: "Трошоците се групираат по категорија: канцеларија, патување, материјали итн." } },
      { icon: "💰", title: { sq: "Buxhet & Alarme", en: "Budget & Alerts", es: "Presupuesto y Alertas", de: "Budget & Warnungen", mk: "Буџет и Аларми" }, desc: { sq: "Caktoni buxhete mujore dhe merrni alarme kur afrohet tejkalimi", en: "Set monthly budgets and get alerts when approaching overspend", es: "Establezca presupuestos mensuales y reciba alertas al acercarse al exceso", de: "Legen Sie monatliche Budgets fest und erhalten Sie Warnungen bei drohender Überschreitung", mk: "Поставете месечни буџети и добивајте аларми кога се приближува прекорачување" } },
      { icon: "📋", title: { sq: "Raporte Taksore", en: "Tax Reports", es: "Informes Fiscales", de: "Steuerberichte", mk: "Даночни Извештаи" }, desc: { sq: "Raporte të gatshme për kontabilistin me zbritje dhe TVSH", en: "Reports ready for accountant with deductions and VAT", es: "Informes listos para el contable con deducciones e IVA", de: "Berichte fertig für den Buchhalter mit Abzügen und MwSt.", mk: "Извештаи подготвени за сметководител со одбивања и ДДВ" } },
      { icon: "🚗", title: { sq: "Lidhje me Flotën", en: "Fleet Integration", es: "Integración de Flota", de: "Flottenintegration", mk: "Интеграција со Флота" }, desc: { sq: "Shpenzimet e flotës (karburant, mirëmbajtje) lidhen automatikisht", en: "Fleet expenses (fuel, maintenance) linked automatically", es: "Los gastos de flota (combustible, mantenimiento) se vinculan automáticamente", de: "Flottenausgaben (Kraftstoff, Wartung) werden automatisch verknüpft", mk: "Трошоците за флота (гориво, одржување) се поврзуваат автоматски" } },
    ],
  }} />;
}
