import FeatureDetail from "@/components/FeatureDetail";

export default function FeatureExpenses() {
  return <FeatureDetail data={{
    category: { sq: "Financë", en: "Finance", es: "Finanzas", de: "Finanzen", mk: "Финансии", fr: "Finance", pt: "Finanças", it: "Finanza" },
    categoryColor: "bg-green-500",
    title: { sq: "Gjurmim Shpenzimesh", en: "Expense Tracking", es: "Seguimiento de Gastos", de: "Ausgabenverfolgung", mk: "Следење на Трошоци" , fr: "Suivi des dépenses", pt: "Controlo de despesas", it: "Monitoraggio delle spese" },
    tagline: { sq: "Organizoni shpenzimet, kurseni kohë dhe para", en: "Organize expenses, save time and money", es: "Organice gastos, ahorre tiempo y dinero", de: "Ausgaben organisieren, Zeit und Geld sparen", mk: "Организирајте трошоци, заштедете време и пари" , fr: "Organisez les dépenses, économisez du temps et de l'argent", pt: "Organize despesas, poupe tempo e dinheiro", it: "Organizza le spese, risparmia tempo e denaro" },
    stat: { sq: "0 hyrje manuale mes bizneseve Clientlly", en: "0 manual entries between Clientlly businesses", es: "0 entradas manuales entre negocios Clientlly", de: "0 manuelle Eingaben zwischen Clientlly-Unternehmen", mk: "0 рачни внесувања меѓу Clientlly бизниси" , fr: "0 saisies manuelles entre entreprises Clientlly", pt: "0 entradas manuais entre empresas Clientlly", it: "0 inserimenti manuali tra aziende Clientlly" },
    description: {
      sq: "Nëse shitësi përdor Clientlly, fatura e tij regjistrohet direkt si shpenzim për ju — pa asnjë hyrje manuale. Thjesht aprovoni dhe sistemi e bën vetë. Për blerjet e tjera, skanoni faturën me kamerë.",
      en: "If the vendor uses Clientlly, their invoice is recorded directly as an expense for you — without any manual entry. Just approve and the system does the rest. For other purchases, scan the invoice with camera.",
      es: "Si el proveedor usa Clientlly, su factura se registra directamente como gasto para usted — sin ninguna entrada manual. Solo apruebe y el sistema hace el resto. Para otras compras, escanee la factura con la cámara.",
      de: "Wenn der Lieferant Clientlly verwendet, wird seine Rechnung direkt als Ausgabe für Sie erfasst — ohne manuelle Eingabe. Einfach genehmigen und das System erledigt den Rest. Für andere Einkäufe scannen Sie die Rechnung mit der Kamera.",
      mk: "Ако продавачот користи Clientlly, неговата фактура се евидентира директно како трошок за вас — без рачно внесување. Само одобрете и системот го прави остатокот. За други набавки, скенирајте ја фактурата со камера.",
    fr: "Si le fournisseur utilise Clientlly, sa facture est directement enregistrée comme dépense — sans saisie manuelle. Approuvez et le système fait le reste. Pour les autres achats, scannez la facture.", pt: "Se o fornecedor usa o Clientlly, a fatura é registada diretamente como despesa — sem entrada manual. Aprove e o sistema faz o resto. Para outras compras, digitalize a fatura.", it: "Se il fornitore usa Clientlly, la fattura viene registrata direttamente come spesa — senza inserimento manuale. Approva e il sistema fa il resto. Per altri acquisti, scansiona la fattura." },
    benefits: [
      { sq: "Fatura e shitësit Clientlly → shpenzim automatik për ju", en: "Clientlly vendor invoice → automatic expense for you", es: "Factura del proveedor Clientlly → gasto automático para usted", de: "Clientlly-Lieferantenrechnung → automatische Ausgabe für Sie", mk: "Фактура од Clientlly продавач → автоматски трошок за вас" , fr: "Facture fournisseur Clientlly → dépense automatique pour vous", pt: "Fatura de fornecedor Clientlly → despesa automática para si", it: "Fattura fornitore Clientlly → spesa automatica per te" },
      { sq: "Pa hyrje manuale — thjesht aprovoni me 1 klikim", en: "No manual entry — just approve with 1 click", es: "Sin entrada manual — solo apruebe con 1 clic", de: "Keine manuelle Eingabe — einfach mit 1 Klick genehmigen", mk: "Без рачно внесување — само одобрете со 1 клик" , fr: "Aucune saisie manuelle — approuvez avec 1 clic", pt: "Sem entrada manual — basta aprovar com 1 clique", it: "Nessun inserimento manuale — approva con 1 clic" },
      { sq: "Skanim automatik i faturave me kamerë (të tjerët)", en: "Automatic invoice scanning with camera (others)", es: "Escaneo automático de facturas con cámara (otros)", de: "Automatisches Rechnungsscannen mit Kamera (andere)", mk: "Автоматско скенирање на фактури со камера (други)" , fr: "Numérisation automatique des factures avec caméra (autres)", pt: "Digitalização automática de faturas com câmara (outros)", it: "Scansione automatica delle fatture con fotocamera (altri)" },
      { sq: "Kategorizim inteligjent i shpenzimeve", en: "Intelligent expense categorization", es: "Categorización inteligente de gastos", de: "Intelligente Ausgabenkategorisierung", mk: "Интелигентна категоризација на трошоци" , fr: "Catégorisation intelligente des dépenses", pt: "Categorização inteligente de despesas", it: "Categorizzazione intelligente delle spese" },
      { sq: "Raporte të gatshme për taksën", en: "Tax-ready reports", es: "Informes listos para impuestos", de: "Steuerfertige Berichte", mk: "Извештаи подготвени за данок" , fr: "Rapports prêts pour les impôts", pt: "Relatórios prontos para impostos", it: "Report pronti per le tasse" },
      { sq: "Buxhet, alarme tejkalimi dhe lidhje me flotën", en: "Budget, overage alerts and fleet integration", es: "Presupuesto, alertas de exceso e integración de flota", de: "Budget, Überschreitungswarnungen und Flottenintegration", mk: "Буџет, аларми за прекорачување и интеграција со флота" , fr: "Budget, alertes de dépassement et intégration de flotte", pt: "Orçamento, alertas de excesso e integração de frota", it: "Budget, avvisi di superamento e integrazione flotta" },
    ],
    workflow: [
      { step: "1", sq: "Shitësi Clientlly ju dërgon faturën — ajo shfaqet automatikisht te shpenzimet tuaja", en: "Clientlly vendor sends you an invoice — it appears automatically in your expenses", es: "El proveedor Clientlly le envía una factura — aparece automáticamente en sus gastos", de: "Der Clientlly-Lieferant sendet Ihnen eine Rechnung — sie erscheint automatisch in Ihren Ausgaben", mk: "Clientlly продавачот ви испраќа фактура — таа автоматски се појавува во вашите трошоци" , fr: "Un fournisseur Clientlly vous envoie une facture — elle apparaît automatiquement dans vos dépenses", pt: "Um fornecedor Clientlly envia-lhe uma fatura — aparece automaticamente nas suas despesas", it: "Un fornitore Clientlly ti invia una fattura — appare automaticamente nelle tue spese" },
      { step: "2", sq: "Aprovoni shpenzimin me një klikim — sistemi e kategorizon vetë", en: "Approve the expense with one click — the system categorizes it automatically", es: "Apruebe el gasto con un clic — el sistema lo categoriza automáticamente", de: "Genehmigen Sie die Ausgabe mit einem Klick — das System kategorisiert sie automatisch", mk: "Одобрете го трошокот со еден клик — системот го категоризира автоматски" , fr: "Approuvez la dépense en un clic — le système la catégorise automatiquement", pt: "Aprove a despesa com um clique — o sistema categoriza-a automaticamente", it: "Approva la spesa con un clic — il sistema la categorizza automaticamente" },
      { step: "3", sq: "Për blerje jashtë Clientlly, skanoni faturën me kamerë ose ngarkoni PDF", en: "For purchases outside Clientlly, scan the invoice with camera or upload PDF", es: "Para compras fuera de Clientlly, escanee la factura con cámara o suba PDF", de: "Für Einkäufe außerhalb von Clientlly scannen Sie die Rechnung mit der Kamera oder laden Sie ein PDF hoch", mk: "За набавки надвор од Clientlly, скенирајте ја фактурата со камера или прикачете PDF" , fr: "Pour les achats hors Clientlly, scannez la facture avec la caméra ou téléchargez un PDF", pt: "Para compras fora do Clientlly, digitalize a fatura com câmara ou carregue PDF", it: "Per gli acquisti fuori da Clientlly, scansiona la fattura con la fotocamera o carica il PDF" },
      { step: "4", sq: "Shikoni raportet mujore me kategorit, buxhetin dhe alarmet", en: "View monthly reports with categories, budget and alerts", es: "Vea informes mensuales con categorías, presupuesto y alertas", de: "Sehen Sie monatliche Berichte mit Kategorien, Budget und Warnungen", mk: "Прегледајте месечни извештаи со категории, буџет и аларми" , fr: "Consultez les rapports mensuels avec catégories, budget et alertes", pt: "Visualize relatórios mensais com categorias, orçamento e alertas", it: "Visualizza i report mensili con categorie, budget e avvisi" },
    ],
    capabilities: [
      { icon: "🔄", title: { sq: "Integrim Automatik", en: "Auto Integration", es: "Integración Automática", de: "Automatische Integration", mk: "Автоматска Интеграција" , fr: "Intégration automatique", pt: "Integração automática", it: "Integrazione automatica" }, desc: { sq: "Faturat nga biznese Clientlly regjistrohen automatikisht si shpenzime", en: "Invoices from Clientlly businesses auto-recorded as expenses", es: "Las facturas de negocios Clientlly se registran automáticamente como gastos", de: "Rechnungen von Clientlly-Unternehmen werden automatisch als Ausgaben erfasst", mk: "Фактурите од Clientlly бизниси автоматски се евидентираат како трошоци" , fr: "Les factures des entreprises Clientlly sont automatiquement enregistrées comme dépenses", pt: "As faturas de empresas Clientlly são automaticamente registadas como despesas", it: "Le fatture delle aziende Clientlly vengono automaticamente registrate come spese" } },
      { icon: "📸", title: { sq: "Skanim me Kamerë", en: "Camera Scanning", es: "Escaneo con Cámara", de: "Kamerascannen", mk: "Скенирање со Камера" , fr: "Numérisation par caméra", pt: "Digitalização por câmara", it: "Scansione con fotocamera" }, desc: { sq: "Fotografoni faturën dhe sistemi e lexon e kategorizon automatikisht", en: "Photo the invoice and the system reads and categorizes automatically", es: "Fotografíe la factura y el sistema la lee y categoriza automáticamente", de: "Fotografieren Sie die Rechnung und das System liest und kategorisiert automatisch", mk: "Фотографирајте ја фактурата и системот ја чита и категоризира автоматски" , fr: "Photographiez la facture et le système lit et catégorise automatiquement", pt: "Fotografe a fatura e o sistema lê e categoriza automaticamente", it: "Fotografa la fattura e il sistema legge e categorizza automaticamente" } },
      { icon: "📁", title: { sq: "Kategorizim i Zgjuar", en: "Smart Categorization", es: "Categorización Inteligente", de: "Intelligente Kategorisierung", mk: "Паметна Категоризација" , fr: "Catégorisation intelligente", pt: "Categorização inteligente", it: "Categorizzazione intelligente" }, desc: { sq: "Shpenzimet grupohen sipas kategorisë: zyrë, udhëtim, material, etj.", en: "Expenses grouped by category: office, travel, materials, etc.", es: "Gastos agrupados por categoría: oficina, viajes, materiales, etc.", de: "Ausgaben nach Kategorie gruppiert: Büro, Reisen, Material usw.", mk: "Трошоците се групираат по категорија: канцеларија, патување, материјали итн." , fr: "Dépenses regroupées par catégorie: bureau, voyage, matériaux, etc.", pt: "Despesas agrupadas por categoria: escritório, viagem, materiais, etc.", it: "Spese raggruppate per categoria: ufficio, viaggi, materiali, ecc." } },
      { icon: "💰", title: { sq: "Buxhet & Alarme", en: "Budget & Alerts", es: "Presupuesto y Alertas", de: "Budget & Warnungen", mk: "Буџет и Аларми" , fr: "Budget & Alertes", pt: "Orçamento & Alertas", it: "Budget & Avvisi" }, desc: { sq: "Caktoni buxhete mujore dhe merrni alarme kur afrohet tejkalimi", en: "Set monthly budgets and get alerts when approaching overspend", es: "Establezca presupuestos mensuales y reciba alertas al acercarse al exceso", de: "Legen Sie monatliche Budgets fest und erhalten Sie Warnungen bei drohender Überschreitung", mk: "Поставете месечни буџети и добивајте аларми кога се приближува прекорачување" , fr: "Définissez des budgets mensuels et recevez des alertes lors d'un dépassement", pt: "Defina orçamentos mensais e receba alertas ao aproximar-se do limite", it: "Imposta budget mensili e ricevi avvisi quando si avvicina al superamento" } },
      { icon: "📋", title: { sq: "Raporte Taksore", en: "Tax Reports", es: "Informes Fiscales", de: "Steuerberichte", mk: "Даночни Извештаи" , fr: "Rapports fiscaux", pt: "Relatórios fiscais", it: "Report fiscali" }, desc: { sq: "Raporte të gatshme për kontabilistin me zbritje dhe TVSH", en: "Reports ready for accountant with deductions and VAT", es: "Informes listos para el contable con deducciones e IVA", de: "Berichte fertig für den Buchhalter mit Abzügen und MwSt.", mk: "Извештаи подготвени за сметководител со одбивања и ДДВ" , fr: "Rapports prêts pour le comptable avec déductions et TVA", pt: "Relatórios prontos para o contabilista com deduções e IVA", it: "Report pronti per il contabile con detrazioni e IVA" } },
      { icon: "🚗", title: { sq: "Lidhje me Flotën", en: "Fleet Integration", es: "Integración de Flota", de: "Flottenintegration", mk: "Интеграција со Флота" , fr: "Intégration de flotte", pt: "Integração de frota", it: "Integrazione flotta" }, desc: { sq: "Shpenzimet e flotës (karburant, mirëmbajtje) lidhen automatikisht", en: "Fleet expenses (fuel, maintenance) linked automatically", es: "Los gastos de flota (combustible, mantenimiento) se vinculan automáticamente", de: "Flottenausgaben (Kraftstoff, Wartung) werden automatisch verknüpft", mk: "Трошоците за флота (гориво, одржување) се поврзуваат автоматски" , fr: "Les dépenses de flotte (carburant, entretien) sont liées automatiquement", pt: "As despesas de frota (combustível, manutenção) são ligadas automaticamente", it: "Le spese della flotta (carburante, manutenzione) vengono collegate automaticamente" } },
    ],
  }} />;
}
