import FeatureDetail from "@/components/FeatureDetail";

const data = {
  category: { sq: "Financë", en: "Finance", es: "Finanzas", de: "Finanzen", mk: "Финансии", fr: "Finance", pt: "Finanças", it: "Finanza" },
  categoryColor: "bg-cyan-500",
  title: { sq: "Oferta & Kuota Elektronike", en: "Electronic Quotes & Offers", es: "Cotizaciones & Ofertas Electrónicas", de: "Elektronische Angebote & Offerten", mk: "Електронски Понуди & Офери" , fr: "Devis & Offres électroniques", pt: "Orçamentos & Ofertas eletrónicos", it: "Preventivi & Offerte elettronici" },
  tagline: { sq: "Dërgoni, gjurmoni dhe nënshkruani — pa letër", en: "Send, track and sign — paperless", es: "Envíe, rastree y firme — sin papel", de: "Senden, verfolgen und unterschreiben — papierlos", mk: "Испратете, следете и потпишете — без хартија" , fr: "Envoyez, suivez et signez — sans papier", pt: "Envie, acompanhe e assine — sem papel", it: "Invia, monitora e firma — senza carta" },
  stat: { sq: "3× oferta të aprovuara", en: "3× faster quote approval", es: "3× aprobación de cotizaciones más rápida", de: "3× schnellere Angebotsgenehmigung", mk: "3× побрзо одобрување на понуди" , fr: "3× d'approbation de devis plus rapide", pt: "3× aprovação de orçamento mais rápida", it: "3× approvazione preventivo più veloce" },
  description: {
    sq: "Krijoni oferta profesionale me shabllone të ndryshme dhe dërgojini direkt me email. Klienti e hap, e lexon dhe e nënshkruan direkt nga telefoni ose kompjuteri i tij. Ju shikoni çdo hap në kohë reale — nga momenti i dërgimit deri te nënshkrimi final.",
    en: "Create professional quotes with different templates and send them directly by email. The client opens, reads and signs directly from their phone or computer. You see every step in real time — from the moment of sending to the final signature.",
    es: "Cree cotizaciones profesionales con diferentes plantillas y envíelas directamente por correo electrónico. El cliente abre, lee y firma directamente desde su teléfono o computadora. Usted ve cada paso en tiempo real — desde el momento del envío hasta la firma final.",
    de: "Erstellen Sie professionelle Angebote mit verschiedenen Vorlagen und senden Sie sie direkt per E-Mail. Der Kunde öffnet, liest und unterschreibt direkt von seinem Telefon oder Computer. Sie sehen jeden Schritt in Echtzeit — vom Moment des Versands bis zur endgültigen Unterschrift.",
    mk: "Креирајте професионални понуди со различни шаблони и испратете ги директно по е-пошта. Клиентот отвора, чита и потпишува директно од телефонот или компјутерот. Вие го гледате секој чекор во реално време — од моментот на испраќање до финалниот потпис.",
  fr: "Créez des devis professionnels avec différents modèles et envoyez directement par e-mail. Le client ouvre, lit et signe directement depuis son téléphone ou ordinateur. Vous voyez chaque étape en temps réel — de l'envoi à la signature finale.", pt: "Crie orçamentos profissionais com diferentes modelos e envie diretamente por e-mail. O cliente abre, lê e assina diretamente do seu telemóvel ou computador. Vê cada etapa em tempo real — do momento do envio à assinatura final.", it: "Crea preventivi professionali con diversi modelli e inviati direttamente via e-mail. Il cliente apre, legge e firma direttamente dal suo telefono o computer. Vedi ogni fase in tempo reale — dal momento dell'invio alla firma finale." },
  benefits: [
    { sq: "Dërgim elektronik me email — pa printer, pa letër", en: "Electronic delivery by email — no printer, no paper", es: "Entrega electrónica por correo — sin impresora, sin papel", de: "Elektronischer Versand per E-Mail — kein Drucker, kein Papier", mk: "Електронска достава по е-пошта — без печатач, без хартија" , fr: "Livraison électronique par e-mail — sans imprimante, sans papier", pt: "Entrega eletrónica por e-mail — sem impressora, sem papel", it: "Consegna elettronica via e-mail — senza stampante, senza carta" },
    { sq: "Klienti nënshkruan direkt nga telefoni ose PC", en: "Client signs directly from phone or PC", es: "El cliente firma directamente desde teléfono o PC", de: "Kunde unterschreibt direkt vom Telefon oder PC", mk: "Клиентот потпишува директно од телефон или PC" , fr: "Le client signe directement depuis son téléphone ou PC", pt: "O cliente assina diretamente do telemóvel ou PC", it: "Il cliente firma direttamente dal telefono o PC" },
    { sq: "Ju nënshkruani gjithashtu nga aplikacioni", en: "You also sign from the app", es: "Usted también firma desde la aplicación", de: "Sie unterschreiben ebenfalls über die App", mk: "Вие исто така потпишувате од апликацијата" , fr: "Vous signez également depuis l'application", pt: "Também assina a partir da aplicação", it: "Firmi anche tu dall'app" },
    { sq: "Gjurmim: dërguar → hapur → lexuar → nënshkruar", en: "Tracking: sent → opened → read → signed", es: "Seguimiento: enviado → abierto → leído → firmado", de: "Verfolgung: gesendet → geöffnet → gelesen → unterschrieben", mk: "Следење: испратено → отворено → прочитано → потпишано" , fr: "Suivi: envoyé → ouvert → lu → signé", pt: "Rastreamento: enviado → aberto → lido → assinado", it: "Monitoraggio: inviato → aperto → letto → firmato" },
    { sq: "Njoftim i menjëhershëm kur klienti e hap ofertën", en: "Instant alert when client opens the quote", es: "Alerta instantánea cuando el cliente abre la cotización", de: "Sofortige Benachrichtigung, wenn der Kunde das Angebot öffnet", mk: "Моментално известување кога клиентот ја отвора понудата" , fr: "Alerte instantanée quand le client ouvre le devis", pt: "Alerta imediato quando o cliente abre o orçamento", it: "Avviso istantaneo quando il cliente apre il preventivo" },
    { sq: "Konvertim automatik Ofertë → Faturë pas aprovimit", en: "Auto conversion Quote → Invoice after approval", es: "Conversión automática Cotización → Factura tras aprobación", de: "Automatische Umwandlung Angebot → Rechnung nach Genehmigung", mk: "Автоматска конверзија Понуда → Фактура по одобрување" , fr: "Conversion automatique Devis → Facture après approbation", pt: "Conversão automática Orçamento → Fatura após aprovação", it: "Conversione automatica Preventivo → Fattura dopo l'approvazione" },
  ],
  workflow: [
    { step: "1", sq: "Zgjidhni shabllon oferte dhe plotësoni artikujt, çmimet dhe kushtet", en: "Choose a quote template and fill in items, prices and terms", es: "Elija una plantilla de cotización y complete artículos, precios y términos", de: "Wählen Sie eine Angebotsvorlage und füllen Sie Artikel, Preise und Bedingungen aus", mk: "Изберете шаблон за понуда и пополнете ги артиклите, цените и условите" , fr: "Choisissez un modèle de devis et remplissez les articles, prix et conditions", pt: "Escolha um modelo de orçamento e preencha artigos, preços e condições", it: "Scegli un modello di preventivo e compila articoli, prezzi e condizioni" },
    { step: "2", sq: "Dërgoni ofertën me email direkt nga Clientlly — klienti merr linkun", en: "Send the quote by email directly from Clientlly — the client receives the link", es: "Envíe la cotización por correo directamente desde Clientlly — el cliente recibe el enlace", de: "Senden Sie das Angebot per E-Mail direkt von Clientlly — der Kunde erhält den Link", mk: "Испратете ја понудата по е-пошта директно од Clientlly — клиентот го добива линкот" , fr: "Envoyez le devis par e-mail directement depuis Clientlly — le client reçoit le lien", pt: "Envie o orçamento por e-mail diretamente do Clientlly — o cliente recebe o link", it: "Invia il preventivo via e-mail direttamente da Clientlly — il cliente riceve il link" },
    { step: "3", sq: "Gjurmoni në kohë reale: kur hapet, sa herë lexohet, dhe kur nënshkruhet", en: "Track in real time: when it's opened, how many times it's read, and when it's signed", es: "Rastree en tiempo real: cuándo se abre, cuántas veces se lee y cuándo se firma", de: "Verfolgen Sie in Echtzeit: wann es geöffnet wird, wie oft es gelesen wird und wann es unterschrieben wird", mk: "Следете во реално време: кога се отвора, колку пати се чита и кога се потпишува" , fr: "Suivez en temps réel: quand il est ouvert, combien de fois lu et quand signé", pt: "Acompanhe em tempo real: quando é aberto, quantas vezes lido e quando assinado", it: "Monitora in tempo reale: quando viene aperto, quante volte letto e quando firmato" },
    { step: "4", sq: "Klienti nënshkruan dixhitalisht nga telefoni ose kompjuteri — pa printer", en: "Client signs digitally from phone or computer — no printer needed", es: "El cliente firma digitalmente desde teléfono o computadora — sin necesidad de impresora", de: "Kunde unterschreibt digital vom Telefon oder Computer — kein Drucker nötig", mk: "Клиентот потпишува дигитално од телефон или компјутер — без потреба од печатач" , fr: "Le client signe numériquement depuis téléphone ou ordinateur — aucune imprimante nécessaire", pt: "O cliente assina digitalmente do telemóvel ou computador — sem impressora necessária", it: "Il cliente firma digitalmente dal telefono o computer — nessuna stampante necessaria" },
    { step: "5", sq: "Oferta e aprovuar konvertohet automatikisht në faturë — pa rishkrim manual", en: "Approved quote automatically converts to invoice — no manual rewriting", es: "La cotización aprobada se convierte automáticamente en factura — sin reescritura manual", de: "Genehmigtes Angebot wird automatisch in Rechnung umgewandelt — kein manuelles Neuschreiben", mk: "Одобрената понуда автоматски се конвертира во фактура — без рачно препишување" , fr: "Le devis approuvé se convertit automatiquement en facture — aucune réécriture manuelle", pt: "O orçamento aprovado converte-se automaticamente em fatura — sem reedição manual", it: "Il preventivo approvato si converte automaticamente in fattura — nessuna riscrittura manuale" },
  ],
  capabilities: [
    { icon: "📄", title: { sq: "Shabllone Profesionale", en: "Professional Templates", es: "Plantillas Profesionales", de: "Professionelle Vorlagen", mk: "Професионални Шаблони" , fr: "Modèles professionnels", pt: "Modelos profissionais", it: "Modelli professionali" }, desc: { sq: "Shabllone të gatshme me logon dhe markën tuaj. Personalizoni ngjyrat, fontet dhe strukturën", en: "Ready templates with your logo and brand. Customize colors, fonts and structure", es: "Plantillas listas con su logo y marca. Personalice colores, fuentes y estructura", de: "Fertige Vorlagen mit Ihrem Logo und Ihrer Marke. Farben, Schriften und Struktur anpassen", mk: "Готови шаблони со вашето лого и бренд. Прилагодете бои, фонтови и структура" , fr: "Modèles prêts avec votre logo et marque. Personnalisez couleurs, polices et structure", pt: "Modelos prontos com o seu logótipo e marca. Personalize cores, tipos de letra e estrutura", it: "Modelli pronti con il tuo logo e brand. Personalizza colori, font e struttura" } },
    { icon: "✍️", title: { sq: "Nënshkrim Dixhital", en: "Digital Signature", es: "Firma Digital", de: "Digitale Unterschrift", mk: "Дигитален Потпис", fr: "Signature numérique", pt: "Assinatura digital", it: "Firma digitale" }, desc: { sq: "Klienti dhe ju nënshkruani nga çdo pajisje — ligjërisht e vlefshme dhe e sigurt", en: "Client and you sign from any device — legally valid and secure", es: "El cliente y usted firman desde cualquier dispositivo — legalmente válido y seguro", de: "Kunde und Sie unterschreiben von jedem Gerät — rechtlich gültig und sicher", mk: "Клиентот и вие потпишувате од секој уред — правно валиден и безбеден" , fr: "Le client et vous signez depuis n'importe quel appareil — légalement valide et sécurisé", pt: "O cliente e você assinam de qualquer dispositivo — legalmente válido e seguro", it: "Il cliente e tu firmate da qualsiasi dispositivo — legalmente valido e sicuro" } },
    { icon: "👁️", title: { sq: "Gjurmim i Plotë", en: "Full Tracking", es: "Seguimiento Completo", de: "Vollständige Verfolgung", mk: "Целосно Следење" , fr: "Suivi complet", pt: "Rastreamento completo", it: "Monitoraggio completo" }, desc: { sq: "Shikoni kur oferta hapet, lexohet dhe nënshkruhet — me data dhe orare të sakta", en: "See when the quote is opened, read and signed — with exact dates and times", es: "Vea cuándo la cotización se abre, lee y firma — con fechas y horas exactas", de: "Sehen Sie, wann das Angebot geöffnet, gelesen und unterschrieben wird — mit genauen Daten und Zeiten", mk: "Видете кога понудата се отвора, чита и потпишува — со точни датуми и времиња" , fr: "Voir quand le devis est ouvert, lu et signé — avec dates et heures exactes", pt: "Ver quando o orçamento é aberto, lido e assinado — com datas e horas exatas", it: "Vedere quando il preventivo viene aperto, letto e firmato — con date e orari esatti" } },
    { icon: "🔔", title: { sq: "Njoftime Automatike", en: "Auto Notifications", es: "Notificaciones Automáticas", de: "Automatische Benachrichtigungen", mk: "Автоматски Известувања" , fr: "Notifications automatiques", pt: "Notificações automáticas", it: "Notifiche automatiche" }, desc: { sq: "Merrni njoftim menjëherë kur klienti e hap ose e nënshkruan ofertën tuaj", en: "Get notified immediately when the client opens or signs your quote", es: "Reciba notificación inmediata cuando el cliente abra o firme su cotización", de: "Erhalten Sie sofort eine Benachrichtigung, wenn der Kunde Ihr Angebot öffnet oder unterschreibt", mk: "Добијте известување веднаш кога клиентот ја отвора или потпишува вашата понуда" , fr: "Soyez notifié immédiatement quand le client ouvre ou signe votre devis", pt: "Seja notificado imediatamente quando o cliente abre ou assina o seu orçamento", it: "Ricevi notifica immediata quando il cliente apre o firma il tuo preventivo" } },
    { icon: "🔄", title: { sq: "Konvertim në Faturë", en: "Invoice Conversion", es: "Conversión a Factura", de: "Rechnungsumwandlung", mk: "Конверзија во Фактура" , fr: "Conversion en facture", pt: "Conversão para fatura", it: "Conversione in fattura" }, desc: { sq: "Me një klikim, oferta e aprovuar bëhet faturë — pa rishkrim të dhënash", en: "With one click, the approved quote becomes an invoice — no data re-entry", es: "Con un clic, la cotización aprobada se convierte en factura — sin reingresar datos", de: "Mit einem Klick wird das genehmigte Angebot zur Rechnung — keine erneute Dateneingabe", mk: "Со еден клик, одобрената понуда станува фактура — без повторно внесување податоци" , fr: "En un clic, le devis approuvé devient une facture — aucune re-saisie de données", pt: "Com um clique, o orçamento aprovado torna-se uma fatura — sem re-inserção de dados", it: "Con un clic, il preventivo approvato diventa una fattura — nessuna re-immissione dei dati" } },
    { icon: "📊", title: { sq: "Raporte Ofertash", en: "Quote Reports", es: "Informes de Cotizaciones", de: "Angebotsberichte", mk: "Извештаи за Понуди" , fr: "Rapports de devis", pt: "Relatórios de orçamentos", it: "Report preventivi" }, desc: { sq: "Statistika të ofertave: sa janë dërguar, aprovuar, refuzuar dhe në pritje", en: "Quote statistics: how many sent, approved, rejected and pending", es: "Estadísticas de cotizaciones: cuántas enviadas, aprobadas, rechazadas y pendientes", de: "Angebotsstatistiken: wie viele gesendet, genehmigt, abgelehnt und ausstehend", mk: "Статистики за понуди: колку се испратени, одобрени, одбиени и во чекање" , fr: "Statistiques de devis: combien envoyés, approuvés, rejetés et en attente", pt: "Estatísticas de orçamentos: quantos enviados, aprovados, rejeitados e pendentes", it: "Statistiche preventivi: quanti inviati, approvati, rifiutati e in attesa" } },
  ],
};

export default function FeatureQuotes() {
  return <FeatureDetail data={data} />;
}
